### ISSUE TITLE
Suggestion: Add docs on $ref resolving 

### ISSUE THREAD

**Issue by BlaineAtAffirm** [Julian/jsonschema#135]
As seen by issues #132  and #98 , there are some people who have been confused about how to use jsonschema in order to resolve references between schema files. I myself couldn't figure it out until I saw issue #98. I suggest adding some documentation here or perhaps at http://python-jsonschema.readthedocs.org/en/latest/ if it is affiliated.

**Comment by Julian** [comment]
> Revealing implementation a bit there I think ?

It's explicit in the API that `RefResolver` takes a (mutable) mapping as a cache, it's not particularly its concern what mapping that is as long as it satisfies that interface.

**Comment by Julian** [comment]
Although it looks like RefResolver does some more setup these days, which won't break things but which might actually signal that it's time for some more thought there.
