### ISSUE TITLE
Schema validation error on hyperschema link with $ref

### ISSUE THREAD

**Issue by ricobl** [Julian/jsonschema#173]
I've got the following error trying to validate a schema with a reference on a link:

```
ValidationError: u'#' is not of type u'object'
```

The base schema:

```json
{
    "$ref": "http://json-schema.org/draft-03/hyper-schema#"
}
```

Here is a stripped version of the schema I'm trying to validate:

```json
{
    "$schema": "http://json-schema.org/draft-03/hyper-schema#",
    "links": [
        {
            "href": "{id}",
            "method": "POST",
            "rel": "create",
            "schema": {
                "$ref": "#"
            }
        }
    ]
}
```

I've forked the project and added a test exploring this issue:
https://github.com/ricobl/jsonschema/commit/565084fabaadb1fd6a0c6791818d21563f88de81#diff-d41d8cd98f00b204e9800998ecf8427e

I didn't get any error using the online validators:
https://json-schema-validator.herokuapp.com/
http://jsonschemalint.com/

Looks like the validator isn't expanding the `$ref`, trying to validate the schema URI as an object.

Any clues?

**Comment by Julian** [comment]
So, after a long while I took a quick look at this just now. Ultimately what this ends up resolving to in a minimal-ish reproducing case is:

```
schema = {'additionalProperties': {'$ref': 'http://json-schema.org/draft-03/hyper-schema#'}}
instance = {'$ref': '#'}
```

which I think is *correctly* failing. I'm not sure why the apps you linked are green, they possibly are not even resolving the refs in the first place.

I see roughly what you're trying to do, which makes me think something is wrong with the draft 3 meta schema, but given that we're on the way to draft 5 I think the ship might have sailed there.

I'm going to close this out but feel free to follow up if you're still alive and care, sorry this took so long.

**Comment by ricobl** [comment]
Sounds fair @Julian! Thanks for your time.
