### ISSUE TITLE
Useless error message with very long pattern

### ISSUE THREAD

**Issue by stpierre** [Julian/jsonschema#177]
The error message when an element fails pattern validation is useless when the pattern is extremely long. It would be nice to have a way to override the default message, perhaps by using the ``description`` field in the type subschema. E.g.:

    'thing': {
        'type': 'string',
        'pattern': '^\S*$',
        'description': 'any number of non-whitespace characters'
    }

...might yield:

    ValidationError("'foo bar' does not match pattern: any number of non-whitespace characters")

That overloads the use of the ``description`` field, though, so I'm not sure that's the best way, either. I'm happy to implement this, I just didn't want to put in a PR with an approach you wouldn't accept.

Thanks!

**Comment by thiagomarini** [comment]
I published a little package that formats error messages for end users https://pypi.org/project/json_payload_validator/
