### ISSUE TITLE
Coercion

### ISSUE THREAD

**Issue by skatenerd** [Julian/jsonschema#195]
Are there any plans on the horizon to "coerce" documents into a valid format?

It would be nice if `{"should_be_number": "82"}` actually validated against a schema with `{"type": "number"}`.  It would be even better if I could get my hands on a document that looks like `{"should_be_a_number":  82}`.

Would such a patch be welcome? Or is it against the philosophy of this library?

**Comment by Julian** [comment]
Coercion is a thing that https://github.com/Julian/Seep is designed for (it lacks someone who wants to drive it though at the moment). A patch there would certainly be welcome.

**Comment by skatenerd** [comment]
A patch here or a patch there?
