### ISSUE TITLE
If '$ref' is present in the actual json, the validity of that reference should also be checked.

### ISSUE THREAD

**Issue by prat0318** [Julian/jsonschema#196]
I understand that '$ref' is primarily for json schemas, but in my case i have '$ref' in actual json. Is there a way to validate that the reference '$ref' is making, is actually present? Can i use some method of jsonschema which validates schema and run it on json as well?

**Comment by Julian** [comment]
I'm not sure what you mean by "actual json". Do you mean you have a string?

**Comment by prat0318** [comment]
"actual json" meaning the json instance (the first param of `validate()`) which is being validated against a schema. What if, the instance contains a '$ref'. Validity of this reference is not checked as of now. I hope i made sense.

**Comment by Julian** [comment]
Ah, yeah, sure so that's since your schema just says it's a string. If you wanted to validate that it's a valid reference, you might want to use `format` with either `uri` or something even stronger (your own format checker), and then try to resolve the ref, failing if it doesn't resolve.

**Comment by Julian** [comment]
Closing this out, hope that helped, but lemme know if you need some more direction here.

**Comment by dnephin** [comment]
I believe #144 is attempting to fix what this issue was describing.  

Currently if a schema has a bad $ref, it may still be considered valid.
