### ISSUE TITLE
Mention other json schema validation implementations

### ISSUE THREAD

**Issue by leplatrem** [Julian/jsonschema#199]
In the project title, you mention this tool as *Another* implementation of JSON schema for python.

Could you please mention, how it compares to others, and what are your motivations or scope for this one ? i.e. help a programmer choose the best one depending on her particular needs :)

Thanks !
(*Great job heh ;)*)

**Comment by Julian** [comment]
Thanks :).

I actually don't have much experience with any of the others. There are a few other libraries which claim to be JSON Schema implementations (see http://json-schema.org/implementations.html) -- I haven't used them though so I can just tell you about this one :) -- It use the comprehensive official test suite (https://github.com/json-schema/JSON-Schema-Test-Suite) to test compliance (n.b. I wrote it). The reason I wrote it was that at the time when I started, I tried the other libraries, and they were either lacking in test coverage, or implemented in a way I didn't like. So I wrote this, which has a few things I still don't like, but generally, I think it's fairly solid, and has thankfully had some pretty wide adoption from what I've seen.

Feel free to follow up with any questions, or if you end up using it, lemme know how it goes!
