### ISSUE TITLE
Forgot to tag version 2.4.0

### ISSUE THREAD

**Issue by tobihan** [Julian/jsonschema#205]
Hi,

did you forget to tag the release 2.4.0? I'm reporting this because Linux distributions are watching the tags to get notified about new releases. Also looking at the github page it looks like 2.3.0 is the last release.

Best,
Tobias

**Comment by Julian** [comment]
Hey, thanks.

I tagged it but didn't push the tag. Sort of odd that that's how they'd decide to watch for releases, tags are for my own convenience, people who want to watch for releases can watch PyPI -- regardless, pushed, and hopefully soon we'll be using tags for versioning which will make even them reliable, so everyone should be happy.

Appreciate the info!

**Comment by tobihan** [comment]
It gets more and more common that projects provide only a git repo and
no tarballs, and especially small projects increasingly define their
releases by tags. This is also why the "releases" page on github is
populated more or less automatically using tags.

I know only about Debian: normally our tools watch the upstream download
website for new tarballs. When the upstream website is only a github
project page, we watch the tags.

Best,
Tobias

Am 15.03.2015 um 15:31 schrieb Julian Berman:
