### ISSUE TITLE
Add LICENSE doc

### ISSUE THREAD

**Issue by iandanforth** [Julian/jsonschema#206]
Main repo needs LICENSE.

**Comment by mistercrunch** [comment]
+1! What's the license of for this project?

**Comment by Julian** [comment]
MIT, see the license file in the root of the repo.

**Comment by Arthur-Milchior** [comment]
Actually, the LICENSE is not in the root of the repo; but in the json folder. Which means that technically, jsonschema has no license. 
The license was moved into root in commit ed332a1819789daad35de5faeb0986624f808c79,which is an ancestor of HEAD so I must admit I fail to understand why this problem arrive.

Actually, I was warned by fossa.com that the project anki uses this module, without proper licensing.

**Comment by Julian** [comment]
Again, there is a license in the [root of the repo as well which covers this library](https://github.com/Julian/jsonschema/blob/master/COPYING).

**Comment by iandanforth** [comment]
'COPYING' is going to continue to confuse people it looks like. Unless there's a strong objection I can open a PR to rename it to 'LICENSE' just to bury this.
