### ISSUE TITLE
Specifying a 'formats' parameter to FormatChecker will always raise an exception

### ISSUE THREAD

**Issue by dshirley** [Julian/jsonschema#210]
https://github.com/Julian/jsonschema/blob/master/jsonschema/_format.py#L30

      checkers = {}

      def __init__(self, formats=None):
          if formats is None:
              self.checkers = self.checkers.copy()
          else:
              self.checkers = dict((k, self.checkers[k]) for k in formats)

Checkers is initialized to an empty dict.
A KeyError will always get thrown when iterating through formats and asking for self.checkers[k]

I wish I could propose a fix, but I can't figure out what formats it is actually supposed to take.
It seems like there's supposed to be a dict containing all of the "checkers" and then self.checkers is supposed to be populated with the ones specified in the formats parameter.  Is that right?

**Comment by dnephin** [comment]
Have you tried using one of the instantiated `FormatCheckers` here: https://github.com/Julian/jsonschema/blob/master/jsonschema/_format.py#L239 ?

It seems they are build up using decorators which populate the class level dict?

**Comment by dnephin** [comment]
The docs get into as well: https://python-jsonschema.readthedocs.org/en/latest/validate/#validating-formats

**Comment by dshirley** [comment]
Ahh!  Thanks.  I had reviewed those docs, and I tried following the example except I plugged in "date-time" as the format rather than "hostname".  This failed off the bat.  Low and behold, at the bottom of that section it say you have to add another package dependency to get date-time validation.

Is there any reason that jsonschema doesn't set it as a dependency so that it automatically gets included when jsconschema is installed?

Also, why doesn't jsonschema turn on format verification by default?  Sure the spec doesn't mandate it, but what's the harm in making it a default option?  It seems like there'd be more people that want it on than want it off.  I assume most schemas won't even use the "format" keyword.

**Comment by dshirley** [comment]
PS.  This issue can be closed, but hopefully someone can still respond to my questions.  Thanks!

**Comment by Julian** [comment]
@dshirley yeah, I went back and forth on both of those -- basically it's off by default because when I started, I mostly didn't want format on for myself, I was using it for documentation, which was why the spec doesn't make it mandatory.

I'm not sure it was the correct choice in retrospect, but we're locked in due to backwards compatibility for the moment unfortunately.
