### ISSUE TITLE
anyof/oneof don't work

### ISSUE THREAD

**Issue by pyKun** [Julian/jsonschema#216]
// v2.4.0
from jsonschema import validate
date = ['eeeeee']

schema0 = {"type":"array", "items":{"type":"number"}}
schema1 = {"type":"array", "items":{"oneof":[{"type":"number"}]}} 
schema1 = {"type":"array", "items":{"anyof":[{"type":"number"}]}} 

validate(data, schema0)
// raise :)

validate(data, schema1)
// no raise :(

validate(data, schema2)
// no raise :(

**Comment by Julian** [comment]
`anyof` and `oneof` "don't work" because they're not things.

You're looking for `anyOf` and `oneOf`.
