### ISSUE TITLE
The validation errors are not cumulated

### ISSUE THREAD

**Issue by angelopoerio** [Julian/jsonschema#217]
If I run a piece of code like this

```python
from jsonschema import validate, ValidationError

schema = {"type" : "object",
     "properties" : {
		 "field_a": {"type": "string", "enum": ["STRINGA", "STRINGB"]},
                 "field_b" : {"type" : "number"},
                 "field_c" : {"type" : "string"},
     },
 }

try:
	validate({"field_a" : "NOT_A_STRING", "field_b" : "A_STRING", "field_c": 15}, schema)
except ValidationError as ex:
	print ex
```

This is the output you get:
```python
'A_STRING' is not of type 'number'

Failed validating 'type' in schema['properties']['field_b']:
    {'type': 'number'}

On instance['field_b']:
    'A_STRING'
```

A big improvement would be to have all the validation errors listed. In the example you should get a ValidationError on all the three fields (field_a, field_b, field_c).

**Comment by Julian** [comment]
This is what [`Validator.iter_errors`](http://python-jsonschema.readthedocs.org/en/latest/validate/#jsonschema.IValidator.iter_errors) is for.

**Comment by angelopoerio** [comment]
You are right, what about adding this feature to the exception that gets raised by the validate() function?
I think it would be very helpful to add an example usage of iter_errors on the homepage of https://python-jsonschema.readthedocs.org/en/latest/.
Anyway it is a great library :)

**Comment by Julian** [comment]
Hi!

The two APIs exist specifically to satisfy the two use cases :)

Adding an example might be nice, I tried to keep the homepage fairly clean for someone who just wants to see an example of the high level, and then keep the details to the doc pages.

Think I'm going to close this but if you feel strongly feel free to open a PR and I'll have a look.

And thank you!
