### ISSUE TITLE
ValidationError: 10000.0 is not a multiple of 1e-08

### ISSUE THREAD

**Issue by peter-conalgo** [Julian/jsonschema#218]
However, 10000 is a multiple of 1E-8, except not quite in floats:

```python
>>> 10000.0 % 1e-08
9.999790774391699e-09

>>> from decimal import Decimal
>>> Decimal('10000.0') % Decimal('1e-8')
Decimal('0E-8')
````

I've switching to using simplejson (with `use_decimal=True` flag) to read both my data and schema JSON files, and the validation code works correctly in that case.

Not sure if this should be considered a bug, but at least the validation error message is misleading. I'm excited to soon learn how well Javascript libraries validate this schema.

**Comment by Julian** [comment]
Hi! Thanks for the report.

Yeah, bit misleading. Maybe adding the remainder to the error message would be helpful. Any chance you'd be interested in a pull request?

**Comment by peter-conalgo** [comment]
Sorry, I don't think it's worth fixing.
