### ISSUE TITLE
Custom $schema URIs not supported

### ISSUE THREAD

**Issue by foxx** [Julian/jsonschema#226]
JSON schema should allow you to use custom `$schema` URIs as documented [here][1] to create extended schemas, however this doesn't seem to work as no HTTP request is generated for the following schema;

```
{
    "$schema": "http://example.com/allalalal"
}
```

I had a look through existing issues and couldn't see anything else related to this. I also couldn't see any reference in the code to this, so I'm guessing this should be marked as a feature request?

[1]: http://spacetelescope.github.io/understanding-json-schema/reference/schema.html

**Comment by Julian** [comment]
What do you mean by no HTTP request is generated?

Putting a `$schema` in a schema (hee hee) doesn't generate an HTTP request. When are you expecting one?

**Comment by foxx** [comment]
Oh, I was under the impression that schemas themselves can be extended by using `$schema`, there's a detailed post about it [here][1] as well. If the schema is one of the predefined ones, e.g. draftv4, then an implementation will most likely use a local copy. However if the schema is a custom URI, then I'd assume a request would be generated to fetch it. Have I misinterpreted the spec somewhere?

[1]: http://snowplowanalytics.com/blog/2014/05/15/introducing-self-describing-jsons/

**Comment by foxx** [comment]
Ah, after further analysis of the spec, it would appear I have misinterpreted. I also verified against another well used library and that doesn't include such a feature either. Apologies for the time wasting.

**Comment by Julian** [comment]
`$schema` means "here's a URI for the metaschema for this schema".

There's some docs on extending validators [here](https://python-jsonschema.readthedocs.org/en/latest/creating/) which you'd use if you were extending an existing metaschema (or creating a new one), but you'd just fetch the meta schema beforehand most likely, or else use `check_schema` on a validator with a `RefResolver` that went and grabbed the metaschema.

**Comment by Julian** [comment]
Ah no worries!

**Comment by foxx** [comment]
Makes sense, thank you :)
