### ISSUE TITLE
Why not check in _version.py?

### ISSUE THREAD

**Issue by asottile** [Julian/jsonschema#229]
Just curious.  I found it a bit difficult to figure out what the current version was from browsing via github

**Comment by Julian** [comment]
`_version.py` is autogenerated from (git) tags every time `setup.py` is run using http://vcversioner.readthedocs.org/en/latest/. Unfortunately it looks like I forgot to push the tag for 2.5.0 (thanks git) -- what I had in mind for this though is that you'd be able to tell from the Releases tab on GitHub.

Does that make sense?

**Comment by asottile** [comment]
hmmm, I guess that's fine

**Comment by Julian** [comment]
Would possibly adding a current release badge / shield / whatever they're called help?

**Comment by Julian** [comment]
Badge added.

**Comment by asottile** [comment]
<3
