### ISSUE TITLE
Add IDN support for hostname format.

### ISSUE THREAD

**Issue by eirnym** [Julian/jsonschema#238]
Please, add IDN support for hostname format checking. Now I have to convert it before I check domain and after transfer it to Javascript code. 

you can use [idna library](https://pypi.python.org/pypi/idna/) to convert it internally to ASCII.

**Comment by Julian** [comment]
Hi. Thanks for the report.

It looks like the specification defines hostnames according to [RFC1034](http://json-schema.org/latest/json-schema-validation.html#anchor114). I'm not an expert on internet specs, and I actually don't see a definition of host names in that RFC, I see one in a couple of others though. IDNs look like they're specified by later RFCs. So I suspect that this behavior is actually correct, and that the hostname validator is not actually meant to include IDNs.

But given that the above is unclear (and that we're in the process of cleaning up the draft and removing mistakes in prep for a draft 5), please feel free to open an issue on the [spec](https://github.com/json-schema-org/json-schema-spec) especially if you disagree with the above assessment.

Also, regardless, check out the [documentation](http://python-jsonschema.readthedocs.org/en/latest/validate/#validating-formats) for this library if you haven't already, it has info on defining your own format checkers, should you want to.

Thanks.

**Comment by eirnym** [comment]
IDN is just encoding used to encode non-ascii characters to valid hostname described in RFC1034.

Unfortunately, your formatter API doesn't support any extending, and I have to use part of your code (not extend) to implement IDN wrapper to use your library.

So I want to this feature be added into your library as optional, something like this:

````python
try:
   import idna
except ImportError:
   idna = None


@_checks_drafts(draft3="host-name", draft4="hostname")
def is_host_name(instance):
    if not isinstance(instance, str_types):
        return True
    if idna # 
    instance = idna.encode(
        value, uts46=True, transitional=True).decode('utf-8')
    if not _host_name_re.match(instance):
        return False
    components = instance.split(".")
    for component in components:
        if len(component) > 63:
            return False
    return True
````

**Comment by Julian** [comment]
I'm not sure what you mean by the formatter API not supporting extending. Did you read the documentation I linked? There is a documented API for extending with new format checkers.

And thanks for the info, I'll read into what you mentioned.

**Comment by eirnym** [comment]
I mean default validators are not following this API.

**Comment by Julian** [comment]
What is a default validator? `FormatChecker` is an object, separate from validators. It has a `.checks` method which adds new format checkers, and `.checkers` which lets you access any existing format checkers. Both are documented there but feel free to suggest improvements to the documentation, I would love to clarify anything that's unclear, and there's a definite lack of examples.

**Comment by eirnym** [comment]
Why I can't use your default checkers?

**Comment by Julian** [comment]
You can. Please read the documentation and what I wrote above and ask specific questions.

**Comment by eirnym** [comment]
I can't use method `is_host_name` because it in private package.

**Comment by Julian** [comment]
Yes, it is, the appropriate API for accessing it is `FormatChecker().checks(instance, "hostname")`, or to directly call FormatChecker.checkers["hostname"]'s checker.

**Comment by Julian** [comment]
IDN support appears to be coming in Draft 7.
