### ISSUE TITLE
How to $ref require?

### ISSUE THREAD

**Issue by nicklasb** [Julian/jsonschema#246]
Hi,
I am wondering how to "inherit" a require array, because I think something I used to do have stopped working;

Also it *feel* like this used to work, although I am not sure if it really did. At least, it did not result in any errors. I missed out on having negative tests on missing properties on the validation as I felt like that would be testing jsonschema rather than my code.

So either way, this is what the schema looks like that used to work:

```js
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "description": "MBE Right Schema",
  "title": "Right",
  "type": "object",
  "version": "0.1",
  "allOf": [
    {
      "properties":
      {
        "$ref": "mbe://node.json#/properties"
      }
    },
    {
      "properties": {
        "description": {
          "description": "The description of the right",
          "type": "string",
          "propertyId": "01678a5c-956e-44fb-b6e0-f549f5042af9"
        }
      }
    },
    {
      "$ref": "mbe://node.json#/required"
    }
  ],
  "collection": "node",
  "schemaId": "4288fc06-d615-4f1c-ac10-8328153f2c54"
}
```

Now I am getting an error in Validator.iterErrors
```python
        def iter_errors(self, instance, _schema=None):
            if _schema is None:
                _schema = self.schema

            scope = _schema.get(u"id")  # HERE BE ERRORS
```

The error is: 
```
AttributeError: 'list' object has no attribute 'get'". 
```

It seems to resolve the schema properly, the problem is that the resulting array isn't handled, the value is: 
`['name', 'createdWhen', 'schemaId', 'canRead', 'canWrite']`

**Comment by Julian** [comment]
Hi. Same here, please include a full self contained example, otherwise I can't really be of help here.

**Comment by nicklasb** [comment]
Well, this is also a question, I am wondering how to "inherit" a require array. 
Is that possible, and am I going mad if I am thinking that it used to work?

**Comment by Julian** [comment]
What's a "require array"?

**Comment by nicklasb** [comment]
The array of attributes that are required.
```json
    {
      "$ref": "mbe://node.json#/required"
    }
```
resolves to something like:
```json
    {
      "required": ["description","nodeId"]
    }
```

**Comment by Julian** [comment]
The way to add on to that would be to use `allOf` with another schema and some more required properties.

**Comment by nicklasb** [comment]
Basically, I had to rewrite:
```json
{		
    "$ref": "mbe://node.json/required"		
},		
{		
     "required": ["groups"]
}
```

to:

```json
"required": [
    "name",
    "createdWhen",
    "schemaId",
    "canRead",
    "canWrite",
    "groups"
],
```


You mean requiring them inside the "remote" schema?

**Comment by Julian** [comment]
I can't tell what you mean by the first one, that's not a valid schema, it's 2. But if you take those 2 as `allOf : [those two]`, then that's what I mean.

**Comment by nicklasb** [comment]
Aha, that might be it, if you are saying to this(below) is not valid schema, then that might be some newer check that raises an error:
```json

{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "description": "MBE Right Schema",
  "title": "Right",
  "type": "object",
  "version": "0.1",
  "allOf": [
    {
      "properties":
      {
        "$ref": "mbe://node.json#/properties"
      }
    },
    {
      "properties": {
        "description": {
          "description": "The description of the right",
          "type": "string",
          "propertyId": "01678a5c-956e-44fb-b6e0-f549f5042af9"
        }
      }
    },
    {		
        "$ref": "mbe://node.json/required"		
    },		
    {		
         "required": ["groups"]
    }
  ],
  "collection": "node",
  "schemaId": "4288fc06-d615-4f1c-ac10-8328153f2c54"
}
```

**Comment by nicklasb** [comment]
I will take a new look on the approach I am using, thanks for your time!
