### ISSUE TITLE
oneOf validations give confusing error messages

### ISSUE THREAD

**Issue by karenc** [Julian/jsonschema#248]
For example, my schema has something like this:

```
"oneOf": [
    {"required": ["field_a"]},
    {"required": ["field_b"]},
]
```

If the input does not have `field_a` or `field_b`, I get something like 
```"{'field_c': ['2000']} is not valid under any of the given schemas"```

If the input has both `field_a` and `field_b`, I get something like 
```"{'field_a': ['1'], 'field_b': ['2'], 'field_c': ['2000']} is valid under each of {'required': ['pool_id']}, {'required': ['tag_query']}"```

**Comment by Julian** [comment]
Hey!

Thanks! Can you suggest an error message that you'd find clearer possibly?

**Comment by karenc** [comment]
Hi!  Thanks for your quick response.

I think if the input does not have `field_a` or `field_b`,
`You must specify one of these fields: ["field_a"], ["field_b"]`.

If the input has both `field_a` and `field_b`, how about
`"field_a" and "field_b" are mutually exclusive`?

**Comment by Julian** [comment]
That would be hard to do other than in the very-very-specific example you have originally.

`oneOf` is fairly generic, it just takes two schemas and asks for one to be valid. Being able to roll up information from individual failures within them isn't trivial -- it happens to be that in the case where the schemas are as simple as two `required`s with nothing else, you could construct a higher level message like the one you wrote (`oneOf` would have to inspect the two sub-validation errors and then inspect the two schemas and see that it knows a high-level way of describing the situation, which would only really apply in your exact case). But this starts to get really hairy I think, each case is going to be different and it will just become adding special-cases for a bunch of different scenarios.

Maybe you've seen it already, but have you seen http://python-jsonschema.readthedocs.org/en/latest/errors/#jsonschema.exceptions.ValidationError by any chance?

**Comment by karenc** [comment]
Oh I haven't seen `ValidationError`, that'll be very useful.  Thanks!
