### ISSUE TITLE
Unable to validate a schema where a default value is a required value

### ISSUE THREAD

**Issue by darrenkenny** [Julian/jsonschema#250]
I have a schema where it has a required value, that also has a default value. 

I followed the example in the documentation for adding a default value mechanism, but
that is insufficient, in that the "required" validator always seems to end up being
called prior to the "properties" validator - so the defaulted value still appears to
be missing.

I know that this is unusual, but it's a valid use-case.

I've been able to work around it by some manipulation of the validators, along the
lines of the mechanism for setting the default, and ensuring the correct order
when calling the validators.

But, I believe this could be simply solved by replacing the dictionary of validators
by an ordered dictionary that allowed the processing of the properties prior
to the validation of the required list.

Simply logging the list of validators, by iterating over them in the same way
as the validator.py code does, I get the following output for a V4 schema:

```
required
minProperties
format
minLength
enum
additionalItems
maximum
not
minimum
maxItems
maxLength
uniqueItems
anyOf
properties
$ref
oneOf
minItems
pattern
allOf
patternProperties
multipleOf
dependencies
maxProperties
items
additionalProperties
type
```

I'm not sure how this order is arrived at (guessing based on the dictionary key hash values), but
it doesn't work for this use-case.

**Comment by dnephin** [comment]
If you have a default value for a field why does it need a `required` validator? If it's not provided then the default will be used, so you know there always be a value in the field. It seems like `required` is unnecessary if you have a default.

**Comment by darrenkenny** [comment]
That's very true - but, just like jsonschema, not all validators will fill in the defaults, so the required field is needed for these validators.

Being able to express that a value is required is useful then to enforce that something is specified in a system where that is the case - especially in mixed systems.

On the other hand, being able to default is also useful to consumers of implementations that do support defaulting.

I believe this is a valid case - but maybe I'm being just pedantic about it.

I've been digging further and it actually appears to be the lines:

```python
# From validators.py
if ref is not None:
    validators = [("$ref", ref)]
else:
    validators = iteritems(_schema)

for k, v in validators:
    validator = self.VALIDATORS.get(k)
```

That are the cause, not the order of the VALIDATORS dictionary.

It's this iteration that causes the required to be processed before properties for me.

**Comment by Julian** [comment]
`jsonschema` provides no guarantees about the order in which validators will be run, yeah. It's arbitrary, as you've noticed.

This is why I recommend doing `default` setting as a pre-validation step, transforming your instance, not by doing it while validating with a validator.

**Comment by Julian** [comment]
Closing this out but feel free to follow up if you want to discuss further.
