### ISSUE TITLE
A tuple should validate successfully when the schema designates it should be of type array

### ISSUE THREAD

**Issue by ju2wheels** [Julian/jsonschema#253]
I think there should be an option for this even if its not the default because having to go through a dataset to cast a tuple to list in order to validate it against a schema should be unnecessary. JSON doesnt have a tuple and for all intensive purposes it is an array. Also when you use json.dumps all tuples will be converted to arrays anyway, so from this perspective it would also make sense that validation should consider a tuple a JSON array.

**Comment by Julian** [comment]
Hi.

Are you aware of the [`types`](https://python-jsonschema.readthedocs.org/en/latest/validate/#jsonschema.IValidator) argument to validators?

**Comment by Julian** [comment]
Closing this out but feel free to follow up if need be. Thanks!

**Comment by nanthony21** [comment]
Now that the `types` argument appears to be gone, what is the simplest way to allow a `tuple` as an `array`?

**Comment by Julian** [comment]
Configuring a type checker is fairly similar: https://python-jsonschema.readthedocs.io/en/stable/validate/#validating-types

**Comment by nanthony21** [comment]
Thank you.
