### ISSUE TITLE
Question: python tool to generate fake data from json schema?

### ISSUE THREAD

**Issue by bruceflowers** [Julian/jsonschema#259]
I've found some other interesting libraries for autogenerating fake "ipsum"-style data from json schema, notably for node.js.  But I'd like to keep the stack small for what I'm trying to do and stick with python.

Do you know of any good tools/libraries to do this?

**Comment by Julian** [comment]
I don't know of any existing ones personally unfortunately, but from some brief discussions, https://github.com/DRMacIver/hypothesis would be a really really good place to start for this I think, and shouldn't require a ton of work to get simple cases working. If you do find or write something though would love to hear about it.

**Comment by Rovanion** [comment]
For posterity:

I found a package which does this: https://github.com/mlakewood/hypo_schema

No idea how complete or usable it is though, or which version of JSON schema it is for.
