### ISSUE TITLE
Validate that the schema is an object

### ISSUE THREAD

**Issue by vitorbaptista** [Julian/jsonschema#260]
According to http://json-schema.org/latest/json-schema-core.html:

> A JSON Schema is a JSON document, and that document MUST be an object.

Given that, I would expect (say) `jsonschema.validators.validator_for(51)` to raise a `SchemaError`, but what I get is:

```
>>> import jsonschema
>>> jsonschema.validators.validator_for(51)                                                                                                                                                                                                    
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "./venv/local/lib/python2.7/site-packages/jsonschema/validators.py", line 431, in validator_for
    return meta_schemas.get(schema.get(u"$schema", u""), default)
AttributeError: 'int' object has no attribute 'get'
```

`Draft4Validator` and `Draft3Validator`'s `check_schema()` behave as expected:

```
>>> jsonschema.validators.Draft4Validator.check_schema(51)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "./venv/local/lib/python2.7/site-packages/jsonschema/validators.py", line 76, in check_schema
    raise SchemaError.create_from(error)
jsonschema.exceptions.SchemaError: 51 is not of type u'object'

Failed validating u'type' in schema:
    {u'$schema': u'http://json-schema.org/draft-04/schema#',
     u'default': {},
(...)
```

**Comment by Julian** [comment]
The only API currently that validates whether a schema is valid first is the most "beginner-friendly" one, `jsonschema.validate` -- the other ones rely on the caller to make sure they check their schema first if they're not sure.

Here though there's kind of a chicken-and-egg problem. You can't really validate the schema until you know what validator is the one that goes with it.

So validating whether the thing passed into `validator_for` really just means validating it's a `dict` -- that's not the sort of thing that generally in Python you'd validate, it's the caller's responsibility to make sure they follow the docs.

At least that was the rationale when I wrote it -- if you have further thoughts please lemme know.

**Comment by vitorbaptista** [comment]
That's a fair point. But, with the API as it is now, I would have to code something like:

```python
def get_validator(schema):
    if isinstance(schema, dict):
        return jsonschema.validators.validator_for(schema)
    else:
        raise ValidationError
```

Basically, I'm pre-validating the schema before validating it with jsonschema. This feels like I'm breaking the separation of concerns: the code that validates the schema is not only inside jsonschema, but also inside my method. If JSON Schema changes to accept array as well (which is quite improbable), I would have not only to upgrade jsonschema but also fix my code.

You could say that it's a case of "be liberal with input, strict with output".

**Comment by Julian** [comment]
I don't think ValidationError is the right exception there.

Where do your schemas come from? Are you taking arbitrary user input?

**Comment by vitorbaptista** [comment]
I was taking arbitrary user input, but changed that so this issue doesn't affects me anymore. I still think this would be a small improvement to jsonschema, though. I'd be happy to send a pull request if you want. If not, please close this issue.

Thanks for your work on jsonschema. It has helped me a lot.

**Comment by Julian** [comment]
Gonna close this for now, for arbitrary user input this still seems like needing to handle the case of non-digital user input when calling `int`, for example. Appreciate the report though and the kind words!
