### ISSUE TITLE
oneOf will not validate unique(?) attributes/schemas

### ISSUE THREAD

**Issue by nicklasb** [Julian/jsonschema#265]
Hi,
I have this strange issue, this is a part of my schema, basically "statement" can have either of these properties, and they all have different names. Still, oneOf fails, and anyOf succeeds.
This should not be possible as the subscemas all have unique attribute names, so matching with two schemas should be impossible, and it is obviously match at least one as I am not getting any errors from anyOf:

File to be validated:
 
```json
{
  "statement": {
    "VerbCreateTable": {
      ....some.data........
    }
}
```

And this is the relevant part of the schema: 

```json
{
    "statement": {
      "oneOf": [
        {
          "properties": {
            "VerbCreateTable": {
              "$ref": "#/definitions/VerbCreateTable"
            }
          }
        },
        {
          "properties": {
            "VerbCreateIndex": {
              "$ref": "#/definitions/VerbCreateIndex"
            }
          }
        },
        {
          "properties": {
            "VerbSelect": {
              "$ref": "#/definitions/VerbSelect"
            }
          }
        },
        {
          "properties": {
            "VerbCustom": {
              "$ref": "#/definitions/VerbCustom"
            }
          }
        },
        {
          "properties": {
            "VerbInsert": {
              "$ref": "#/definitions/VerbInsert"
            }
          }
        }
      ],
      "type": "object"
    },
```

Error:
```
E           Failed validating 'oneOf' in schema['properties']['statement']:
E               {'oneOf': [{'properties': {'VerbCreateTable': {'$ref': '#/definitions/VerbCreateTable'}}},
E                          {'properties': {'VerbCreateIndex': {'$ref': '#/definitions/VerbCreateIndex'}}},
E                          {'properties': {'VerbSelect': {'$ref': '#/definitions/VerbSelect'}}},
E                          {'properties': {'VerbCustom': {'$ref': '#/definitions/VerbCustom'}}},
E                          {'properties': {'VerbInsert': {'$ref': '#/definitions/VerbInsert'}}}],
E                'type': 'object'}
E           
E           On instance['statement']:
```

**Comment by Julian** [comment]
Hi.

There's not enough information here for diagnosis unfortunately. Please include a full, [self-contained example](http://sscce.org/)

It's also hard to prioritize "maybe this is a bug" tickets. If you have specific behavior you've identified it is easier to address.

Thanks.

**Comment by nicklasb** [comment]
HI,
I saw that I had missed the actual question, which is, is this by design or have I misunderstood something about oneOf or the implementation of it in jsonschema? I can look for the bug myself, that is not a problem.

**Comment by Julian** [comment]
I can't even tell what the "it" is unfortunately :/.

`oneOf` succeeds when exactly one of the given schemas is valid. If that doesn't match the behavior you're seeing, it's a bug.

**Comment by nicklasb** [comment]
"It" was the implementation of oneOf in json schema. Doesn't matter. 
Ok, I was just thinking that there could be some other aspect to likeness.

**Comment by nicklasb** [comment]
Thanks!
