### ISSUE TITLE
Strict check for the schema.

### ISSUE THREAD

**Issue by neimad1985** [Julian/jsonschema#268]
Hi,

First thanks for the tool, so useful !
I read the docs and didn't find a way (or missed it) to make jsonschema act strict.
I mean if you write in a schema "typ" : "object" instead of "type" : "object", you won't get any error. So the validation succeeds, but it is a false true.
This forces me to create a json schema for the json schema....
Could it be possible that field names be checked : "type", "additionalProperties", etc.. and an error be raised if an unknown field name is encoutered, like "typ".

Thanks in advance.

Best regards

**Comment by Julian** [comment]
Hey, thanks!

You can create a validator class that doesn't allow unknown validators by adding `additionalProperties : False` to its meta-schema. E.g.:

```
stricter_metaschema = dict(jsonschema.Draft4Validator.META_SCHEMA, additionalProperties=False)
StrictDraft4Validator = jsonschema.validators.create(stricter_metaschema, jsonschema.Draft4Validator.VALIDATORS, "StrictDraft4")
StrictDraft4Validator.check_schema({"typ" : 123})
```

Let me know if this helps.

**Comment by neimad1985** [comment]
Well, that totally did the trick, which is awesome !
I can now delete my schema's schema (which was redundant with your jsonschema.Draft4Validator.META_SCHEMA I guess)...
So sorry for your time, I did not understand this part of the documentation.
Now that you gave me the solution, it is crystal clear.

Thanks again.

**Comment by Julian** [comment]
:) no problem glad you got it to work.

**Comment by neimad1985** [comment]
Last question. It is the first time I open an issue on github. Do I have something to do to close it (as you solved my problem) ?

**Comment by Julian** [comment]
Either of us can close it, I did already :) so you're good.

**Comment by jason-curtis** [comment]
Beautiful, thank you. I didn't know about `"unevaluatedProperties"` and your example works perfectly.

btw, I wanted to do a one-time drop at https://github.com/sponsors/Julian but it won't let me do less than $500, so my org will be doing a smaller monthly donation for a few months.

**Comment by Julian** [comment]
> Beautiful, thank you. I didn't know about "unevaluatedProperties" and your example works perfectly.

My pleasure!

> btw, I wanted to do a one-time drop at https://github.com/sponsors/Julian but it won't let me do less than $500, so my org will be doing a smaller monthly donation for a few months.

Very very appreciated! Thank you! (And your org!) If you need me to tweak anything to make that donation easier please let me know (here or by email or whatever) -- otherwise I see the new sponsor! Thank you again, it really helps!

**Comment by brynpickering** [comment]
@Julian your example works for top-level keys but doesn't seem to catch issues further into the schema, e.g. :

```json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "properties": {
        "my_property": {
            "type": "object",
            "requrtypoed": [],
        }
    }
}
``` 
Any ideas on how to solve this? I've had a look at the meta schema but it isn't clear where to inject a recursive `"unevaluatedProperties": False`.

**Comment by gazpachoking** [comment]
I believe to make sure recursion works properly for the strict metaschema, you have to re-declare the dynamicAnchor
```python
from jsonschema import Draft202012Validator
strict = {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://json-schema.org/draft/2020-12/strict",
    "$dynamicAnchor": "meta",
    "$ref": "https://json-schema.org/draft/2020-12/schema",
    "unevaluatedProperties": False
}
strict_validator = Draft202012Validator(strict)
assert strict_validator.is_valid({
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "properties": {
        "my_property": {
            "type": "object",
            "required": [],
        }
    }
})
assert not strict_validator.is_valid({
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "properties": {
        "my_property": {
            "type": "object",
            "requrtypoed": [],
        }
    }
})
assert not strict_validator.is_valid({
    "typ": "object",
})
```
