### ISSUE TITLE
uri validation doesn’t support unicode

### ISSUE THREAD

**Issue by acadilhac** [Julian/jsonschema#269]
Is there a way to validate uri with unicode inside? 
When running the following code, we get an unexpected ValidationError.

```python
from jsonschema import validate, FormatChecker

schema = {
    "type": "object",
    "properties": {
        "url": {"type": "string", "format": "uri"}
    }
}

url = "http://www.example.com/maïs"

obj = {"url": url}

print validate(obj, schema, format_checker=FormatChecker(formats=["uri"]))
```

**Comment by Julian** [comment]
Hi.

Yes, this is true. URIs cannot contain unicode, they're ASCII.

If you want something else, like IRIs, you can define your [own format](http://python-jsonschema.readthedocs.org/en/latest/validate/#validating-formats).
