### ISSUE TITLE
version.txt/no vcs could be detected on tarball install

### ISSUE THREAD

**Issue by NDevox** [Julian/jsonschema#270]
I'm wondering if this is related to #244.

I'm trying to install the latest version - 2.5.1 on an offline server so have to use a tarball install.

On running `python setup.py install` I get the following:

    vcversioner: no VCS could be detected in u'/usr/lib/python2.7/dist-packages/jsonschema-2.5.1' and u'/usr/lib/python2.7/dist-packages/jsonschema-2.5.1/version.txt' isn't present.
    vcversioner: are you installing from a github tarball?

Any idea why this happens?

**Comment by Julian** [comment]
Can you try with `pip install .` instead?

Also, which tarball are you using? Does it contain a `version.txt`?

**Comment by NDevox** [comment]
Don't have pip isntalled but will get it on so I can do this then will let you know.

I probably got the one linked off pypi (forgot now). it's 2.5.1 and there is no version.txt

**Comment by NDevox** [comment]
Ok, progress, but still errors.

I now have:


    root@elk:/usr/lib/python2.7/dist-packages/jsonschema-2.5.1# pip install .
    Traceback (most recent call last):
      File "/usr/bin/pip", line 9, in <module>
        load_entry_point('pip==1.5.6', 'console_scripts', 'pip')()
      File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 568, in load_entry_point
      File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 2720, in load_entry_point
      File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 2380, in load
      File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 2386, in resolve
      File "/usr/lib/python2.7/dist-packages/pip/__init__.py", line 74, in <module>
        from pip.vcs import git, mercurial, subversion, bazaar  # noqa
      File "/usr/lib/python2.7/dist-packages/pip/vcs/mercurial.py", line 9, in <module>
        from pip.download import path_to_url
      File "/usr/lib/python2.7/dist-packages/pip/download.py", line 25, in <module>
        from requests.compat import IncompleteRead
    ImportError: cannot import name IncompleteRead

**Comment by Julian** [comment]
dist-packages is a pretty strange place to install out of -- did you
download the tarball into there?

The tarball on PyPI also definitely has a version.txt:

```
⊙  curl -s '
https://pypi.python.org/packages/source/j/jsonschema/jsonschema-2.5.1.tar.gz#md5=374e848fdb69a3ce8b7e778b47c30640'
| tar tzf - | grep version.txt
            julian@yoga
jsonschema-2.5.1/version.txt
```

Please double check where you got your tarball from.

**Comment by NDevox** [comment]
Odd. I don't know what happened there then.

dist-packages was a mistake on my part, don't think I read the folders properly when moving everything around.

Using the tarball you linked I installed it no problem.

**Comment by Julian** [comment]
Awesome, glad it worked for you, cheers.

**Comment by NDevox** [comment]
Apaprently for ubuntu (the distro being used) dist-packages is more or less the right place:

http://stackoverflow.com/questions/9387928/whats-the-difference-between-dist-packages-and-site-packages

worth noting I didn't use pip. I used the setup.py instead.

**Comment by Julian** [comment]
That's where packages get *installed* to, but not generally a place you'd
run pip install out of.
