### ISSUE TITLE
Fix Python 2.6 support (or desupport it)

### ISSUE THREAD

**Issue by bhearsum** [Julian/jsonschema#271]
Currently, Python 2.6 is claimed to be supported, but due to the dependency on functools32 (for lru_cache), it is not. functools32 does not support Python 2.6, so jsonschema doesn't either by extension.

**Comment by Julian** [comment]
Py26 support has been dropped already in aa2cd272c880e4f3dd7352775fd1504fc745aa68.

On previous releases, it works perfectly fine and jsonschema did support it. As you can see in that commit, caching was via repoze.lru.

**Comment by bhearsum** [comment]
Ah, mea culpa! Should https://pypi.python.org/pypi/jsonschema/2.5.1 be updated to reflect this as well?

**Comment by Julian** [comment]
No worries! 2.5.1 was the last release to support 2.6 -- have you seen
issues with it?

**Comment by bhearsum** [comment]
I thought I had...but this is probably PEBKAC. I installed jsonschema into a vendor lib with Python 2.7, but then ran the app with Python 2.6, so it probably chose the wrong version. Sorry for the noise!

**Comment by Julian** [comment]
Got it, no worries, glad it worked in the end. Cheers.
