### ISSUE TITLE
$ref to an invalid schema always says the data is valid

### ISSUE THREAD

**Issue by PeterMinin** [Julian/jsonschema#278]
If a file referenced by $ref is a random JSON instead of a schema, validation always passes instead of raising an error. I think the $ref contents should also be verified with check_schema first.

**Comment by Julian** [comment]
When you say "random JSON", do you mean " a JSON object with some keys that aren't necessarily known validators "? Such a thing is a valid schema, and all things validate successfully against it.

**Comment by PeterMinin** [comment]
Yes, I'm sorry, I didn't know that. Allowing a schema to contain arbitrary keys is counter-intuitive to me... I think it would be nice to implement [the "Ban unknown properties" mode proposal](https://github.com/json-schema/json-schema/wiki/ban-unknown-properties-mode-%28v5-proposal%29) and provide an option to use this mode for schema checking. Maybe even by default, if the standard (draft) allows this.

**Comment by Julian** [comment]
No worries -- it's quite a useful feature, it's what allows the spec to be extended with extra validators without sacrificing (the entirety) of portability.

There's code in some old issues for disallowing additionalProperties in schemas if you're looking for the behavior.
