### ISSUE TITLE
The implementation of "pattern" validator does not respect the standard

### ISSUE THREAD

**Issue by i93sme** [Julian/jsonschema#280]
Heya,

according to:

http://json-schema.org/latest/json-schema-validation.html#anchor33

"pattern" validates the value. It means that if the value *matches* the regexp, it is valid.

Your code implements it the other way around. In your code, if the regexp does not match, then the value is valid.

That will break any logic that uses pattern to validate values.

**Comment by i93sme** [comment]
I am amending my findings. You are using search, and thus you don't respect ECMA 262 regexps at all.
Closing this issue, using a string that re.search() will cope with and produce the right results.

**Comment by Julian** [comment]
I'm not sure I followed the original description (well I did, but I'm not sure what made it seem like the logic was inverted, sounds like just that you had a pattern that wasn't matching and thought the code was inverted?) -- but yes, the spec notes that across languages it's hard to have adherence to ECMA 262 regexes and encourages schema authors to pick regexes that are portable across regex engines.

**Comment by i93sme** [comment]
My pattern was ECMA 262 and yes, it didn't matched. From the code itself it looked like the logic was inverted (red herring). I've corrected my pattern to work with re.search() that your code uses and it works.
