### ISSUE TITLE
Validation error to reference the property for the related error

### ISSUE THREAD

**Issue by aronysidoro** [Julian/jsonschema#281]
I wanted to ask, for this example schema:

```json
schema = {
    "type": "object",
    "properties": {
        "welcome_text": {
            "type": "string"
        }
    }
}
```

Is it possible when raising validation errors to reference the *property* for the related error?  For example, if  the property is`welcome_text`, and it submitted as an integer, to raise an error like:

`{'welcome_text': ["Invalid JSON - 1 is not of type 'string'"]}`

The standard error message that I'm seeing is just an array without a property name:

`["Invalid JSON - 1 is not of type 'string'"]`

Thanks
-Aaron

**Comment by Julian** [comment]
Hi.

There are many queryable fields on errors, the [documentation](http://python-jsonschema.readthedocs.org/en/latest/errors/#jsonschema.exceptions.ValidationError.relative_path) has info about them.

In this case, you're asking about one of the path attributes.

-J
