### ISSUE TITLE
Option to suppress sending the entire schema back with errors

### ISSUE THREAD

**Issue by jvinet** [Julian/jsonschema#284]
I'm using Connexion for my REST API spec layer, which in turn relies on jsonschema for validation. It works great.

However, if a required property is missing and jsonschema catches it, it sends back the entire schema as part of the error string. With larger schemas, this is quite costly in terms of transfer time/space, not to mention my poor log files.

Is it feasible to add an option of some kind that can suppress this behaviour?

The code in question appears to be in `exceptions.py`:

        pschema = pprint.pformat(self.schema, width=72)
        pinstance = pprint.pformat(self.instance, width=72)
        return self.message + textwrap.dedent("""

            Failed validating %r in schema%s:
            %s

            On instance%s:
            %s
            """.rstrip()
        ) % (
            self.validator,
            _utils.format_as_index(list(self.relative_schema_path)[:-1]),
            _utils.indent(pschema),
            _utils.format_as_index(self.relative_path),
            _utils.indent(pinstance),
        )

**Comment by Julian** [comment]
Hi! Thanks.

So, that option really exists already :) -- I don't recommend generally sending those exceptions anywhere, they're aimed at developers, not really end users. Specific applications should generally catch them and inspect them to turn them into more relevant messages.

Perhaps it'd be useful to hear a bit more about what you have in mind, I'm not at all familiar with connexion or with how it uses `jsonschema`, but the current "expected" solution here is that whatever is calling `jsonschema.validate` or the equivalent can freely do:

```
try:
    jsonschema.validate(...)
except ValidationError as error:
   do_something_with(error.message)
```

for example, to just pull off the message.

Lemme know what else you have in mind though.

**Comment by Julian** [comment]
Closing, but feel free to reopen / follow up if you have ideas. Thanks!

**Comment by jvinet** [comment]
Ah, yes -- looks like Connexion isn't using the `.message` attribute of the exception but using `str(exception)` instead, giving me the giant response:

    def validate_schema(self, data):
        """
        :type schema: dict
        :rtype: flask.Response | None
        """
        if self.is_null_value_valid and is_null(data):
            return None

        try:
            validate(data, self.schema, format_checker=draft4_format_checker)
        except ValidationError as exception:
            logger.error("%s validation error: %s" % (flask.request.url, exception))
            return problem(400, 'Bad Request', str(exception))

        return None

Right-o, I'll take it up with them.  Thanks!  :)
