### ISSUE TITLE
ImportError: No module named 'jsonschema' While Launching gns3 in Ubuntu 16.04

### ISSUE THREAD

**Issue by tempdist** [Julian/jsonschema#291]
(https://cloud.githubusercontent.com/assets/4009835/16753282/3b8d9458-4806-11e6-88da-73f8f9fe2c43.png)
Above is the link to screenshot of the error. Jsonschema is already installed and updated to recent version. 
please suggest any thing that fixes this 'cause I need gns3 as soon as possible before my training begins at Honeywell by next monday.
thanks

**Comment by tempdist** [comment]
earlier pip3 freeze -l was not listing jsonschema. However, even upon adding it to the list upon running pip freeze -f jsonschema[ver 2.5.1], the error upon launching gns3 is the same--unable to find jsonschema to import.

**Comment by Julian** [comment]
Please do not use the issue tracker as general Python support. There are many other channels where such support is offered.

**Comment by tempdist** [comment]
I apologise if I used the wrong portal. I am e-mailing to inform that the issue was due to __pycache___ folder not being deleted and because some custom routers were set up[configurations] from pip3 install that caused that import jsonschema issue that were being picked up in the new install of GNS3 using apt-get.

Now the issue is gone and I am being able to use GNS3. Thank you fore responding.


Abhineet Sharma
+91-9810619816


________________________________
