### ISSUE TITLE
How do you pull in the Acceptance Tests?

### ISSUE THREAD

**Issue by Relequestual** [Julian/jsonschema#292]
Hey Julian,

Wondering where you pull in the wonderful acceptance tests you wrote for checking complaiance?
A lot of libraries I've seen have the acceptance test repo as an external repo. Does the json test content get loaded in dynmaically, or is it placed somewhere in the repo I missed, by hand?

(I'm looking at the posibility of wrapping this module in a perl module to actually get a working perl module!)
Cheers
Ben

**Comment by Julian** [comment]
Hey!

The test suite is git subtree'd into this repo in the `json` directory.

Is that what you're after?

**Comment by Relequestual** [comment]
Interesting. Thanks.
Other repos I've seen on github, subtrees show up with a specific folder icon and are linked to the repo.

**Comment by Julian** [comment]
Those are submodules, not subtrees (and they're really bad)
