### ISSUE TITLE
Support for properties named "type" or "id"

### ISSUE THREAD

**Issue by danielsitnik** [Julian/jsonschema#293]
I'm trying to validate some JSON files that have properties named as "type" and "id", which are kind of "reserved words" in the JSON Schema specification.

Sample JSON:
`{
  "id": 100,
  "type": "chart",
  "likes": {
    "count": 0
  },
  "comments": {
    "count": 0
  }
}`

The error message:
```
Failed validating 'type' in schema['properties']['id']:
    {'format': 'uri', 'type': 'string'}

On instance['id']:
    100
```

The property "id" is part of the specification and is expected to be a URL, but in my JSON it is a simple integer (100), hence the error.

If I type a URL into the "id" property just to let the validation proceed, it will then fail in the "type" property with this message:
```
Failed validating 'anyOf' in schema['properties']['type']:
    {'anyOf': [{'$ref': '#/definitions/simpleTypes'},
               {'items': {'$ref': '#/definitions/simpleTypes'},
                'minItems': 1,
                'type': 'array',
                'uniqueItems': True}]}

On instance['type']:
    'chart'
```

Again, this happens because "type" is part of the specification and is expected to be one of ["array", "boolean", "integer", "null", "number", "object", "string"], but in my JSON it has the value "chart".

I didn't find any anything in the specification regarding the use of these "reserved words" inside the JSON to be validated. In fact, some online validators such as [jsonschemavalidator.net](http://www.jsonschemavalidator.net/) work just fine and my JSON is correctly validated against the schema.

Could this be a bug?
Is there anything specific I need to do to be able to use properties with these names (some kind of escaping for example)?

Thanks!

For reference, below is the full schema I'm using:
`{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "id": {
      "type": "integer"
    },
    "type": {
      "type": "string"
    },
    "likes": {
      "type": "object",
      "properties": {
        "count": {
          "type": "integer"
        }
      },
      "required": [
        "count"
      ]
    },
    "comments": {
      "type": "object",
      "properties": {
        "count": {
          "type": "integer"
        }
      },
      "required": [
        "count"
      ]
    }
  },
  "required": [
    "id",
    "type",
    "likes",
    "comments"
  ]
}`

**Comment by Julian** [comment]
Hey.

Nothing special is required. Can you provide the exact code you're running and a full traceback?

**Comment by danielsitnik** [comment]
Damn, just realised my mistake.. I was calling `validate` passing the schema first, and then the instance to be validated.

I'm closing the issue.
