### ISSUE TITLE
Loading $refs in yaml causes a JSONDecodeError

### ISSUE THREAD

**Issue by locallycompact** [Julian/jsonschema#295]
Hi, would it be possible to support loading $ref as yaml? I am using jsonschema to validate yaml against a yaml schema but it failed when trying to import a local $ref, as it then tries to decode it as JSON. Or is it possible to override the function the RefResolver uses to decode the file?

**Comment by Julian** [comment]
Really I'd say you should probably have the web server be able to serve up JSON, YAML is a bit out of scope for JSONSchema :) -- but yes, if you wanted to, you could use a custom scheme to RefResolver's [handler argument](http://python-jsonschema.readthedocs.io/en/latest/references/#jsonschema.RefResolver) as a way to tell jsonschema a function to use to do the requesting and loading.
