### ISSUE TITLE
no VCS could be detected 

### ISSUE THREAD

**Issue by AliBaheri** [Julian/jsonschema#305]
Hi,
I am facing with the following error when I try to install jsonchema (to run the jupiter notebook!)

vcversioner: no VCS could be detected in u'/Users/ali/Downloads/Python_Libraries/jsonschema-master' and u'/Users/ali/Downloads/Python_Libraries/jsonschema-master/version.txt' isn't present.
vcversioner: are you installing from a github tarball?

I am a mac user. I have downloade the source from github, and run "python setup.py install"

Can someone please help me to fix this issue?
Thanks

**Comment by Julian** [comment]
Is there a reason you're trying to run master instead of a release?

But yes, if you did want master, you need an honest-to-goodness checkout, not just a tarball of the tip.

**Comment by AliBaheri** [comment]
Thanks, when I am using jsonschema-2.5.1 from the source and repeat python setup.py stall, I am facing:
Permission denied: '/Users/ali/anaconda/lib/python2.7/site-packages/easy-install.pth'
I really have problem to fix the permission error file even after dozens of search.
Can you please give some suggestion?

**Comment by AliBaheri** [comment]
Update: conda install jsonschema solve the issue.
