### ISSUE TITLE
Non-ascii properties validation?

### ISSUE THREAD

**Issue by novel** [Julian/jsonschema#308]
Hi,

I have some difficulties validating properties that use non-ascii chars. I'd better illustrate using an example:

```
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from jsonschema import validate
import jsonschema.exceptions

schema = { 
    'type': 'object',
    'patternProperties': {
        '^[\w _:.-]{1,255}$': {
            'type': 'string', 'maxLength': 255 
        }   
    },  
    "additionalProperties": False,
}


if __name__ == "__main__":
    validate({"foo": "bar"}, schema)
    print "ok"
    try:
        validate({"foo": 123}, schema)
        print "ok"
    except jsonschema.exceptions.ValidationError:
        print "expected fail"
    
    try:
        validate({u"test": u"тест"}, schema)
        print "ok"
    except jsonschema.exceptions.ValidationError:
        print "unexpected fail on non-ascii value"

    try:
        validate({u"собака": u"баскервилей"}, schema)
        print "ok"
    except jsonschema.exceptions.ValidationError:
        print "unexpected fail on non-ascii key"
```

When I run this test script I expect to get only 1 failure (in the second check, where I pass integer instead of string). However, I get:

```
ok
expected fail
ok
unexpected fail on non-ascii key
```

However, with a tiny tweak of jsonschema I can get a result that I expect. The tweak looks like this:

```
--- jsonschema/_utils.py.orig   2016-11-25 09:24:40.461301331 +0300
+++ jsonschema/_utils.py        2016-11-25 09:48:04.233281565 +0300
@@ -97,7 +97,7 @@
     patterns = "|".join(schema.get("patternProperties", {}))
     for property in instance:
         if property not in properties:
-            if patterns and re.search(patterns, property):
+            if patterns and re.search(patterns, property, re.UNICODE):
                 continue
             yield property
 
```

And then the result looks like this:

```
ok
expected fail
ok
ok
```

Info about my env:

```
Description:    Ubuntu 14.04.2 LTS
Python 2.7.6
locale:
LANG=ru_RU.UTF-8
LANGUAGE=
LC_CTYPE="ru_RU.UTF-8"
LC_NUMERIC="ru_RU.UTF-8"
LC_TIME="ru_RU.UTF-8"
LC_COLLATE="ru_RU.UTF-8"
LC_MONETARY="ru_RU.UTF-8"
LC_MESSAGES="ru_RU.UTF-8"
LC_PAPER="ru_RU.UTF-8"
LC_NAME="ru_RU.UTF-8"
LC_ADDRESS="ru_RU.UTF-8"
LC_TELEPHONE="ru_RU.UTF-8"
LC_MEASUREMENT="ru_RU.UTF-8"
LC_IDENTIFICATION="ru_RU.UTF-8"
LC_ALL=ru_RU.UTF-8
jsonschema (2.5.1)
```

Is that a bug or am I doing something wrong?

Thanks

**Comment by Julian** [comment]
So this is actually a bit tricky. I can elaborate a bit when I get a second, but basically, patternProperties are recommended to be ECMAScript regexes -- now, we don't do that, we use Python regexes (and the JSON Schema spec acknowledges that not all languages have easy access to an ECMAScript-compatible regex engine), but the behavior you were expecting is even further from ECMAScript regexes I think, so it'd make your schema even less portable.

**Comment by novel** [comment]
Thanks for reply, Julian. Though it's still not clear what's the best way to have non-ascii char as object keys?

If this helps, here's a little more context: my goal is not add support for non-ascii keys for OpenStack's Nova metadata (that's basically an arbitrary key/value pairs one can assign to servers).

https://github.com/openstack/nova/blob/master/nova/api/validation/parameter_types.py#L310

I've changed the regexp to use \w instead of 'a-z' stuff, but for obvious reason it didn't help, that's why I'm here :)

**Comment by Julian** [comment]
@novel so I think the answer involves "what's the ECMAScript regex compatible syntax for non-ascii word characters" which is what I think needs verifying (if such a thing exists).

If it doesn't, an intermediate solution probably would let you inject flags for regex validation, but that's kind of hairy.

I still haven't been able to dedicate time to this but if you have any ideas I'd love to discuss further, otherwise I should be able to give it at least a bit of time.

**Comment by novel** [comment]
Unfortunately, I'm a practicing (Java|ECMA)Script developer, so I don't know best practices for this case. I was able to google up something though. Specifically, there does not seem to be a way to flip `\w` into supporting all Unicode ranges.

Quoting https://mathiasbynens.be/notes/es6-unicode-regex, "Impact on character class escapes" section:

> Their inverse counterparts \d, \s, and \w are not affected by the u flag. There was a proposal to make \d and \w (and \b) more Unicode-aware, but it was rejected.

Mozilla docs (https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/RegExp#Regular_expression_and_Unicode_characters) suggests using the following:

```
var text = 'Образец text на русском языке';
var regex = /[\u0400-\u04FF]+/g;

var match = regex.exec(text);
console.log(match[0]);        // logs 'Образец'
console.log(regex.lastIndex); // logs '7'
```

**Comment by Julian** [comment]
Hey! Really sorry it took this long, but I *think* that the best solution here is that if you really want to write a non-portable regex, to use Python's ability to inject in flags within the pattern itself -- i.e., the equivalent of what you've patched in is to just write:

```
schema = { 
    'type': 'object',
    'patternProperties': {
        '(?u)^[\w _:.-]{1,255}$': {
            'type': 'string', 'maxLength': 255 
        }   
    },  
    "additionalProperties": False,
}
```

What you've found also looks reasonable to me though.

Hope one of the two of those works? I think as a general solution that either seems reasonable to me, but happy to discuss further!
