### ISSUE TITLE
strict_rfc3339 and isodate validate timezones differently

### ISSUE THREAD

**Issue by tsaylor** [Julian/jsonschema#311]
Below is the code for validating a date-time formatted field:
```
try:
    import strict_rfc3339
except ImportError:
    try:
        import isodate
    except ImportError:
        pass
    else:
        @_checks_drafts("date-time", raises=(ValueError, isodate.ISO8601Error))
        def is_datetime(instance):
            if not isinstance(instance, str_types):
                return True
            return isodate.parse_datetime(instance)
else:
    @_checks_drafts("date-time")
    def is_datetime(instance):
        if not isinstance(instance, str_types):
            return True
        return strict_rfc3339.validate_rfc3339(instance)
```

Strict_rfc3339 and isodate both accept a string like "2016-11-05T23:59:59+01:00", but strict_rfc3339 rejects the similar string "2016-11-05T23:59:59+0100" while isodate accepts it. Since python's "%z" format refers to tz offset strings formatted as "+0100" it makes more sense to me to use isodate's validation, and I'd like to make a pull request removing strict_rfc3339 in favor of isodate. 

So before I write any code, I have a few questions:
1) Do you agree with my proposal to accept +0100 formatted tz offset strings?
2) What is the reason for supporting both libraries?

**Comment by tsaylor** [comment]
Ah, after more investigation I see that it was changed because the json schema definition only supports rfc3339. Nevermind then.

**Comment by jufemaiz** [comment]
Just discovered this. Damn, we've been using +/-hhmm for timezone offsets everywhere prior to JSON schema 😞
