### ISSUE TITLE
Wrong absolute_path with anyOf nested in allOf

### ISSUE THREAD

**Issue by estan** [Julian/jsonschema#312]
I was working on a schema and noticed that the `absolute_path` in the `ValidationException` was not quite right when working with `anyOf` nested inside `allOf`.

Here's a small test case:

**test.json**
```json
{
    "foo": {
        "baz": "wrong"
    }
}
```

**schema1.json**
```json
{
    "$schema": "http://json-schema.org/draft-04/schema",

    "type": "object",
    "properties": {
        "foo": {
            "allOf": [
                {
                    "type": "object",
                    "properties": {
                        "bar": { "type": "integer" }
                    }
                },
                {
                    "type": "object",
                    "properties": {
                        "baz": { "type": "integer" }
                    }
                }
            ]
        }
    }
}
 ```

**schema2.json**
```json
{
    "$schema": "http://json-schema.org/draft-04/schema",

    "type": "object",
    "properties": {
        "foo": {
            "allOf": [
                {
                    "type": "object",
                    "properties": {
                        "bar": { "type": "integer" }
                    }
                },
                {
                    "anyOf": [
                        {
                            "type": "object",
                            "properties": {
                                "baz": { "type": "integer" }
                            }
                        }
                    ]
                }
            ]
        }
    }
}
```

And finally:

**test.py**
```python
from jsonschema import validate, ValidationError
from json import load

instance = load(open('test.json'))

schema1 = load(open('schema1.json'))
schema2 = load(open('schema2.json'))

for schema in [schema1, schema2]:
    try:
        validate(instance, schema)
    except ValidationError as e:
        print(e.absolute_path)
```

**Output from `python3 test.py`**
```
deque(['foo', 'baz'])
deque(['foo'])
```

**Expected output**
```
deque(['foo', 'baz'])
deque(['foo', 'baz'])
```

In both cases, the offending element in the instance is the same, so I would expect the `absolute_path` to be the same.

Would be great to have this fixed, as I'm using an `allOf { anyOf { ... } }` construct at quite a high level in my schema, and the `absolute_path` really helps when presenting an error to the user. As it is, the path is collapsed like this, making the error message not very helpful :/

**Comment by estan** [comment]
I found this problem with the 2.5.1 Ubuntu package, but I've tested with Git `master` and it's still there.

**Comment by estan** [comment]
Sorry, I should have read the error handling docs more carefully. I realize now that this is actually expected behavior, since the default heuristic considers `anyOf` and `oneOf` *weak* validation errors. If I instead use the `jsonschema.exceptions.best_match` on `iter_errors()`, it'll give me what I want. Very nice with all this flexibility!

Closing this now. Sorry for the noise.

**Comment by Julian** [comment]
Glad you figured it out thanks for following up.
