### ISSUE TITLE
Can YAML be used for schema while using CLI

### ISSUE THREAD

**Issue by amanjeev** [Julian/jsonschema#315]
Within my own app, I can always load YAML schema instead of JSON using PyYAML etc. but I was wondering if there is a way to use the this via command line as well? It seems like the entire package is pretty much expecting JSON for schema. Like `load_schema()` looks for JSON only : https://github.com/amanjeev/jsonschema/blob/master/jsonschema/_utils.py#L51

Any suggestions to how I may approach this. I am willing to work on this if you want and open a PR but I was wondering if I could get some input from you regarding whether it is already done and also regarding portions of the code (packaging, testing, cli etc.) that I may be missing. thanks!

**Comment by Julian** [comment]
The right way to do this is to just compose some external tool which
converts YAML to JSON. There are many of em, pick whichever one. Then just
`jsonschema validate -i <(yaml-to-json instance.yaml) <(yaml-to-json
schema.yaml)

**Comment by amanjeev** [comment]
I see. Thank you!
