### ISSUE TITLE
Error message on patternProperties could be more informative

### ISSUE THREAD

**Issue by itamarst** [Julian/jsonschema#316]
Consider the following schema snippet:

```yaml
     templates:
        type: object
        additionalProperties: false
        patternProperties:
          "^[a-zA-Z][-a-zA-Z0-9]{0,29}$":
            $ref: "#/definitions/docker-component"
```

If there is a key in the `templates` JSON object that doesn't match that regex the error message looks like this (I'm formatting this with `error.path` + `error.message`):

```
/templates: Additional properties are not allowed ("postgresql-v9'6" was unexpected)
```

This is not very informative to the reader. Here's my proposal for a better error message:

```
/templates: "postgresql-v9'6" does not match any of these regexs: ^[a-zA-Z][-a-zA-Z0-9]{0,29}$.
```

**Comment by Julian** [comment]
Hey! Yeah, makes sense.

I have a slight guess that it might be a bit tricky to propagate that message given the way that `patternProperties` has to interact with `additionalProperties` there, and it ends up being `additionalProperties` that constructs the error message.

You could have it look back and figure out that there's a patternProperties that might have covered that pattern I guess.

But if this doesn't turn out to be too hairy to implement I think it'd definitely be an improvement.

Any chance you have time for a PR? If not feel free to leave open and I'll try to put it on the (long) list.

**Comment by itamarst** [comment]
I'll see what I can do.
