### ISSUE TITLE
Implement merge from v5 draft

### ISSUE THREAD

**Issue by stevenxxiu** [Julian/jsonschema#321]
Hi, is it possible to add the merge keyword from the v5 draft? This makes it possible to extend refs, which is currently difficult to do, if we set `additionalProperties` to `false`:

    {
      "definitions": {
        "obj1": {
          "type": "object",
          "properties": {"p": {"type": "string"}},
          "additionalProperties": false
      },
      "type": "object",
      "merge": {
        "source": {"$ref": "#/definitions/obj1"},
        "with": {
          "properties": {
            "q": {"type": "string"}
          },
        }
      }
    }

This feature is rather popular on [stackoverflow](http://stackoverflow.com/questions/22689900/json-schema-allof-with-additionalproperties), and the javascript equivalent of jsonschema, [ajv has also implemented it as an extension](https://epoberezkin.github.io/ajv/#merge-and-patch-keywords).

**Comment by Julian** [comment]
Hi.

I don't think that $merge has landed yet, even in the upcoming Draft 6.

(I don't particularly intend to implement Draft 5, it was a hasty release, but Draft 6 support will land once the draft does I hope -- certainly patches welcome if you'd like to pitch in, although last I checked the metaschema wasn't even published yet).

For the specific functionality here -- I definitely hear it requested a lot -- jsonschema is strictly an implementation of the specs, but I definitely could encourage the use of an implementation of this if one were to be created (and yeah if it lands in the spec, jsonschema will certainly get it).

**Comment by Julian** [comment]
I'm going to open another ticket specifically tracking implementing Draft 6, but if you've got more here, lemme know.
