### ISSUE TITLE
Properties not found in schema do not cause a validation failure

### ISSUE THREAD

**Issue by rachekalmir** [Julian/jsonschema#322]
From the base example in the README:
```
from jsonschema import validate
from jsonschema.exceptions import ValidationError

schema = {
    "type": "object",
    "properties": {
        "price": {"type": "number"},
        "name": {"type": "string"},
    },
}
try:
    validate({"name": "Eggs", "price": "inv"}, schema)
except ValidationError:
    print("Expected validation failure")

try:
    validate({"name": "Eggs", "prce": 33.33}, schema)
except ValidationError:
    print("Expected validation failure also")
```

The first validation fails as expected, however the second validation doesn't.

**Comment by Julian** [comment]
Additional properties are allowed by default by the specification.

**Comment by rachekalmir** [comment]
Is there a way to specify "additionalProperties": false at a global level or do you have to specify this per object type?

**Comment by Julian** [comment]
Global to what? All subschemas within a schema? Nothing shorter than just
writing it into schemas in JSON.

If you're writing schemas in Python rather than JSON though, go wild,
you've got all of the programming language as you need to shorten things if
you want to add it all over your dicts.

**Comment by rachekalmir** [comment]
Ah, I was hoping you could override the base schema somehow to specify that, but it seems like you can just removed the additionalProperties attribute which would be counter productive since now you wouldn't even be able to turn it off lol.

Thanks for the help anyway, it is much appreciated =).

**Comment by Julian** [comment]
np :)

If you do want to be drastic, you can certainly extend a validator class:

http://python-jsonschema.readthedocs.io/en/latest/creating/

to override the `properties` validator, and make it have no additional properties allowed by default.

Lots of options.
