### ISSUE TITLE
date-time format does not raise a ValidationError

### ISSUE THREAD

**Issue by Pentusha** [Julian/jsonschema#323]
I expect that this should cause a ValidationError or FormatError, but in doesn't.

```python
jsonschema.validate(instance={"dt": "20-04"}, schema={
    "type": "object",
    "properties": {"dt": {"type": "string", "format": "date-time"}},
    "required": ["dt"]
})
```

[Online json schema validator](https://www.google.com) gave me this:
> Found 1 error(s)
> Message:
> String '20-04' does not validate against format 'date-time'.
> Schema path:
> #/properties/dt/format

Python == 3.5.2
jsonschema == 2.6.0

**Comment by Julian** [comment]
See the docs, did you install the required dependency or use the 'format'
setuptools extra?

**Comment by Pentusha** [comment]
Of course I did not read the documentation, sorry.

**Comment by Julian** [comment]
No worries, glad it worked for you.

**Comment by SujoyDutta** [comment]
@Pentusha could you please share what was the solution that got it working for you ? Did you have to update the schema to include anything ?
