### ISSUE TITLE
tox: style test fails with undefined 'unicode' if default python is python3

### ISSUE THREAD

**Issue by ssteinerx** [Julian/jsonschema#325]
The `style` test runs with whichever environment pertains when tox is run.  If that environment is python3, the style test fails with `undefined unicode` error in `exceptions.py`.

Switching the virtualenv under which `tox` is run to python2.7 does not produce the error.

Not sure which is the best way to fix this...

**Comment by Julian** [comment]
It's a false positive, so presumably the fix needs to be something flake8-specific.

**Comment by ssteinerx** [comment]
Maybe migrate to [six](https://pypi.python.org/pypi/six) and eliminate as much of the manual handling of PY3 differences in the actual code?

**Comment by Julian** [comment]
That doesn't really fix the problem it just hides it :), this is really just a bug in flake8. Not one that it can ever hope to fix I guess, but one nonetheless.

I wonder whether flake8 has version-specific noqa comments. Or something else for this...

Would like to brainstorm a bit before deciding on something like that, six doesn't really offer any benefits over what's here so switching to it just to appeal a flawed linter doesn't seem right quite yet.
