### ISSUE TITLE
bug: Validator doesn't support format: email

### ISSUE THREAD

**Issue by kblw** [Julian/jsonschema#326]
Seems, that format email it's just string.
I have schema:
```
{
    "type": "object",
    "properties": {
        "email": {
            "type": "string",
            "format": "email"
        }
    }
}
```
I'm trying to validate data:
```
{"email": "just string"}
```
And validator said that's ok.

**Comment by Julian** [comment]
Have you read the documentation?

http://python-jsonschema.readthedocs.io/en/latest/validate/#validating-formats

You haven't included your code, so I don't know what you're running, but I suspect you haven't passed in a `FormatChecker`. Note also that this is pretty much the only instance where `jsonschema` deviates from the spec (intentionally), in that the email validator basically just does `"@" in email`.

**Comment by kblw** [comment]
Sorry, i don't take put a FormatsChecker.
