### ISSUE TITLE
Use schema specified in the instance using "$schema"

### ISSUE THREAD

**Issue by mikehwang** [Julian/jsonschema#327]
I would like to have JSON instances specify the custom JSON schema by having instances use the `$schema` property.  This is a valid use of JSON schema per [this page on `$schema`](https://spacetelescope.github.io/understanding-json-schema/reference/schema.html).

I've poked around the library and I see this:

```
def validate(instance, schema, cls=None, *args, **kwargs):
```

But what I would like is a convenience version of that:

```
def validate(instance, cls=None, *args, **kwargs):
```

Where this `validate` would grab and use the schema specified in the `$schema` property.  Does this already exist?  Otherwise wouldn't this be a cool feature to add?

Thanks!

**Comment by Julian** [comment]
$schema is a thing that does that for schemas, not instances. Instances are
not presumed to have meaningful keys.

**Comment by mikehwang** [comment]
I understand that schemas are metadata for the data (instances).  What I'm looking for is described in [this SO post](http://stackoverflow.com/questions/26215253/json-schema-in-json/26220786#26220786).

A given JSON can be made self-describing if it had a `$schema` property or an equivalent.

**Comment by Julian** [comment]
Yeah, it makes sense :), although in that answer is also "Although other tools wouldn't pick up on this automatically, it would be obvious to any other developers what you were doing."

Basically, `jsonschema` could never make assumptions about whether parts of your instance do or don't mean things, even about JSON Schema.

Is the convenience version really that much more convenient than just passing in e.g. `requests.get(instance["$schema"]).json()`?

**Comment by mikehwang** [comment]
> Basically, jsonschema could never make assumptions about whether parts of your instance do or don't mean things, even about JSON Schema.

Yes I think I see that supporting self-describing JSONs is outside the scope of this library and JSON schema.  What's missing is a standardization of the self-describing bit.

> Is the convenience version really that much more convenient than just passing in e.g. requests.get(instance["$schema"]).json()?

I wasn't just looking for convenience rather a suitable, permanent home for this ;)

**Comment by Julian** [comment]
Gonna close this for now, but if you have any further thoughts lemme know certainly.
