### ISSUE TITLE
"required" field in nested dict

### ISSUE THREAD

**Issue by viehwegerlib** [Julian/jsonschema#331]
I have a JSON schema like so:

```
{
    "properties": {
        "_id": {
            "type": "string"
        },
        "animal": {
            "type": "string"
        },
        "c": {
            "properties": {
                "danger": {
                    "type": "boolean"
                },
                "very": {
                    "type": "boolean"
                }
            },
            "required": [
                "danger"
            ],
            "type": "object"
        },
        "zoo": {
            "type": "string"
        }
    },
    "required": [
        "_id",
        "animal"
    ],
    "type": "object"
}
```

Validation only works at the top level:

```
from jsonschema import validate
rec = {'_id': '1', 'zoo': 'le', 'animal': 'lion'}
validate(rec, schema)  # success
```

However, I would expect the validation to fail, because I have no field ['c']['danger']. Am I doing something wrong or does jsonschema not validate nested "required" fields?

Thx a lot!

**Comment by Julian** [comment]
'c' itself isn't required. That schema just makes 'danger' required when it's present. If you mean for 'c' to be required too, you need to require it as well.

**Comment by viehwegerlib** [comment]
Wow, that was instantaneous :) I did not know this of JSON schema (the spec) and jsonschema (the library) errs out when I specify "c" but not "danger", thanks!
