### ISSUE TITLE
Validating URI templates?

### ISSUE THREAD

**Issue by JulienPalard** [Julian/jsonschema#332]
Hi,

Is there any way to validate for [URI templates](https://tools.ietf.org/html/rfc6570)? Looks like the "format": "uri" fails when given a template.

**Comment by handrews** [comment]
@JulienPalard The latest draft of the specification (which was published a few weeks ago so is not yet broadly implemented) now includes a "uri-template" format for exactly this reason:

https://tools.ietf.org/html/draft-wright-json-schema-validation-01#section-8.3.8

**Comment by JulienPalard** [comment]
I love when I'm in sync with specs þ

Does any work to implement it has started?

**Comment by Julian** [comment]
@JulienPalard I was waiting for a release, so should be implemented shortly -- patches welcome as well of course.

**Comment by Julian** [comment]
Handling this alongside the rest of draft-06 in #337 -- keep an eye out.
