### ISSUE TITLE
FormatChecker not working on 'email'

### ISSUE THREAD

**Issue by pll** [Julian/jsonschema#336]
I'm sure I'm likely doing something wrong.

This code works fine:

```
jsonschema.validate("pll@foo.com",
                    { "format" : "email"},
                    format_checker=jsonschema.FormatChecker())
```

But when I define a schema like this:
```
{
   "type" : "object",
    "tags" : {
	"email" : {
	    "type" : "string",
	    "format" : "email"
       }
    }
}
```
and load it in from a file and use it to validate a file like this:
```
{
    "tags" : {
	"email": "noreply",
    }
}
```

using this code:
```
 jsonschema.validate(config,
                                    schema,
                                    format_checker=jsonschema.FormatChecker())
```

It passes. Despite the `tags["email"]` value not being a valid email format.

What am I doing wrong?

Thanks!

**Comment by Julian** [comment]
You forgot "properties": "tags".

**Comment by mxmader** [comment]
@pll have a look at [jsonschema._format](https://github.com/Julian/jsonschema/blob/master/jsonschema/_format.py) which simply looks for the presence of the `@` character in the string when validating the `email` format. If you want something fancier like validation against the RFC822 address specification, I suggest you use a custom format with one or more regular expressions or submit a PR to enhance the built-in functionality of `jsonschema._format`. Acknowledging that, this issue could close.

**Comment by pll** [comment]
Thanks!
