### ISSUE TITLE
Expose failed property name in required_draft4?

### ISSUE THREAD

**Issue by pobiega** [Julian/jsonschema#344]
https://github.com/Julian/jsonschema/blob/master/jsonschema/_validators.py#L314

It would be very useful to expose the property that failed, other than in the message. Adding a ValidationError.property property that defaults to None and filling it before yielding works and is what I'm currently doing locally.

**Comment by Julian** [comment]
Hi!

See #119, which is still waiting for a patch :)

**Comment by pampas93** [comment]
You could add the "required" field into your schema; and once you validate; you know which properties are missing. 
Worked for me.
