### ISSUE TITLE
it can support type datetime?

### ISSUE THREAD

**Issue by admin-zou** [Julian/jsonschema#347]
I want to use jsonschema check type datetime. 

`from jsonschema.validators import Draft4Validator

myjson = {"dateTime": "2017-07-25 17:38:10", "result": {"returnCode": 0, "errMsg": ""}}

validator = Draft4Validator(schema= {   
                "type":"object",
                "properties":{
                    "dateTime": {"type":"datetime"}, 
                    "result":{
                        "type":"object",
                        "properties":{
                            "returnCode":{"type":"integer"},
                            "errMsg":{"type":"string"},
                        },
                        "required":"returnCode",
                    },
                },
                "reqiured":["dateTime","result"]
        })

validator.validate(myjson)`

but it say "datetime" is unkown

**Comment by Julian** [comment]
datetime is a format, not a type. Please read the format documentation, and if possible use the making list for questions, the issue tracker is for bugs and development.
