### ISSUE TITLE
Python 3.6 support

### ISSUE THREAD

**Issue by impredicative** [Julian/jsonschema#349]
I would like to request documented Python 3.6 support. This is of course defined in `setup.py`, and is reflected under Categories at https://pypi.python.org/pypi/jsonschema/

**Comment by Julian** [comment]
Hey, thanks!

Fine with me as long as we actually support 3.6 (at very least by making sure travis runs tests under it) -- care to send a PR?

**Comment by Julian** [comment]
Closed via #353
