### ISSUE TITLE
jsonschema is support json-ld schema or not?

### ISSUE THREAD

**Issue by linzhi** [Julian/jsonschema#351]
I want to use jsonschema to validate json-ld data...

**Comment by handrews** [comment]
@linzhi here is a discussion of this topic over at the JSON Schema standards project: https://github.com/json-schema-org/json-schema-spec/issues/309

You can definitely use JSON Schema and JSON-LD together, the main question is whether there is some way in which it would help for these things to be aware of each other.

**Comment by Julian** [comment]
Think I'm going to close this out for now, looks like that's the right place to discuss, but if any action items come out of it I'm happy to address.

@linzhi lemme know if you disagree

@handrews thanks as usual :)
