### ISSUE TITLE
format content while validating

### ISSUE THREAD

**Issue by revesansparole** [Julian/jsonschema#359]
Is there a way to force jsonschema to actually parse and change the content of a json while validating it?

for example:
```
from jsonschema import validate
schema = {
    "type": "string",
    "format": "date-time"
}
data = "1937-01-01T12:00:27.87+00:20"
data_fmt = validate(data, schema)
```

with data_fmt containing a datetime object instead of a string.

Thanks

**Comment by Julian** [comment]
The current spec only deals with validation, not coersion.

https://github.com/Julian/Seep was / is an exploratory place for doing some coersion, which you might want to have a look at.

Happy to accept PRs / improvements there certainly as well, if you find something you'd like to add.
