### ISSUE TITLE
ValidationError.cause unset for date-time format errors

### ISSUE THREAD

**Issue by bsmithers** [Julian/jsonschema#368]
I noticed that the exceptions generated by an invalid datetime only set the cause parameter of the ValidationError when isodate is used - and not when strict_rfc3339 is in use.

As per [1], no exceptions are raised by strict_rfc3339.validate_rfc3339. I wonder if it would make sense for jsonschema to raise strict_rfc3339.InvalidRFC3339Error rather than return False in that handler? 

Otherwise, some other method of identifying what caused the exception would be useful, especially since FormatErrors are caught and reraised as a ValidationError - as it stands I think you cannot determine that it was a format failure that occurred? I'm not sure if this applies to any of the other built-in format checkers.

I could submit a pull request with the former solution if you are happy with that?

[1] https://github.com/Julian/jsonschema/blob/d0381d51c1ba361e675bdf36adb6ea9d62caa06b/jsonschema/_format.py#L219-L223

**Comment by Julian** [comment]
Hey! Thanks for filing this.

Hmmmm... I think you should still have the `validator` property telling you it's failing validating format, no?

The purpose of `cause` was mostly to support cases where the format validation process provides even more detail about *why* the value doesn't satisfy the format -- so you still might be onto something here, does the `InvalidRFC3339Error` raised by whatever other API contain any other useful details about validation?

If so might still be worth attaching it.

**Comment by bsmithers** [comment]
Thanks for the reply. I didn't realise that was the intention of `cause`. If `cause` is not the appropriate mechanism, it does feel like it would be useful if there were some other way to know that a format error has occurred, as opposed to a structural or type error in the JSON document. Perhaps there is something else in the exception that gives this away?

> does the InvalidRFC3339Error raised by whatever other API contain any other useful details about validation?

Unfortunately not. It's simply the error raised if `validate_rfc3339` returns False when trying to convert to e.g. convert it to unix timestamp.

> Hmmmm... I think you should still have the validator property telling you it's failing validating format, no?

For what benefit though? The return of a given handler isn't propagated anywhere is it? As a user, either my document validates or an error is generated.

**Comment by Julian** [comment]
It's propagated on attributes on the exception object. someerror.validator
specifically.

Have a look at the error docs, or I can follow up with some more info in a
bit.

**Comment by bsmithers** [comment]
Ah, I got it now - that makes sense. Sorry, I had misinterpreted your first response. 

Thanks very much for taking the time to respond. 

Given the purpose of `cause`, it seems this is rather a non-issue in the end :)

**Comment by Julian** [comment]
No worries, glad you got it working!
