### ISSUE TITLE
SchemaError being raised on a valid draft-4 schema

### ISSUE THREAD

**Issue by vvasuki** [Julian/jsonschema#369]
Relevant portion of the trace, along with the schema: https://pastebin.com/P69gqQLS

https://jsonschemalint.com/#/version/draft-04/markup/json confirms that the schema seen above is valid - https://i.imgur.com/0NCbT9p.png . 

Confirmed on latest version by installing with: `sudo pip3 install git+https://github.com/Julian/jsonschema@master -U`

**Comment by Julian** [comment]
Hi! Thanks for the report.

What's making you think that website is any more trustworthy than `jsonschema` :)?

If possible, can you track down (via e.g. the `context` attribute or by using `jsonschema.exceptions.best_match`) what specifically is the claim is wrong with your schema, and we can then confirm whether that's actually a bug here or correct and a bug there?

**Comment by vvasuki** [comment]
Sorry about the false alarm - the jsonschema website is fine as well, but it seems that I was somehow checking the wrong schema (that one that shows up last in the log linked above -  Turns out I was setting the type field (['properties']['publication_details']['properties']['publisher']['type']) to be this schema json.). All's well now.
