### ISSUE TITLE
None is not covered under 'string' type

### ISSUE THREAD

**Issue by bhushan5** [Julian/jsonschema#372]
As per the documentation(http://json-schema.org/latest/json-schema-validation.html#rfc.section.6.25), 'string' type covers one of the six ("null", "boolean", "object", "array", "number", or "string"). But, it does not cover "None" which is equivalent to "null". Can that be fixed, because we get failures like ::
`None is not of type 'string'`

**Comment by bsmithers** [comment]
I think you might have misunderstood the documentation - it's saying the _value_ of the type must be a _string_, which is either "null", "boolean", "object", "array", "number", "string", "integer" (note that integer is slightly different from the other as it's not a actually a different JSON type, simply a number with no fraction). 

It's not saying that a string type also matches, e.g. "null"/None. 

Maybe you can give an example of what you're trying to do to better point you in the right direction?

**Comment by bhushan5** [comment]
Oh I see. Is there an option of `or` I can use. So, in my case, one of the attribute can either be a `string` or `None`. So, if I put 'type': 'string', it fails when the attribute's value is `None`. Hence, I want to validate if the attribute's value is one of the two types.

**Comment by bsmithers** [comment]
Yes, you can use a list of types, e.g. 

`"type": ["string", "none"]`

For more complex use cases, you can use `anyOf` rather than `type`.

**Comment by bhushan5** [comment]
That helped ! Thanks ! I shall close this issue.
