### ISSUE TITLE
Nested requirements does not work with array

### ISSUE THREAD

**Issue by mmeyer39** [Julian/jsonschema#375]
Nested requirements on object properties does not work.
The validation is done on the first level requirements but not on the sublevels one
`{
	"$schema": "http://json-schema.org/draft-06/schema#",
	"definitions": {
		"address": {
			"type": "object",
			"properties": {
				"street_address": {
					"type": "string"
				},
				"city": {
					"type": "string"
				},
				"state": {
					"type": "string"
				}
			},
			"required": [
				"street_address",
				"city",
				"state"
			]
		}
	},
	"type": "object",
	"properties": {
		"addresses": {
			"type": "array",
			"item": {
				"$ref": "#/definitions/address"
			}
		},
		"name": {
			"type": "string"
		}
	},
	"required": [
		"addresses",
		"name"
	]
}`

and the test associated and validated (second address of the array is incorrect)
`{
  "name": "test",
  "addresses": [
    {
      "street_address": "1600 Pennsylvania Avenue NW",
      "city": "Washington",
      "state": "DC"
    },
    {
      "street_address": "1st Street SE",
      "city": "Washington"
    }
  ]
}`

**Comment by Julian** [comment]
Hi.

Please include a reproducible snippet with whatever you're running.

It also looks like you're using a draft 6 schema, when there's no released draft 6 support.

**Comment by mmeyer39** [comment]
It validates as well when removing the draft6 line...

**Comment by Julian** [comment]
You have `"item": {"$ref": "#/definitions/address"}` instead of `"items"`.

**Comment by mmeyer39** [comment]
Okay, 
This is my mistake, 
Thanks for the help and sorry to bother you.
I was surprise that it did not raise any error and couldn't find the problem as it was validating everything
