### ISSUE TITLE
[help] replace invalid values with default values?

### ISSUE THREAD

**Issue by pavitrakumar78** [Julian/jsonschema#379]
Hi,

Is it possible to replace the invalid values in a json file with the default specified in the schema?
Ex:
Schema (excerpt):
```
"foo": {
                "id": "/properties/a/b/c/d/e/foo",
                "type": "integer",
                "title": "The foo Schema.",
                "default": 0,
		"minimum": 0,
		"maximum": 40
              }
```

JSON (excerpt):
```
 "foo": -34,
```

so, is it possible to replace -34 by 0? or with the default minimum value using the `path` and `absolute_schema_path` from the validation error?

I understand this is more than just "validation"  so I am not sure whether what I am asking is correct or if it is even the right way to approach this problem.

**Comment by Julian** [comment]
Hi. Please use the mailing list for questions, the issue tracker is for actual issues.

This isn't a thing `jsonschema` does, but there was some experimentation on this in the `Seep` repo. I believe there's some further info in the FAQ as well if you're looking for some code.

Please follow up on the mailing list or IRC channel (or in some previous related issues) if neither of those manages to get you where you want to go, happy to provide further pointers.
