### ISSUE TITLE
Fuzzy matching on field names

### ISSUE THREAD

**Issue by mitar** [Julian/jsonschema#381]
I would like to use JSON schema to validate human-created JSON documents. While some parts of my schema are strict, some parts of it is lax (`additionalProperties` set to `true`). This makes it tricky to really validate documents because people could make a simple mistake, like writing `colour` instead of `color` found in the schema. Validation would not catch this because additional properties are allowed, but it is still a bug from the user's perspective.

So it would be great if there could be a way to hook in or have this built-in, that for properties and other values which are not covered by the schema, there could be a custom check, which would then check if something similar does exist in the schema and maybe warn about it.

**Comment by Julian** [comment]
How would you define "similar"? If you've got a suitably scientific definition, this is certainly possible, though I'm not sure it's related to JSON Schema, unless you're looking to declare that property in a schema. If you're not, just run it on your dicts after you get them.

**Comment by mitar** [comment]
There are some [libraries for this](https://github.com/seatgeek/fuzzywuzzy). For example, git also proposes alternative commands if you make a mistake.

> I'm not sure it's related to JSON Schema

It is related to JSON Schema validation, but it is not part of the standard. But it is something which would be useful for end-users in my opinion.

> unless you're looking to declare that property in a schema

No, there would be no extra information about this in the schema. Schema lists correct property names, but if somebody passes a dict with a similar property name, then validation could show a warning: both because this can be confusing (two fields with very similar names) or because it is a typo.

> If you're not, just run it on your dicts after you get them.

I cannot really do this outside of JSON Schema validation (without doing JSON Schema validation myself) because at each location in my data instance, I would have to know which properties are part of the schema and which are not. This is already being done by this validator, so I would have to duplicate work if I would go over dicts myself.

**Comment by bsmithers** [comment]
IMHO this would be best handled outside of the jsonschema library. For your use case, you could define a custom validation function for 'properties' by extending an existing validator[1]. Your function could first do your fuzzy check before calling the standard validation function (e.g. [2]) for properties to handle the rest of the process (concretely, look for keys in `instance` that are 'close' but-not-exact matches to keys in `properties` with a method of your choosing) . 

[1] https://python-jsonschema.readthedocs.io/en/latest/creating/#jsonschema.validators.extend
[2] https://github.com/Julian/jsonschema/blob/master/jsonschema/_validators.py#L294

**Comment by Julian** [comment]
There are mechanisms for [extending validators](http://python-jsonschema.readthedocs.io/en/latest/creating/#jsonschema.validators.extend) to add additional behavior to them -- I presume in your case that you'd mean to extend the properties validator to run some fuzzywuzzy thing?

(I'm not sure what you mean to do in cases where your schema doesn't define which properties are allowed, presumably you want to skip that level? jsonschema does not already look at those parts of your instance)

**Comment by Julian** [comment]
Closing, but lemme know if what it looks like both me and @bsmithers said makes sense :), think you should have the tools you need here already to do this pretty easily.
