### ISSUE TITLE
Add support for optional strict validation of types

### ISSUE THREAD

**Issue by adi69** [Julian/jsonschema#391]
One should have the freedom to check for types inside strings.
For instance, given the following schema
```
    {
        "schema": {
            "id": "schema_id",
            "properties": {
                "age": {
                    "type": "integer",
                    "description": "",
                }
            }
        }
    }
```
above schema should validate true for following data when strict validation is False
```
{ "age": "23" }
```

Why? It'll be helpful in API validation of query in GET requests and headers.

**Comment by Julian** [comment]
This sounds like the opposite of "strict" :)

It's possible already though to do now that we've got [fully extendable type checkers](http://python-jsonschema.readthedocs.io/en/latest/validate/#type-checking). Haven't tidied up enough to do a release just yet, but if you give HEAD a try you'd be able to do this.

Feedback welcome.
