### ISSUE TITLE
Validate specification built-in formats

### ISSUE THREAD

**Issue by cpersico** [Julian/jsonschema#393]
Hi, I'm trying to validate an RFC3339 date by using the default format "date-time".
(see: https://spacetelescope.github.io/understanding-json-schema/reference/string.html)

Right now the library only validates the type (string) are there any plans to support this in the future?

**Comment by Julian** [comment]
Hi -- sorry, I can't parse your description, it seems like possibly there's a word or two missing?

Are there plans to support what in the future? RFC3339 dates *are* strings.

**Comment by Julian** [comment]
Closing this, but if you clarify feel free to follow up.
