### ISSUE TITLE
draft-07 support

### ISSUE THREAD

**Issue by gaoxinyang** [Julian/jsonschema#400]
In our current project we are using JSON draft-07 schema, is there any plan to introduce the support to draft-07 ? Thanks.

**Comment by handrews** [comment]
See #337 as it will be a much smaller follow-on to draft-06 support.  To summarize the discussion there, draft-07 requires all of draft-06 so releasing draft-06 as soon as it is ready doesn't really slow down progress to draft-07.

**Comment by wolfthefallen** [comment]
Would love the ability to do version 7!

**Comment by mgab** [comment]
Is it possible to follow progress or/and pending tasks for any of the two versions anywhere? I'm thinking of a wiki page with TODOs, a label or milestone for pending issues or anything like that.

This would allow people to know not only how far or close new versions are, but also where hands are needed.

**Comment by Julian** [comment]
There's a [checklist](https://github.com/Julian/jsonschema/issues/337#issuecomment-305981069) on the draft 6 ticket. On this one, there's a branch (`draft7`) with support for draft7 on it, and probably will have a checklist as soon as draft6 is fully done.

**Comment by iddan** [comment]
Is there a checklist?

**Comment by Julian** [comment]
Hi! Beyond the one from the Draft6 ticket, essentially for Draft7 all that's left specifically for Draft7 is adding support for `if/then/else`, which should be fairly straightforward.

The branch that's out there passes everything else besides those.

**Comment by Julian** [comment]
The draft 7 specific pieces here are done and merged, so I'm going to close this one at least -- the next stable release will have full draft 7 support other than a format or two that doesn't have an existing implementation.
