### ISSUE TITLE
Regex

### ISSUE THREAD

**Issue by josephbiko** [Julian/jsonschema#406]

**Comment by Julian** [comment]
Hi. Please always include full code + traceback, or if there's no error, full code + a description of what happens, and what you expect to happen instead.

Note here also that if you mean literally the string `"\d+"`, that's not a valid regex.

**Comment by josephbiko** [comment]
Julian, ty for the quick response, but it seems like i created the issue myself somewhere, sorry:)

**Comment by Julian** [comment]
No worries, glad you figured it out!
