### ISSUE TITLE
additionalProperties should store off the unexpected extra properties

### ISSUE THREAD

**Issue by ogenodisho** [Julian/jsonschema#409]
I am trying to obtain all keys that caused validation errors using the ErrorTree object but I can't seem to do it. (Please see my stackoverflow question for more detail: https://stackoverflow.com/questions/50401837/getting-invalid-key-values-from-jsonschema-using-python)

Here is the code I am using:

```
def get_errors_in_tree(error_tree):
    errors = []
    if error_tree.total_errors <= 1:
        return map(lambda ve: list(ve.instance.keys()),  error_tree.errors.values())
    for error in error_tree:
        errors.extend(get_errors_in_tree(error_tree[error]))
    return errors
```

But this isn't working - it's only giving me some of the keys. Could I please get more guidance on how to achieve this?

**Comment by Julian** [comment]
Hi.

This is discussed tangentially in #119, it's basically the other known case where this information isn't present.

Have a look there, though I can leave this open as one specifically about `additionalProperties`.

Patches welcome of course.
