### ISSUE TITLE
error path is missing when using iter_errors

### ISSUE THREAD

**Issue by wichert** [Julian/jsonschema#411]
I have a very basic schema:

```
    schema = {
           '$schema': 'http://json-schema.org/draft-04/schema',
           'type': 'object',
           'properties': {
               'email': {
                   'type': 'string',
                   'format': 'email',
               },
               'password': {
                    'type': 'string',
                    'minLength': 1,
               },
           },
           'additionalProperties': False,
           'required': ['email', 'password'],
    }
```

When I validate an empty map against that I can see two errors:

```python
>>> validator = validator_for(schema)
>>> errors = list(validator(schema).iter_errors(data))
>>> errors
[<ValidationError: "'email' is a required property">,
 <ValidationError: "'password' is a required property">]
```

Creating an error tree fails shows some odd behaviour:

```python
>>> et = jsonschema.ErrorTree(validator(schema).iter_errors(data))
>>> et
<ErrorTree (1 total errors)>
>>>  'email' in et
False
```

Trying to figure out why this happened revealed that the error path is empty:

```python
>>> [e.path for e in errors]
[deque([]), deque([])]
```

**Comment by Julian** [comment]
This is expected, though maybe underdocumented.

path means "where in the instance the error occured", and should always be a sequence of indexes that can be performed against the instance.

`required` is validated at the level of the object that should contain the properties (here your root object), so the path is empty.

Try your example with any other validator, or any nested object.

**Comment by wichert** [comment]
Hm, that is problematic for me. My use case here is doing validation on data past to a REST service, and I would like to report all errors back to the client, which I can't do now due to the missing path. As far as I can see there is no other way to see which property triggered the error. This is the `__dict__` if the error:

```
{'cause': None,
 'context': [],
 'instance': {},
 'message': "'email' is a required property",
 'parent': None,
 'path': deque([]),
 'relative_path': deque([]),
 'relative_schema_path': deque(['required']),
 'schema': {'additionalProperties': False,
            'properties': {'email': {'format': 'email', 'type': 'string'},
                           'password': {'minLength': 1, 'type': 'string'}},
            'required': ['email', 'password'],
            'type': 'object'},
 'schema_path': deque(['required']),
 'validator': 'required',
 'validator_value': ['email', 'password']}
```

Can you consider adding some way to see which property triggered the error?

**Comment by Julian** [comment]
You're already seeing every error.

If you mean you want to know specifically for `required` which properties are missing, that's #119, patches certainly welcome.

**Comment by handrews** [comment]
@wichert you might be interested in the discussion in https://github.com/json-schema-org/json-schema-spec/issues/396, about standardizing or at least recommending output/error formats.  Note that that's on the spec repo, not this implementation specifically.  It's also just getting off the ground despite having been filed a while back.

**Comment by Julian** [comment]
> when using jsonschema.validate() instead of lazy validation the error exception does have the missing property in path

What code are you running and what path are you looking at?

The behavior here should match between `iter_errors` and `validate` (and the latter actually just uses the former).

**Comment by Julian** [comment]
Going to close this given the above (but if you do have a case where this has different behavior definitely lemme know!) and given @handrews's pointer, which I'll have to have a look at myself.
