### ISSUE TITLE
Not able to Use json-schema-form to form data in table

### ISSUE THREAD

**Issue by amithmahakala423** [Julian/jsonschema#412]
I am using angular2-json-schema-form, to form html page. Some of the data i want to represent in the table using the attribute "format": "table". I am getting the following error: "unknown format "table" ignored in schema".

Do i need to install any table module using npm ?

"YextCategoryList": {
                "type": "array",
                "format": "table",
                "addable" : false,
                "removable":false,
                "orderable": false, 
                "title": "<b>Yext Category List</b>",                 
                "items": {
                    "type": "object",
                    "properties": {
                        "yextCategoryId": {
                            "title": "Yext Category Id",
                            "type": "string",
                            "readonly": true,
                            "default": "",
                            "examples": [ "123456" ]
                        },
                        "addedBy": {
                            "title": "Added By",
                            "type": "string",
                            "readonly": true,
                            "default": "",
                            "examples": [ "koushk01" ]
                        },
                        "addedDate": {
                            "title": "Added Date",
                            "readonly": true,
                            "default": "",
                            "examples": [ "2017-12-20T16:44:04.000Z" ]
                        },
                        "updatedBy": {
                            "title": "Updated By",
                            "type": "string",
                            "readonly": true,
                            "default": "",
                            "examples": [ "koushk01" ]
                        },
                        "updatedDate": {
                            "title": "Updated Date",
                            "tyre": "string",
                            "readonly": true,
                            "default": "",
                            "examples": [ "2017-12-20T16:44:04.000Z" ]
                        }
                    }
                }
            }

**Comment by Julian** [comment]
Hi. Pretty sure you've got the wrong repo here.

**Comment by amithmahakala423** [comment]
Can help us know the right repo, as we are using this schema for json to html. As mentioned above using angular2-json-schema-form.

**Comment by handrews** [comment]
This repo is for a Python implementation and has nothing to do with HTML or angular.

**Comment by handrews** [comment]
http://json-schema.org/implementations.html
