### ISSUE TITLE
i want to show which field is error

### ISSUE THREAD

**Issue by TesterQiao** [Julian/jsonschema#414]
For example ：  "status_code"  422 is not one of [42211] 
How should I do it？
Use ValidationError？
thanks

**Comment by Julian** [comment]
Hi. Please leave the bug tracker for bugs, and use other resources (the JSON Schema IRC channel, or Slack channel, or the mailing lists, or StackOverflow) for usage questions.

In your case though yes, I'd recommend starting by reading the docs on [`ValidationError`](http://python-jsonschema.readthedocs.io/en/latest/errors/#jsonschema.exceptions.ValidationError)
