### ISSUE TITLE
Consider subtree-ing in the spec repo

### ISSUE THREAD

**Issue by Julian** [Julian/jsonschema#418]
Would help to preserve context on e.g. #415

**Comment by Julian** [comment]
Looks like json-schema-org/json-schema-spec is doing one-branch-per-draft or so, so not very easy to do this unfortunately. Oh well, not a huge loss anyhow.

**Comment by handrews** [comment]
@Julian the web site sub-trees the spec repo.  What are you trying to do with it?  My difficulties with keeping them in sync have to do more with the limitations of `git submodule` :-/

**Comment by Julian** [comment]
Uhhhh so basically the idea here was that if I subtreed in the spec repo, I'd be able to `git subtree pull` in all the changes to metaschemas (same as for the test suite repo). And could preserve (or not preserve at my whim) the commits / messages that changed them.

But since each draft is on its own branch, I'd actually need N subtrees, one for each metaschema, which is inconvenient sounding enough to not be worth it :D

**Comment by handrews** [comment]
Hmm... are subtrees transitive?  If you subtree'd the web site repo would you get its subtrees for managing the specs?

The spec repo is branched, the web site repo is not- it has each branch subtree'd separately already, which is how we manage the meta-schemas on the site.

**Comment by Julian** [comment]
A ha -- interesting.

Yeah subtrees are basically totally transparent, it's as if all the files and directories are copied over.

So that'd work if I subtree'd the website repo.
