### ISSUE TITLE
validation against database models

### ISSUE THREAD

**Issue by graingert** [Julian/jsonschema#424]
I'd like to be able to define a set of formats that validate Django model `pk`s

I would define some checkers and validate parsed JSON against the schema. I'd like to be able to batch up similar formats into one query and convert those formats into the actual Django model instances.

```python
from django.contrib.auth import User

format_re = re.compile('db:(?P<model_name>[\w_]+\.\w+)')
checker = FormatChecker()

@checker.formater(formats=format_re, batched=True)
def django_formatter(instances: Dict[FormatStr, Set[str]]):
    def process_items(format, items):
        model_name = format_re.match(format).groups('model_name')
        Model = apps.get_model(model_name)
        mapping = {m.pk: m for m in Model.objects.filter(pk_in=items)}
        return {item: mapping[m] for item in items if item in mapping}

    return {k: process_items(k, v) for k, v in instances.items()}

user_schema = {
  "type": "string",
  "format": "db:auth.User",
}

def test_format_converter():
    content = '3'

    result = jsonschema.validate(content, user_schema, format_checker=checker)
    assert isinstance(result, User)
    assert result.pk = 3


def test_multiple(django_assert_num_queries):
    schema = {
      "type": "array",
      "items": user_schema,
    }
    content = ['1', '2', '3']

    with django_assert_num_queries(1):
        result = jsonschema.validate(content, schema, format_checker=checker)

    for u in result:
        assert isinstance(u, User)
    assert [u.pk for u in result] = [1, 2, 3]
```

**Comment by Julian** [comment]
Hm -- is there a big advantage to this over just using a `for` loop?

Or is the key here that you want to dynamically define formats, and you don't know what they are in advance?

**Comment by graingert** [comment]
The reason being, I want to check them all in one go

**Comment by graingert** [comment]
@Julian here's a proposal for more than just formats: https://github.com/Julian/jsonschema/issues/458

**Comment by Julian** [comment]
I think I left a comment on the other issue that this is definitely something interesting but something I'd want to put in a library on top of this one. Closing for now but definitely appreciate the idea.
