### ISSUE TITLE
[Feature Request] list of all properties (resolving references)

### ISSUE THREAD

**Issue by lzkelley** [Julian/jsonschema#437]
I'm working with a "complex" set of schema that each use references from numerous other files.  It would be super useful if there was an easy way to get a list of all of the references, combining the relevant references in the schema.  Perhaps a `schema` class that could give general derived properties would be helpful, i.e. so that you could do things like,

```
schema = jsonschema.load_schema(schema_filename)
print(schema.properties)
print(schema.required)
```

**Comment by Julian** [comment]
Hi, thanks!

Not sure I fully follow your example -- from the text it sounds like you're asking for something like #419 or [jsonref](https://github.com/gazpachoking/jsonref), but from your code it sounds like you're talking about being able to access dict keys as attributes.

Which of those two (if either) is this about?

**Comment by lzkelley** [comment]
@Julian Sorry, that was a very vague FR, but I think both of those tools are all that would be required to make my request trivial.  I think I'm actually missing how they are different.  I was imagining something that would not only dereference/combine-references but also resolve conditional logic (if needed).  Thinking that through a bit more, I guess that would actually be non-trivial to determine different nesting levels (and possible recursions) and how to deal with `anyOf` versus `allOf` etc.  I haven't looked much at the internal machinery in the `jsonschema` package, but it seems like the functionality of `jsonref` must be happening internally, right?  There's no easy access to achieve the same effect as `jsonref.loads`?

**Comment by lzkelley** [comment]
Yeah, you're right of course.  The ability to access a complete list of `properties` (even solely at the top level) could be quite difficult depending on the structure of the schema in question.  The ability to do that easily is prefaced on the structure of the schema, and thus isn't a good, general-purpose method.
