### ISSUE TITLE
cannot run executable with jsonschema

### ISSUE THREAD

**Issue by Sir2B** [Julian/jsonschema#440]
I have made a executable from a python script with includes jsonschema with cx_Freeze 4.3.3.
But if I run the executable, I get the following error:

> ---------------------------
> cx_Freeze: Python error in main script
> ---------------------------
> Traceback (most recent call last):
>   File "C:\Python34\lib\site-packages\cx_Freeze\initscripts\Console.py", line 27, in <module>
>     exec(code, m.__dict__)
>   File "test.py", line 1, in <module>
>   File "c:\python\32-bit\3.4\lib\importlib\_bootstrap.py", line 2214, in _find_and_load
>   File "c:\python\32-bit\3.4\lib\importlib\_bootstrap.py", line 2203, in _find_and_load_unlocked
>   File "c:\python\32-bit\3.4\lib\importlib\_bootstrap.py", line 1191, in _load_unlocked
>   File "c:\python\32-bit\3.4\lib\importlib\_bootstrap.py", line 1161, in _load_backward_compatible
>   File "C:\Python34\lib\site-packages\jsonschema\__init__.py", line 18, in <module>
>     from jsonschema.validators import (
>   File "c:\python\32-bit\3.4\lib\importlib\_bootstrap.py", line 2214, in _find_and_load
>   File "c:\python\32-bit\3.4\lib\importlib\_bootstrap.py", line 2203, in _find_and_load_unlocked
>   File "c:\python\32-bit\3.4\lib\importlib\_bootstrap.py", line 1191, in _load_unlocked
>   File "c:\python\32-bit\3.4\lib\importlib\_bootstrap.py", line 1161, in _load_backward_compatible
>   File "C:\Python34\lib\site-packages\jsonschema\validators.py", line 170, in <module>
>     meta_schema=_utils.load_schema("draft3"),
>   File "C:\Python34\lib\site-packages\jsonschema\_utils.py", line 57, in load_schema
>     data = pkgutil.get_data('jsonschema', "schemas/{0}.json".format(name))
>   File "C:\Python34\lib\pkgutil.py", line 607, in get_data
>     spec = importlib.util.find_spec(package)
>   File "C:\Python34\lib\importlib\util.py", line 100, in find_spec
>     raise ValueError('{}.__spec__ is None'.format(name))
> ValueError: jsonschema.__spec__ is None

setup.py
```
import sys
from cx_Freeze import setup, Executable

setup(name="test",
      version="0.1",
      description="",
      executables=[Executable(script="test.py")]
      )
```
test.py
`import jsonschema`

Which all the others packages I have no problem.

**Comment by Julian** [comment]
Hi @Sir2B sorry you're running into issues here.

cx_Freeze isn't officially supported unfortunately. It's not that I don't think it should work (it does do some "interesting" things when it's running but as you say, most packages tend to work without intervention), but there's no current CI testing that things work under cx_Freeze, and I don't use cx_Freeze personally.

If you're able to send a PR adding support for testing against cx_Freeze (or even better that plus fixing this issue) I'm happy to take a look at it.

Beyond that though, from your error, I would *guess* that that's `importlib` saying something like that `jsonschema` isn't installed in the surrounding environment, though the [stdlib documentation](https://docs.python.org/3.7/library/importlib.html#checking-if-a-module-can-be-imported) is unhelpful on when exactly `importlib.util.find_spec` returns `None`.

**Comment by Sir2B** [comment]
Hi @Julian thanks your info.

Is there another tool that you support that can be used to create executables (on windows)?

**Comment by Julian** [comment]
Nothing that currently runs in CI unfortunately.

Even Windows itself just recently started being run (and isn't even passing yet).
