### ISSUE TITLE
Type coercion?

### ISSUE THREAD

**Issue by braco** [Julian/jsonschema#441]
Hi, is there any type of type coercion possible in this module? I don't see it, but I'm not sure if it's buried in one of the specs and named something different.

https://ajv.js.org/coercion.html

**Comment by Julian** [comment]
Hi!

This repository (and library) attempts to essentially very strictly implement the spec and only the spec (nothing experimental), but to provide enough hooks to implement anything else on top.

In particular, [Seep](https://github.com/Julian/Seep) was an attempt to have some coercion functionality.

Patches definitely welcome there if there are things you would like to have.
