### ISSUE TITLE
required in allOf is NOT checked

### ISSUE THREAD

**Issue by lzq420241** [Julian/jsonschema#444]
1. cd to folder contains the jsonschema_issue.json and jsonschema_issue.py, run with:
```shell
python jsonschema_issue.py
```
2. expect validation fails, but it actually passed.

reference:
1. jsonschema_issue.py
```python
import json

from jsonschema.validators import Draft4Validator
from jsonschema.exceptions import ValidationError

resp = '{"HostId": "example.com"}'

schema_file = 'jsonschema_issue.json'
with open(schema_file, 'r') as loadFile:
    schema = json.load(loadFile)

validator = Draft4Validator(schema)
try:
    validator.validate(json.loads(resp))
except ValidationError as e:
    print(e)
else:
    print("pass")
```
2. jsonschema_issue.json
```json
{
    "allOf": [
        {
        "properties": {
            "RequestId": {"type": "string", "pattern": "abcd"},
            "required": ["RequestId"]
            }
        },
        {
        "properties": {
            "HostId": {"type": "string", "pattern": "example.com"},
            "required": ["HostId"]
            }
        }
    ]
}
```

**Comment by lzq420241** [comment]
if resp in jsonschema_issue.py:
```python
resp = '{"RequestId": "abcd"}'
```
expect failure, but actual pass.

for the follow case:
```python
resp = '{"RequestId": "abc2d", "HostId": "example.com"}'
```
the result is right.

**Comment by Julian** [comment]
Hi @lzq420241, there are still many many things here that look like they're not necessary for the bug report.

Ideally what's here should be exactly 1 line: `validate(someobjectliteral, someinstanceliteral)`.

Does your issue still happen if you remove `"type": "object"` from your schema? If so, please remove it, and any other lines that are not required to reproduce.

Does your issue still happen if you don't use refs? If so please remove and inline them.

**Comment by lzq420241** [comment]
update to possible least code.

**Comment by Julian** [comment]
And the rest of the things I mentioned? Are you saying you've tested removing them and they then don't allow you to reproduce?

**Comment by lzq420241** [comment]
I have remove all the unrelated fields, the issue still exists.

**Comment by Julian** [comment]
@lzq420241 that isn't at all the case. Please read the article I linked very very carefully.

Here is what you should have provided, by iteratively deleting pieces of your code and schema, until you likely end up with something like:

```
from jsonschema.validators import Draft4Validator
Draft4Validator(
    {
        "allOf": [
            {
                "properties": {
                    "RequestId": {},
                    "required": ["RequestId"]
                }
            }
        ]
    },
).validate(
    {}
)
```

All I did were start combining your files and deleting lines, making sure the behavior was the same, until it was obvious what the issue was -- that you put `required` inside your `properties`, instead of alongside it.

Please do read that SSCCE article, it's what you should do when reporting an issue on any repository.

**Comment by lzq420241** [comment]
@Julian, sorry for waste your time, and thanks for your help.
I should be more careful and do as SSCCE told.
