### ISSUE TITLE
Removing failing fields from JSON?

### ISSUE THREAD

**Issue by dhimmel** [Julian/jsonschema#448]
[We're interested](https://github.com/greenelab/manubot/issues/47) in using a JSON schema to produce valid CSL JSON Items (citation styles language). Our CSL inputs contain many fields that are not part of the schema. In addition, some fields have values that violate the schema. Therefore we would like to perform the following two steps:

1. Removing fields not part of the specification (when `additionalProperties` is `false`). Cross-referencing [SO44694835](https://stackoverflow.com/questions/44694835/remove-properties-from-json-object-not-present-in-schema).

2. Removing fields whose values violate the schema. Here we would want to remove the lowest-level errors, such that we don't remove entire objects because of a single deeply nested error contained within them.

Is this doable with `jsonschema` or should we look to an alternative solution? Any suggestions will be appreciated.

**Comment by dhimmel** [comment]
One solution that comes to mind is to collect all errors using `validator.iter_errors`. Then we may be go through each error and delete the affected field. However, I'm having trouble extracting the keys that failed due to `additionalProperties`. For example, the following error message provides the names of the additional keys:

```
Additional properties are not allowed ('arxiv_id', 'arxiv_id2' were unexpected)
```

Are those keys ('arxiv_id', 'arxiv_id2') accessible in a structured way without parsing the error message?

**Comment by dhimmel** [comment]
This is what I've come up with so far:

```python
import re
import copy

def delete_elem(instance, path):
    *head, tail = path
    for key in head:
        instance = instance[key]
    del instance[tail]

def remove_error(instance, error):
    if error.validator == 'additionalProperties':
        pattern = re.compile(r"'(.+?)'")
        for key in pattern.findall(error.message):
            delete_elem(instance, path=list(error.path) + [key])
    elif error.validator in {'enum', 'type'}:
        delete_elem(instance, error.path)
    else:
        raise NotImplemented(f'{error.validator} is not yet supported')

def remove_errors(instance, errors):
    """
    Remove fields that produced JSON Schema errors. UNTESTED
    """
    instance = copy.deepcopy(instance)
    errors = sorted(errors, key=lambda e: e.path, reverse=True)
    for error in errors:
        remove_error(instance, error)
    return instance
```

Would appreciate any advice whether I'm on the right track.

**Comment by Julian** [comment]
`jsonschema` itself does no mutation on any instance, but you might want to have a look at [the code in this FAQ](http://python-jsonschema.readthedocs.io/en/latest/faq/#why-doesn-t-my-schema-s-default-property-set-the-default-on-my-instance) and modify it for your use case -- specifically rather than overriding `default`, you can override `additionalProperties`.

It's quite icky to do that though, you're taking a thing that means one thing and overriding it to mean something quite different. If I were you I'd consider inventing your own keyword entirely (and adding an additional validator for it).

**Comment by Julian** [comment]
(Closing this one too for cleanliness, but if you have any additional comments lemme know!)

**Comment by dhimmel** [comment]
Thanks @Julian for the advice. I had looked at the code in the FAQ, but with my limited understanding of the internals of this package, it was a bit difficult. However, of course, I still think it would be a great builtin feature for your package should it be in scope sometime in the future.

For others interested in this feature, we ended up implementing something in https://github.com/greenelab/manubot/pull/49. See the [relevant code here](https://github.com/greenelab/manubot/blob/66a6efc6f4b84153a813aa423ec00725ed1417c5/manubot/cite/citeproc.py#L62-L146) and the relevant [test suite here](https://github.com/greenelab/manubot/blob/66a6efc6f4b84153a813aa423ec00725ed1417c5/tests/csl-json/test_csl_pruning.py), where we note:

> The fidelity of the remove_jsonschema_errors implementation is difficult to assess theoretically, therefore its performance should be evaluated empirically with thorough test coverage.

**Comment by rmedaer** [comment]
Hi @dhimmel 
A few days ago I publish [a solution which removes the properties not in the schema](https://stackoverflow.com/a/60907034/2437450).

See the following example:

```python
from jsonschema import Draft7Validator, validators

def extend_validator(validator_class):
    validate_properties = validator_class.VALIDATORS["properties"]

    def remove_additional_properties(validator, properties, instance, schema):
        for prop in list(instance.keys()):
            if prop not in properties:
                del instance[prop]

        for error in validate_properties(
            validator, properties, instance, schema,
        ):
            yield error

    return validators.extend(
        validator_class, {"properties" : remove_additional_properties},
    )

DefaultValidatingDraft7Validator = extend_validator(Draft7Validator)

# Example usage:
obj = {
    'foo': 'bar',
    'not_in_schema': 'no no no'
}
schema = {
    'properties': {
        'foo': {
            'type': 'string'
        }
    }
}

DefaultValidatingDraft7Validator(schema).validate(obj)
assert obj == {'foo': 'bar'}
``` 

It doesn't check if `additionalProperties` is `false` but it would not be hard to add.

Could you confirm it fixes you first point.

**Comment by aj07mm** [comment]
this doesn't work with polymorphic schemas
