### ISSUE TITLE
Is vcversioner no longer dependency of jsonschema?

### ISSUE THREAD

**Issue by idgserpro** [Julian/jsonschema#453]
I am having trouble installing ```jsonschema```2.6.0  in environments without accessing pypi because of vcversioner. But I see that it is no longer dependency.

**Comment by Julian** [comment]
It isn't, but setuptools_scm is now, which works the same exact way.

**Comment by idgserpro** [comment]
I'm basically having the same problem as #276, but using the ```buildout``` to install ```jsonschema```.

We have a server without internet access and we install the packages from an internal mirror. We configure the ```buildout``` index to get packages from this mirror. The ```buildout``` uses this configuration to get packages that are in ```install_requires```, but it doesn't work for packages that are in ```setup_requires```.

So ```easy_install``` tries to download ```vcversioner``` from pypi but, as the server doesn't access the internet, an error occurs:

```bash
Getting required 'jsonschema==2.6.0'
We have no distributions for jsonschema that satisfies 'jsonschema==2.6.0'.
Getting distribution for 'jsonschema==2.6.0'.
Running easy_install:
/opt/programas/zope/2.13.26/des_10466_ttransparente/bin/python "-c" "from setuptools.command.easy_install import main;main()" "-mUNxd" "/opt/programas/zope/2.13.26/des_10466_ttransparente/zeoclient/eggs/tmpOpVeBa" "-q" "/tmp/tmpYl0V09get_dist/jsonschema-2.6.0.tar.gz"
path=/opt/programas/zope/2.13.26/des_10466_ttransparente/zeoclient/eggs/setuptools-26.1.1-py2.7.egg

Download error on https://pypi.python.org/simple/vcversioner/: [Errno 111] Connection refused -- Some packages may not be found!
Couldn't find index page for 'vcversioner' (maybe misspelled?)
Download error on https://pypi.python.org/simple/: [Errno 111] Connection refused -- Some packages may not be found!
No local packages or working download links found for vcversioner>=2.16.0.0
error: Could not find suitable distribution for Requirement.parse('vcversioner>=2.16.0.0')
An error occurred when trying to install jsonschema 2.6.0. Look above this message for any errors that were output by easy_install.
While:
  Installing instance.
  Getting distribution for 'jsonschema==2.6.0'.
Error: Couldn't install: jsonschema 2.6.0
```

Is possible fix this by using a ```~/.pydistutils.cfg``` file with the content:

```cfg
[easy_install]
index_url = http://my.mirror/root/pypi
```

This tells to ```easy_install``` to get packages from my mirror and not from pypi.

Probably, we will have the same problem with ```setuptools_scm```. But this isn't a problem of ```jsonschema```. It is only for registration.

Thanks.

**Comment by idgserpro** [comment]
I'm basically having the same problem as #276, but using the ```buildout``` to install ```jsonschema```.

We have a server without internet access and we install the packages from an internal mirror. We configure the ```buildout``` index to get packages from this mirror. The ```buildout``` uses this configuration to get packages that are in ```install_requires```, but it doesn't work for packages that are in ```setup_requires```.

So ```easy_install``` tries to download ```vcversioner``` from pypi but, as the server doesn't access the internet, an error occurs:

```bash
Getting required 'jsonschema==2.6.0'
We have no distributions for jsonschema that satisfies 'jsonschema==2.6.0'.
Getting distribution for 'jsonschema==2.6.0'.
Running easy_install:
/opt/programas/zope/2.13.26/zinstance/bin/python "-c" "from setuptools.command.easy_install import main;main()" "-mUNxd" "/opt/programas/zope/2.13.26/zinstance/zeoclient/eggs/tmpOpVeBa" "-q" "/tmp/tmpYl0V09get_dist/jsonschema-2.6.0.tar.gz"
path=/opt/programas/zope/2.13.26/zinstance/zeoclient/eggs/setuptools-26.1.1-py2.7.egg

Download error on https://pypi.python.org/simple/vcversioner/: [Errno 111] Connection refused -- Some packages may not be found!
Couldn't find index page for 'vcversioner' (maybe misspelled?)
Download error on https://pypi.python.org/simple/: [Errno 111] Connection refused -- Some packages may not be found!
No local packages or working download links found for vcversioner>=2.16.0.0
error: Could not find suitable distribution for Requirement.parse('vcversioner>=2.16.0.0')
An error occurred when trying to install jsonschema 2.6.0. Look above this message for any errors that were output by easy_install.
While:
  Installing instance.
  Getting distribution for 'jsonschema==2.6.0'.
Error: Couldn't install: jsonschema 2.6.0
```

Is possible fix this by using a ```~/.pydistutils.cfg``` file with the content:

```cfg
[easy_install]
index_url = http://my.mirror/root/pypi
```

This tells to ```easy_install``` to get packages from my mirror and not from pypi.

Probably, we will have the same problem with ```setuptools_scm```. But this isn't a problem of ```jsonschema```, so we're commenting here just for the sake of documentation.

Thanks.
