### ISSUE TITLE
Is it possible to add ability to convert raw dict to reduced dict using schema?

### ISSUE THREAD

**Issue by asheraScout** [Julian/jsonschema#455]
jsonschema already have a function `validate` to validate a raw dict with a schema.

To explain what I mean, for example, there is a dict:
```
raw_dict = {
  "latitude": 48.858093,
  "longitude": 2.294694,
  "extra_key": "value1"
}
```
and a schema:
```
schema = {
  "id": "https://example.com/geographical-location.schema.json",
  "$schema": "http://json-schema.org/draft-06/schema#",
  "title": "Longitude and Latitude Values",
  "description": "A geographical coordinate.",
  "required": [ "latitude", "longitude" ],
  "type": "object",
  "properties": {
    "latitude": {
      "type": "number",
      "minimum": -90,
      "maximum": 90
    },
    "longitude": {
      "type": "number",
      "minimum": -180,
      "maximum": 180
    }
  }
}
```

Now I want a function which like:
```
def reduce(instance, schema):
    ...
    return new_instance

>>> reduce(raw_dict, schema)
>>> raw_dict = {
      "latitude": 48.858093,
      "longitude": 2.294694
    }
```
the `reduce` function validate the raw_dict and pass it ,then convert it to the result which fit the schema, if the dict is not passed, it behaves like `validate`, raise an error.

If this function is allowed to add into jsonschema, I can take some time to write it.

**Comment by Julian** [comment]
Hi, thanks!

This repository is guided more to being an exact implementation of the
spec. https://github.com/Julian/Seep was more for this sort of thing. Happy
to review a PR there.

Seems like this would be a fairly easy function to implement, though it'd
likely depend on #409. Sounds useful potentially though.
