### ISSUE TITLE
No module named attr

### ISSUE THREAD

**Issue by NieXiaoyi** [Julian/jsonschema#457]
python 2.7.6
error: File "/jsonschema/exceptions.py", line 6,  no module named attr.
how to fix this?

**Comment by Julian** [comment]
Hi. What version of `jsonschema`, and where did you get it from?

`attrs` is a dependency of jsonschema, but one properly declared in its `install_requires`.

(Also please don't elide tracebacks if you were to share one.)

**Comment by NieXiaoyi** [comment]
Thanks for your reply, I have fixed this by pip install, 'cause I just used the source code on github without installing before.
But now there is another problem, the code as follow:
```
my_schema = \
{
"type": "object",
    "properties": 
    {
        "productId": 
        {
            "const":  1
        }
    },
"required": [ "productId" ]
}

if __name__=='__main__':
    product = \
    {
        "productId":    2,
    }
    validate(product, my_schema)
```
there is no exception raised when I run the code, is that correct?  'cause I thought the instance can validate successfully only when its value is equal to the vaule of the keyowrd "const"

**Comment by Julian** [comment]
Draft 6 is added only in the alpha (which you'd install with `--pre`) or directly from HEAD.
