### ISSUE TITLE
custom validator/process functions for definitions

### ISSUE THREAD

**Issue by graingert** [Julian/jsonschema#458]
```python
import jsonschema

class AddressValidationError extends jsonschema.ValidationError:
    pass

def process_address(address):
    if valid_physical_address(address):
        return Address(address)
    raise ValidationError(address)

schema = {
  "definitions": {
    "address": {
      jsonschema.process: validate_address,
      "type": "object",
      "properties": {
        "street_address": {
          "type": "string"
        },
        "city": {
          "type": "string"
        },
        "state": {
          "type": "string"
        }
      },
      "required": [
        "street_address",
        "city",
        "state"
      ]
    },
    "node": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        },
        "children": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/node"
          }
        }
      }
    }
  },
  "type": "object",
  "properties": {
    "billing_address": {
      "title": "Billing address",
      "$ref": "#/definitions/address"
    },
    "shipping_address": {
      "title": "Shipping address",
      "$ref": "#/definitions/address"
    },
    "tree": {
      "title": "Recursive references",
      "$ref": "#/definitions/node"
    }
  }
}
```

**Comment by graingert** [comment]
with the above schema, I'll be able to define a custom validator function and get data binding to custom classes

**Comment by graingert** [comment]
my actual usecase is taking a django ModelForm, using the fields to generate jsonschema and using the form clean methods etc to generate instances.

**Comment by graingert** [comment]
it avoids being incompatible with future jsonschema properties by using a Symbol object, that can be skipped in JSON serialization:

```
# jsonschema/__init__.py

class Symbol(object):
    __slots__ = []

process = Symbol()
process_bulk = Symbol()
```

**Comment by graingert** [comment]
other option is a class like:

```python
import jsonschema

class AddressValidationError extends jsonschema.ValidationError:
    pass

def process_address(address):
    if valid_physical_address(address):
        return Address(address)
    raise ValidationError(address)

schema = {
  "definitions": {
    "address": jsonschema.Process(process_address, {
      "type": "object",
      "properties": {
        "street_address": {
          "type": "string"
        },
        "city": {
          "type": "string"
        },
        "state": {
          "type": "string"
        }
      },
      "required": [
        "street_address",
        "city",
        "state"
      ]
    }),
    "node": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        },
        "children": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/node"
          }
        }
      }
    }
  },
  "type": "object",
  "properties": {
    "billing_address": {
      "title": "Billing address",
      "$ref": "#/definitions/address"
    },
    "shipping_address": {
      "title": "Shipping address",
      "$ref": "#/definitions/address"
    },
    "tree": {
      "title": "Recursive references",
      "$ref": "#/definitions/node"
    }
  }
}
```

**Comment by Julian** [comment]
I have to read this a bit more carefully, but at first glance it *seems* like possibly you're talking about the sorts of things that [Seep](https://github.com/Julian/Seep) does / did / was envisioned to do -- namely, more geared towards transforming instances using defined rules rather than strictly validation.

**Comment by graingert** [comment]
Yeah I think that might work

**Comment by schneidersoft** [comment]
I like the first implementation better, where the processor function is given as an attribute of the thing it's supposed to process.

This means the schema can still be traversed manually easily.


I have a use case for this involving hashes. I get some data like:
`{'hash':'deadbeef'}`
and want to get a python object like
`{'hash':bytes.fromhex('deadbeef')}`

a single validate+process schema would be nice
```
{'type':'object',
'properties':{
'hash':{'type':'string', processor:bytes.fromhex}
}
}
```

**Comment by Julian** [comment]
See my comment there and in previous issues -- I think this is in fact still a request for the types of things in Seep, in which case I would definitely be open to pull requests there to add any desired functionality.

If anything is *missing* in this library preventing this type of functionality from being implemented on top, that'd certainly be the kind of thing I'd accept bug reports for and want to add here, but the actual transformation itself is the kind of thing that belongs externally in a second package. This one is intended to strictly be an implementation of the specifications.
