### ISSUE TITLE
3.0.0a2 nested object to array properties do not validate

### ISSUE THREAD

**Issue by Overbryd** [Julian/jsonschema#459]
Hi,

**EDIT: I had a typo. Still investigating. Sorry for the false alarm.**
~I think I found a bug (or I am absolutely blind and don't see the issue I am creating myself here).
When validating an array with a nested object definition, validation passes without errors. Although it should throw an error.~

It stops working at `level3`.

If this is some issue with stack-depth or limited recursion capabilities, I would appreciate an exception at this point, rather than a silent failure that misses a validation.

We are using the validator for medical data, and ... no just kidding. But imagine...

##### Schema

```json
{
  "type": "object",
  "required": [
    "level1"
  ],
  "properties": {
    "level1": {
      "type": "object",
      "required": [
        "level2"
      ],
      "properties": {
        "level2": {
          "type": "object",
          "required": [
            "some_list"
          ],
          "properties": {
            "some_list": {
              "type": "array",
              "minItems": 1,
              "items": {
                "type": "object",
                "required": [
                  "foo"
                ]
              }
            }
          }
        }
      }
    }
  }
}
```

##### JSON

```json
{
  "level1": {
    "level2": {
      "level3": {
        "some_list": []
      }
    }
  }
}
```

**Comment by Overbryd** [comment]
All I need sometime is speaking to a rubber duck. Sorry for the confusion, your library works great.

![rubber_duck_ 8374802487](https://user-images.githubusercontent.com/21111/45313902-79b89e00-b530-11e8-947f-55db9d261926.jpg)

**Comment by Julian** [comment]
Hah, glad you figured it out :)
