### ISSUE TITLE
Validating an instance with an unknown $schema should error

### ISSUE THREAD

**Issue by Julian** [Julian/jsonschema#460]
In `validator_for`, and transitively in `validate`, providing an instance whose `$schema` [isn't one of the known metaschemas](https://github.com/Julian/jsonschema/blob/master/jsonschema/validators.py#L848) should error, not use the latest supported version.

It looks like that was my intention originally, judging by the docstring, but the code and tests use the default in all cases.

This will unfortunately not be changeable immediately, it'll need a deprecation period first, so step one is to do that.

**Comment by Julian** [comment]
> About the deprecation? you mean add warnings when a schema is not found
but use the latest anyway? why not just raise an Exception since v3 is
going to be a major bump

Thanks for asking that, it's a subtle thing that a lot of us developers get
wrong :)

So, the rationale there is that semantic versioning tells you what to do
*when* you need to make a backwards incompatible change. It's a signaling
mechanism. It isn't an excuse to just break things just because you're
changing a number :). People very well might be relying on those things,
and just because you bumped a version doesn't change that you're going to
break their stuff. So everything still needs a deprecation period where
things warn, so that people are given a chance to fix their code
*before* things
break on them all at once. (This was Py3's major mistake, which we've paid
a lot for over the years, so it's a lesson we've now learned the hard way
:P).

Hope that makes sense, but lemme know if that needs some more clarification.

**Comment by opethe1st** [comment]
Sorry deleted my comment after I realized that you actually explained and answered [here](https://github.com/Julian/jsonschema/issues/470#issuecomment-434677576) . I just didnt read it properly. Definitely makes sense, need to warn before removing stuff.
