### ISSUE TITLE
Which parts of this library are threadsafe?

### ISSUE THREAD

**Issue by laian** [Julian/jsonschema#464]
Is this library in general threadsafe?  

Assuming that I preload all schemas for the RefResolver:

Can I share validators across threads?  

If not, can I have 1 validator per thread, but have all validators across threads share the same RefResolver?

**Comment by Julian** [comment]
Hey -- in general no objects are explicitly guaranteed to be threadsafe (and no tests currently deal with threads).

If all you're trying to do is share some large dicts, adding them to a bunch of different `RefResolver` stores doesn't copy them.

**Comment by Julian** [comment]
#223 might also interest you.

**Comment by laian** [comment]
thanks!

**Comment by stkrp** [comment]
Hello.

Sorry to bring up the old closed topic, but is it safe to pass the same object (dict) to different validators (one validator per thread)?

### Example

I doubt this code works, but I hope that's enough for an example.

```python
import threading
from multiprocessing.pool import ThreadPool

from jsonschema import Draft7Validator


heavy_schema = {
    # Includes several `$ref` like "#/definitions/some_struct"
    # ...
}


class ThreadSafeValidator:
    def __init__(self, schema):
        self._schema = schema
        self._tl = threading.local()
    
    def validate(self, value):
        if not hasattr(self._tl, "validator"):
            # Create independent `Draft7Validator` for each thread.
            # Can I use `_schema` without deepcopy?
            self._tl.validator = Draft7Validator(_schema)
        
        self._tl.validator.validate(value)


validator = ThreadSafeValidator(heavy_schema)


def validate_value(value):
    validator.validate(value)


pool = ThreadPool(4)
pool.map(validate_value, range(1000))
pool.close()
pool.join()

```

**Comment by Julian** [comment]
Validators don't modify the schemas they're given so that looks like it
should be fine yeah

**Comment by stkrp** [comment]
Great! Thanks.
