### ISSUE TITLE
'jsonschema._validators' has no attribute 'type_draft4'

### ISSUE THREAD

**Issue by cxf739** [Julian/jsonschema#466]
when I use SwaggerClient , report this problem。
Is there any one  know why?
thank you!

**Comment by Julian** [comment]
Hi -- thanks for the ticket.

When reporting issues, please include your minimal reproducing code and a full (unelided) traceback (on this or any repository).

That's a somewhat suspicious traceback, given that that's a private module, but it's impossible to really know what's happening without the above.

Thanks.

**Comment by Julian** [comment]
Closing this but if you have more to follow up with here happy to help.
