### ISSUE TITLE
No Exception raised?

### ISSUE THREAD

**Issue by spike-spb** [Julian/jsonschema#469]
Hello!

I have a following sample schema:

```json
"schema": {
  "type": "object",
    "properties": {
      "value": {"type": "integer"}
    }
}
```

and

```python
validate({"non_existent_property": "test"}, schema)
```

does not raise an Exception.

Is it ok?
I've thought it should.

**Comment by Julian** [comment]
Hi.

Please do have a look at a JSON Schema tutorial before filing these sorts of issues, this would be covered fairly early.


The default for additionalProperties is to allow them, so yes this is expected.
