### ISSUE TITLE
Feature suggestion - support for conversion of formatted strings

### ISSUE THREAD

**Issue by samfrances** [Julian/jsonschema#475]
It would be useful if `jsonschema` could provide support for retrieving a processed copy of the validated document, with automatic conversion of formatted strings into python data types.

This would have to be a configuration option on the validator/formatter, since not all format strings have an obvious native python data type (e.g. datetimes have an obvious native type, but "ipv4" may not).

So for example, with an appropriately configured validator, you could do something like:

```
doc = {"created_at": "2020-02-01 00:00:00"}
validator.validated(doc)
# --> {"created_at": datetime.datetime(2020, 2, 1, 0, 0)}
```

**Comment by Julian** [comment]
Hi -- this is a somewhat common request, and is what [Seep](https://github.com/Julian/Seep) was an experiment in exploring.

In short, it's not the kind of thing I'd want to put in this library itself, but I certainly want to enable a library on top of this one to do it, and Seep was an attempt/example on how to do so.

Would definitely encourage you to have a look there, patches are certainly welcome.
