### ISSUE TITLE
oneOf array of simple types bug - propose fix

### ISSUE THREAD

**Issue by GrahamJB1** [Julian/jsonschema#476]
basicSchemaDefn = """{
'$schema':'http://json-schema.org/draft-04/schema#',
'title':'Test',
'properties':{
'SimpleArrayOfNumberOrString':{
'$ref':'#/definitions/simparray'
}
},
'required':[
'SimpleArrayOfNumberOrString'
],
'type':'object',
'definitions':{
'simparray':{
'oneOf':[
{
'type':'array',
'items':{
'type':'number'
}
},
{
'type':'array',
'items':{
'type':'string'
}
}
]
}
}
}"""

basicSchema = json.loads(basicSchemaDefn.replace('\'', '"'))
builder = pjs.ObjectBuilder(basicSchema)

ns = builder.build_classes(no_extra_parameters = True)
ns.Test().from_json('{"SimpleArrayOfNumberOrString" : [0, 1]}')

 ---------

Proposed fix in classbuilder.py validate:

elif isinstance(val, list):
if len(val) and hasattr(val[0], "validate"):
  for subval in val:
    subval.validate()
else:
  # handle basic types
  setattr(self, prop, val)

**Comment by Julian** [comment]
Hi.

Not sure you have the right repo here.

If you do, can you update your description to be runnable?

Thanks!

**Comment by GrahamJB1** [comment]
Hi,
Sorry I missed the imports at the top, otherwise it is runnable. Just paste into a python script.
The failure is against your latest release.
Thanks.
Yours,
Graham

**Comment by GrahamJB1** [comment]
That is 3.0.0a3, and the title ' handle basic types above' in the proposed solution is of course a comment mangled by the wiki

**Comment by GrahamJB1** [comment]
I am deeply sorry - you are quite right, I am using 3.0.0a3 in conjunction with python jsonschema object and the bug is in their library. Many thanks for your prompt reply, and thank you for the high quality of your library !

**Comment by Julian** [comment]
No worries, and thank you!
