### ISSUE TITLE
Cleanup and debloat the lib

### ISSUE THREAD

**Issue by KOLANICH** [Julian/jsonschema#480]
This library requires `requests`. Do I really need `requests` in order to validate a local json schema? Are remote refs resolved with `requests` a security hole?

I guess we need a smaller and non-bloated jsonscnema lib.

**Comment by Julian** [comment]
I neither agree with your premise nor your entitled tone -- that's not the right way to file an issue on any project.

Please do feel free to find something else if this library doesn't make you happy.
