### ISSUE TITLE
Please update PyPI package

### ISSUE THREAD

**Issue by Snawoot** [Julian/jsonschema#486]
Current version of this package at PyPI is 2.6.0 and it has broken `const` validator. Please update package, so everyone can use fixed version.

**Comment by Julian** [comment]
Hi.

const is new in Draft 6, which is still in alpha, but already uploaded to PyPI.

**Comment by langmm** [comment]
I know this was closed, but are there plans to update the version on PyPI soon? I am running into minor testing issues where tests differ when dependencies are installed from PyPI vs. conda because jsonschema is at 3.0.0a on conda-forge and 2.6.0 on PyPI.

Thanks!

**Comment by Julian** [comment]
@langmm hi!

#523 is the last remaining blocker for a stable release. There's a branch with a fix for it, but I'm unhappy with the implementation, so haven't merged it hoping a better one would occur to me. Comments of course welcome. As soon as that has a decent fix, it seems like I haven't heard any other feedback about the beta releases (bug reports), so we should be good to go...

I sympathize obviously on the packaging woes too, though that sounds like a conda bug to be honest.
