### ISSUE TITLE
Deprecation warning, affects compatibility with Python 3.8

### ISSUE THREAD

**Issue by jasonrhaas** [Julian/jsonschema#487]
When running tests with `pytest`, I noticed some deprecation warnings popping up.  It appears that starting in Python 3.8 we will start to see some issues.

```
/python3.7/site-packages/jsonschema/compat.py:6:
DeprecationWarning: Using or importing the ABCs from 'collections' instead of 
from 'collections.abc' is deprecated, and in 3.8 it will stop working
    from collections import MutableMapping, Sequence  # noqa
```

**Comment by Julian** [comment]
Hey. Pretty sure someone sent a patch to fix this on HEAD, what version are you on?

**Comment by Julian** [comment]
Of jsonschema I mean.

**Comment by jasonrhaas** [comment]
I'm running:

`jsonschema==2.6.0`

So the fix is in the alpha release?

**Comment by Julian** [comment]
Should be yeah

On Nov 8, 2018 14:15, "Jason Haas" <notifications@github.com> wrote:

I'm running:

jsonschema==2.6.0

So the fix is in the alpha release?

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/Julian/jsonschema/issues/487#issuecomment-437121523>,
or mute the thread

**Comment by Julian** [comment]
Closing, but let me know if that's not the case.

**Comment by kazz-s** [comment]
your problem is that you got 2 import mixed up

```
import operator
import sys


try:
    from collections import MutableMapping, Sequence  # noqa
except ImportError:
    from collections.abc import MutableMapping, Sequence  # noqa
```

you should use `from collections.abc ... ` by default and then on error fall back to `from collections ...`.

While `from collections import MutableMapping` works we will keep getting this warning.

**Comment by lifeeric** [comment]
@Julian when I only import from `from collections.abc` on `compay.py` then the warning disappears:
```bash
from collections.abc import MutableMapping, Sequence  # noqa
```

**Comment by Julian** [comment]
That code isn't present on any recent version of this library.
