### ISSUE TITLE
Expected validator_for usage

### ISSUE THREAD

**Issue by manycoding** [Julian/jsonschema#490]
Hello, I am not sure if I do it correctly, but here's what it looks like:

```
from jsonschema import validators

validator = validators.validator_for(schema)(schema)
validator.check_schema(schema)
```
I want to infer a proper validator from a schema and verify if the schema is valid for the inferred validator.

**Comment by Julian** [comment]
That looks correct, though you don't need an instance, since `check_schema` is a classmethod. I.e. `validator_for(schema).check_schema(schema)`.

Is there an error you're getting, or something specifically unclear about the docs?

**Comment by manycoding** [comment]
No, I just was thinking that's quite funny to pass schema 3 times :) Thank you.
