### ISSUE TITLE
JsonSchema validation oneOf Schema error.

### ISSUE THREAD

**Issue by Sharvin26** [Julian/jsonschema#493]
I am using Validation schema in my code and using oneOf Scheme for this purpose in validate_message(param1,param2).
But I am getting '_oneOf_' error in validation. Can anyone Help me
{} is not valid under any of the given schemas.
Failed validating 'oneOf' in the schema:
 And lot's of lines of error.
Is there any better way available to debug the error properly and get which is the accurate error in the validation.
I have already spent more than 4-5 hours for debugging the error still couldn't find the source of error.
Any help is much-appreciated Thanks

**Comment by Julian** [comment]
Hi, please don't cross-post or use the bug tracker to ask questions, it's meant for reports of issues or features. Support is via the mailing list you'd found, IRC, Slack, or StackOverflow.

That being said, you likely are looking for [`jsonschema.exceptions.best_match`](https://python-jsonschema.readthedocs.io/en/latest/errors/#best-match-and-relevance).
