### ISSUE TITLE
The name of a reference can't be an integer

### ISSUE THREAD

**Issue by sea212** [Julian/jsonschema#508]
I created a swagger 2.0 api (in swaggerhub, which validates it) and exported a python flask server from it. After starting it, many exception bubbled up, containing this snippet:

> python3.7/site-packages/jsonschema/validators.py", line 421, in resolve_fragment
    "Unresolvable JSON pointer: %r" % fragment
swagger_spec_validator.common.SwaggerValidationError: ("Unresolvable JSON pointer: 'definitions/400'", RefResolutionError("Unresolvable JSON pointer: 'definitions/400'"))

As you can see my definition is named "400". When I change the name of it to "ERROR400", no problems occur.

**Comment by Julian** [comment]
Hi, please always include a full minimal example of your code and unelided traceback.

Thanks.
