### ISSUE TITLE
Release 3.0.0a4

### ISSUE THREAD

**Issue by johnthagen** [Julian/jsonschema#514]
Could a new alpha version be released on PyPI? We currently are suffering issues with using `pytest` because of #477, and having this fixed would be a great benefit.

We are required to use CentOS 7, of which the [official Python 3.6 version from SCL](https://www.softwarecollections.org/en/scls/rhscl/rh-python36/) is 3.6.3 and will probably not be upgraded due to stability guarantees they have.

**Comment by Julian** [comment]
Done!
