### ISSUE TITLE
urit-emplate is not documented

### ISSUE THREAD

**Issue by manycoding** [Julian/jsonschema#521]
Maybe I am missing something, but `uri-template` format is not listed here https://github.com/Julian/jsonschema/edit/master/docs/validate.rst
I found the code to support it https://github.com/Julian/jsonschema/blob/89f0f22a949e3561d05576f27e9a97c8233e2ee9/jsonschema/_format.py#L381, though in the same time there's no `uritemplate` dependency in setup https://github.com/Julian/jsonschema/blob/master/setup.cfg

**Comment by Julian** [comment]
The code is written on this side, but not yet merged within uri-trmplate, so cannot be enabled until the PR there is merged.

**Comment by Julian** [comment]
Lemme know if that made sense, happy to elaborate!
