### ISSUE TITLE
Missing dependency to perf

### ISSUE THREAD

**Issue by rmedaer** [Julian/jsonschema#528]
I figured out that `perf` is not installed automatically as dependency. Any objections to add it in test requirements ?

Kind regards,

**Comment by Julian** [comment]
Hey!

It's not actually currently run during a test run, the only current way it'd be invoked (or that I'd invoke it) has been via `tox -e perf` -- not sure it really belongs in `test-requirements`, which is really about "what do you need to run `trial jsonschema`".

Happy to hear about how you encountered this though?

**Comment by rmedaer** [comment]
Actually I'm trying to package `jsonschema-3.0.0b3` for Debian. Basically, I took the current package and I try to fix all the missing dependencies and others.

I just finished a first pass, here is the (main) issues I got:

  1. Missing dependencies (in Debian packaging):
     * sphinxcontrib.spelling
     * certifi
     * attr
     * ...
  2. Unexisting dependencies (always in Debian packaging):
     * perf : hopefully [Gustavo Panizzo did a first version](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=854024) that [I recovered from here](https://alioth-archive.debian.org/git/collab-maint/python-perf.git.tar.xz)
     * pyrsistent: I didn't find entry in Debian wnpp (#todo) so [I did it my self](https://github.com/rmedaer/debian-pyrsistent) (again it's a first pass) !
  3. I got an issue similar to `fixup-version.patch`, so I modified the patch.
  4. I got some issues with `@_checks_drafts` / `test_{}_{}_ignores_non_strings` (mainly `idn-email`). Currently I disabled them through a quilt patch. I still have to investigate what, why, how ...

I do **not** pretend to do something ready for releasing. Indeed there are a lot of checks/improvements to do. But at least I know what's the delta between versions `2.x.x` and `3.0.0bx`. I will soon publish my changes as "documentation" for Debian maintainers ;-) I hope it will help once version `3.0.0` will be released.

**Comment by Julian** [comment]
> Actually I'm trying to package `jsonschema-3.0.0b3` for Debian.

Right but then neither `sphinxcontrib.spelling`, nor `perf`, nor `certifi` are dependencies of this package for end users.

> I will soon publish my changes as "documentation" for Debian maintainers ;-) I hope it will help once version `3.0.0` will be released.

Awesome! Really appreciated on that piece of course.

**Comment by rmedaer** [comment]
> Right but then neither `sphinxcontrib.spelling`, nor `perf`, nor `certifi` are dependencies of this package for end users.

Indeed, I will then close this issue since it's only build or test dependencies.

**Comment by Julian** [comment]
:) cool, thanks again!
