### ISSUE TITLE
Nullable validation fails

### ISSUE THREAD

**Issue by meddulla** [Julian/jsonschema#533]
Given a spec with a `nullable=True` property  and data with an explicit `null` value, the validation fails if there's no `schemas` property. Ie.

```
schema = {
    "type" : "object",
    "required": ["name"],
    "properties" : {
        "initial_date" : {
            "type": "string",
            "format": "date",
            "nullable": True,
        },
    },
}
```

but passes with the following:

```
schema = {
    "schemas": {
        "type" : "object",
        "required": ["name"],
        "properties" : {
            "initial_date" : {
                "type": "string",
                "format": "date",
                "nullable": True,
            },
        }
    }
}
```

This is surprising and does not seem the same as specifying or not the `$schema` property.  A test case is at https://gist.github.com/meddulla/48a7bcc225ca9c221d54e1d099bb2de7 . Tested with jsonschema '3.0.0'. 

We're using the spec the validate each request as it comes in, and extract the partial spec (from `components-> schema->CustomType`)  for the corresponding request path to validate the request body so that is why at that point it no longer has a full spec. I tried passing the class, eg. `Draft7Validator` but the problem remains.

Is there a better/recommended way to do this?

**Comment by gazpachoking** [comment]
`nullable` is not a defined json schema keyword and so will be ignored. You can instead define that null is a valid type with `"type": ["string", "null"]`

`schemas` is also not a defined json schema keyword. When you wrap your schema in it you end up ignoring the whole thing and anything at all will pass validation.

**Comment by meddulla** [comment]
The confusion with `nullable` came from our spec which is actually an openapi.yaml spec but the request body validations are done using jsonschema.. so that is the issue. 

The last point, using an undefined json schema keyword, shouldn't it raise an exception instead?

**Comment by gazpachoking** [comment]
The spec [defines](https://json-schema.org/latest/json-schema-core.html#rfc.section.4.3.1) that unknown keywords should be ignored. You should be able to define your own metaschema that sets `additionalProperties` to false if you want to catch these cases during development, I'm not up to date on the best way to do that right now though. Maybe someone else will chime in.

**Comment by handrews** [comment]
@meddulla there are tools to convert between OpenAPI's JSON Schema dialect and real JSON Schema.  Not sure offhand if there is one in Python.
