### ISSUE TITLE
please provide proper changelog for 3.0.1

### ISSUE THREAD

**Issue by jberends** [Julian/jsonschema#536]
the release 3.0.1 does not come with a proper changelog. Could you please add the change to the changelog (even it is a oneliner on master)

**Comment by Julian** [comment]
Which change are you referring to

**Comment by jberends** [comment]
Hi @julesjulian. I cannot find a [changelog item](../blob/master/CHANGELOG.rst) found for version 3.0.1.

You marked the tag [v3.0.1](../releases/tag/v3.0.1) with the text `Go go gadget bugfix.`. However in the commit I see more changes. 

We are now unsure of what has been changed. We are using jsonschema in production and rely on jsonschema's for security and data persistence, so changelog is important to us.

**Comment by Julian** [comment]
Ah I see -- yeah obviously a reasonable request!

To be honest, I don't like manually maintaining `CHANGELOG.rst` (or any changelog). If you look in it you'll see in the past there also really wasn't entries for bugfix releases, I really only use it to call out major new features or changes in backwards compatibility.

If you really want to know what's in a release, that'd be what the `git` commit history would be for. In this case, it's #529 and #532. But yeah I don't want to be manually maintaining a changelog :/. If it's really necessary, we can potentially think about [towncrier](https://pypi.org/project/towncrier/) but it only supports py3, and still comes with some overhead...

So not sure if that answers the spirit of your question but maybe tells you what's actually in 3.0.1.

**Comment by Julian** [comment]
Closing, but obviously let me know if you have more thoughts!
