### ISSUE TITLE
[Feature Request] Generate example json based on examples in schema

### ISSUE THREAD

**Issue by ParetoLife** [Julian/jsonschema#537]
This might be outside of the intended scope, but would it be interesting to be able to generate an example json based on the examples that you define in the schema? 
For instance, in a way that https://www.jsonschema.net/ generates them if you let it generate a schema based on already filled in json. 

```
 1 {
 2   "definitions": {},
 3   "$schema": "http://json-schema.org/draft-07/schema#",
 4   "$id": "http://example.com/root.json",
 5   "type": "object",
 6   "title": "The Root Schema",
 7   "required": [
 8     "very_simple"
 9   ],
10   "properties": {
11     "very_simple": {
12       "$id": "#/properties/very_simple",
13       "type": "string",
14       "title": "The Very_simple Schema",
15       "default": "",
16       "examples": [
17         "but it does the job"
18       ],
19       "pattern": "^(.*)$"
20     }
21   }
22 }
```

would thus generate
```
{
    "very_simple": "but it does the job"
}
```

This makes it easy to generate human-readable examples of how the json-to-be-validated should be structured. You could then use that json example for a quick overview/refresher, and dive into the schema if you need more details.

Let me know what you think

**Comment by Julian** [comment]
Hey! Thanks.

It's a decent idea certainly, but yeah out of scope for this repository.

For a way to do this *without* examples (i.e. not necessarily with humans as the intended audience for examples) you might have a look at https://github.com/Zac-HD/hypothesis-jsonschema

But a human-centric way of assembling examples is certainly also a decent idea, would love to see something like that.

**Comment by Julian** [comment]
Closing, but happy to hear what you think!
