### ISSUE TITLE
Using $id with $ref to validate complex Schemas

### ISSUE THREAD

**Issue by jbroenstrup** [Julian/jsonschema#540]
Hi,

I read in the documentation of Json Schema, that it is possible to combine $id and $ref to create "absolute" or "static" references, that, if referenced from a file are independent of this files position in the schema tree. Yet in the documentation of Json Schema [it says](https://json-schema.org/understanding-json-schema/structuring.html#using-id-with-ref), that this features is currently not supported by this python implementation of Json Schema. Since the documentation predates the new 3.0.X releases, I was wandering if this features was added? 

Cheers
Jonas

**Comment by Julian** [comment]
Hi, happy to answer this, but would help if you showed specifically what you're trying to do without having to jump through the links to see -- is there some specific example you're trying to get working that doesn't do what you expect?

**Comment by Julian** [comment]
Closing this, but happy to have a look if you've got an example we can discuss.
