### ISSUE TITLE
How can I resolve all references in a schema?

### ISSUE THREAD

**Issue by Zac-HD** [Julian/jsonschema#542]
I would like to take a schema that may have local or remote references, and return an equivalent schema that does not use any references at all.  This would be really useful for [`hypothesis-jsonschema`](https://github.com/Zac-HD/hypothesis-jsonschema), but I have no idea how to do it with `RefResolver` - I can't tell from [the docs](https://python-jsonschema.readthedocs.io/en/stable/references/) whether this is even something it should do.  

Maybe related to #346?  Any advice would be appreciated - I'd also be happy to e.g. ban remote references or local ids if that would help.  I sketched an idea for the quick-and-dirty on Zac-HD/hypothesis-jsonschema#6 but would prefer an upstream implementation if possible :smile:

**Comment by Julian** [comment]
Will respond with more detail but probably related to #419 (and the latter is "doable" but not as easy as it should be so yeah definitely up for improvements here)

**Comment by handrews** [comment]
@Zac-HD if you don't specifically need it to be in Python, you might take a look at [JSON Schema Ref Parser](https://github.com/APIDevTools/json-schema-ref-parser).

**Comment by maddanio** [comment]
Hmm, but this can't be doable for recursive references, right?

**Comment by Zac-HD** [comment]
> Hmm, but this can't be doable for recursive references, right?

Depends on your perspective - Python containers can contain themselves, so it would be perfectly possible to represent recursive schemas without an explicit `$ref` keyword.

It's probably more ergonomic to only resolve the non-recursive references though, since that would make it trivial to construct a DOS attack against naive code.

Recursive references are also - while not especially *rare* - less common than simple references, so non-recursive resolution would still be very helpful incremental step 😄

**Comment by Zac-HD** [comment]
Closing in favor of Zac-HD/hypothesis-jsonschema#28, since the canonicalisation I want isn't really useful for validators.
