### ISSUE TITLE
Add schema generation

### ISSUE THREAD

**Issue by nedkoh** [Julian/jsonschema#543]
In addition to the ability to validate schemas create a builder which generates a json schema

**Comment by Julian** [comment]
Hi! Thanks for the issue.

This is out of scope for this repo, but you might be interested in https://github.com/Zac-HD/hypothesis-jsonschema

**Comment by nedkoh** [comment]
Thanks will have a look. Lot's of implementations out there for generating schema from sample json but that's incomplete
