### ISSUE TITLE
[Support] Why does RefResolver take a referring document?

### ISSUE THREAD

**Issue by Pluckerpluck** [Julian/jsonschema#545]
Hi,

I'm trying to embed some schema into a local tool that I'm going to use to validate my own custom data with. As a result, I need to load the data myself as they're stored within the python package rather than "locally" as per normal.

My issue is that RefResolver makes almost no sense to me. But it basically boils down to a single question. Why does it take a referring document? What does that do? Does it actually do anything?

Like, if you're using "from_schema" it makes sense to provide it, but otherwise I can't work out what it does. Does it do nothing? Or is "from_schema" just a wrapper around the constructor where you give it a schema?

It's weird simply because in order to use a resolver you have to present a schema along side it, so what does embedding the schema into the resolver actually do?

**Comment by Julian** [comment]
Not to say that `RefResolver` is an example of well designed objects :), and I probably have to go back and check, but *probably* this is because without a schema, what do you want to do with `ref`s that use `#`? (Which refers to "the current document")?

**Comment by Pluckerpluck** [comment]
Ok. That makes sense.... maybe. I realized I could look myself. Don't know why I didn't before.

`from_schema` is literally just a constructor wrapper that sets `base_uri` to the id of the schema. 

`self.store[base_url]` is set to `referrer`. So, as you said, it's used to resolve `#` references.

Design is definitely weird, but it does a job. Definitely less crazy ways to do it, but it is what it is :P
