### ISSUE TITLE
Schema using propertyNames and $ref crashes

### ISSUE THREAD

**Issue by rachekalmir** [Julian/jsonschema#547]
Using propertyNames with $ref causes jsonschema to crash:

Traceback (paths truncated):
```
Traceback (most recent call last):
  File "jsonschema_test.py", line 41, in <module>
    main()
  File "jsonschema_test.py", line 34, in main
    valid = validate(data, schema)
  File "\jsonschema\validators.py", line 897, in validate
    error = exceptions.best_match(validator.iter_errors(instance))
  File "\jsonschema\exceptions.py", line 293, in best_match
    best = next(errors, None)
  File "\jsonschema\validators.py", line 323, in iter_errors
    for error in errors:
  File "\jsonschema\_validators.py", line 28, in propertyNames
    schema=propertyNames,
  File "\jsonschema\validators.py", line 339, in descend
    for error in self.iter_errors(instance, schema):
  File "\jsonschema\validators.py", line 323, in iter_errors
    for error in errors:
  File "\jsonschema\_validators.py", line 251, in ref
    for error in validator.descend(instance, resolved):
  File "\jsonschema\validators.py", line 339, in descend
    for error in self.iter_errors(instance, schema):
  File "\jsonschema\validators.py", line 307, in iter_errors
    scope = id_of(_schema)
  File "\jsonschema\validators.py", line 151, in _id_of
    return schema.get(u"$id", u"")
AttributeError: 'str' object has no attribute 'get'
```

Reproduction:
```
schema = {
        "$schema": "http://json-schema.org/draft-07/schema#",
        "$id": "http://example.com/product.schema.json",
        "title": "Product Schema",
        "description": "A product in the catalog",
        "type": "object",
        "patterns": {
            "product_name": "^[A-Z_0-9]$"
        },
        "propertyNames": {
            "$ref": "#/patterns/product_name"
        },
        "patternProperties": {
            "": {
                "type": "object",
                "properties": {
                    "product_id": {
                        "type": "number"
                    }
                },
                "required": ["product_id"]
            }
        },
    }
    data = {
        "PRODUCT1": {
            "product_id": "a"
        }
    }
    valid = validate(data, schema)
```

python version: 3.7
jsonschema version: 3.0.1

**Comment by Julian** [comment]
`$ref` references schemas, not arbitrary values.

You're pointing it at just the value ` "^[A-Z_0-9]$"` which isn't a valid schema.

**Comment by rachekalmir** [comment]
Ah okay cool.

I fixed the error by using:
```
schema = {
        "$schema": "http://json-schema.org/draft-07/schema#",
        "$id": "http://example.com/product.schema.json",
        "title": "Product Schema",
        "description": "A product in the catalog",
        "type": "object",
        "patterns": {
            "product_name": {
                "pattern": "^[A-Z_0-9]+$"
            }
        },
        "propertyNames": {
            "$ref": "#/patterns/product_name"
        },
        "patternProperties": {
            "": {
                "type": "object",
                "properties": {
                    "product_id": {
                        "type": "number"
                    }
                },
                "required": ["product_id"]
            }
        },
    }
    data = {
        "PRODUCT1": {
            "product_id": 1
        }
    }
    valid = validate(data, schema)
```

I expected the library to validate the schema first though against the schema listed in the "$schema" when it is first compiled, but maybe my assumption is incorrect here?

**Comment by Julian** [comment]
Your assumption is correct! The meta schema (i.e. what you have in `$schema` -- the official draft 7 schema) just doesn't actually contain validation for the above.

So this library does validate that the schema is "valid" according to the metaschema, but the metaschema (in fact JSON Schema itself) has no way of writing this validation condition as a JSON Schema condition, so as far as the metaschema is concerned your schema is "valid", but it violates the spec.

**Comment by Julian** [comment]
(Possibly something to raise upstream in the spec repo)

**Comment by handrews** [comment]
Ugh.  yeah, we need to do another bugfix patch on the meta-schemas.  I'm trying to focus on finishing the spec though so maybe someone else could take that on?  There's at least one bug filed on it already.

**Comment by Julian** [comment]
I thought for less than 30 seconds about this to be honest, so possibly I'm just really not thinking clearly, but @handrews I don't think this condition is even representable within JSON Schema, is it?

The thing you're trying to apply validation conditions to isn't the value that's in the schema, it's the dereferenced object. There's no property that works like that, unless my brain is severely behind today.

**Comment by rachekalmir** [comment]
I am new to using JSON schema so please correct me if I am wrong.

The propertyNames in the meta schema has `"propertyNames": { "$ref": "#" },` which will replace the inner schema with the full meta schema (i.e. propertyNames must be a valid JSON schema as per the spec). And when this replacement occurs the resulting schema has in the root `"type": ["object", "boolean"],` which is correct according to the spec correct. However, in this case it seems that this type validation is not occurring after the replacement has occurred?

**Comment by Julian** [comment]
Yeah that's correct, the thing though is that `{"$ref": "foo"}` is a valid
schema regardless of what foo is.

**Comment by Julian** [comment]
Gonna close this, but happy to discuss upstream in the spec repo @rachekalmir if you're interested.

**Comment by rachekalmir** [comment]
Yeah, I would be happy to discuss it upstream.
Seems to be more of a spec problem whereby you would need to treat schema validation of a another schema (e.g. compilation) in a different way to general schema validation.
