### ISSUE TITLE
"If then" statements in schema are validating incorrectly 

### ISSUE THREAD

**Issue by szklany** [Julian/jsonschema#550]
Hi,

i'm trying to construct a complex schema which validates the JSON structure according to values in an array.

Here is an example schema

`schema = {
    "type": "object",
    "properties": {
        "globalRef": {
            "type": "array"
        }
    },
    "allOf": [
        {
            "if": {
                "properties": {
                    "globalRef": {
                        "contains": {
                            "enum": [
                                "software"
                            ]
                        }
                    }
                }
            },
            "then": {
                "required": [
                    "swVersion"
                ]
            }
        },
        {
            "if": {
                "properties": {
                    "globalRef": {
                        "contains": {
                            "enum": [
                                "hardware"
                            ]
                        }
                    }
                }
            },
            "then": {
                "required": [
                    "hwVersion"
                ]
            }
        }
    ]
}`

The schema sets the requirements "hwVersion" and/or "swVersion" if "hardware" and/or "software"are added to the "globalRef" array.
But for some reason the "then" statement seems to always be executed, even if no values are added to the array 

Example:
`validate(instance={}, schema=schema)

jsonschema.exceptions.ValidationError: 'swVersion' is a required property

Failed validating 'required' in schema['allOf'][0]['if']['then']:
    {'required': ['swVersion']}

On instance:
    {}
`

This "If then" logic works fine with other validators like https://json-schema.org/.

I hope this issue can be fixed, since the validator works great otherwise.

**Comment by Julian** [comment]
Hi. That looks correct to me.

Your schema doesn't require `globalRef` at all, in which case the `then` executes, because the `if` passes.

Which validator are you referring to that allows that?

**Comment by szklany** [comment]
Hi Julian,

yeah sorry I just noticed that myself.
