### ISSUE TITLE
$schema must not appear in subschemas

### ISSUE THREAD

**Issue by dsanders11** [Julian/jsonschema#553]
From the spec:

> The "$schema" keyword SHOULD be used in a root schema. It MUST NOT appear in subschemas.

But I'm seeing the following schema pass:

```python
from jsonschema import Draft7Validator

schema = {
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "Root Schema",
    "properties": {
        "foo": {
            "type": "array",
            "items": {
                "$schema": "http://json-schema.org/draft-07/schema#",
                "title": "Subschema"
            }
        }
    }
}

Draft7Validator.check_schema(schema)  # Passes
```

**Comment by Julian** [comment]
I'd have to check, but essentially this typically means the meta schema
doesn't contain validation for this constraint

**Comment by Julian** [comment]
(Which to finish the thought there means that usually this issue belongs upstream as a bug on the metaschema)

**Comment by Julian** [comment]
Yeah so double checking the meta schema, it does not in fact enforce this, though it could -- would you be able to file this upstream on https://github.com/json-schema-org/json-schema-spec/issues ?
