### ISSUE TITLE
How to Validate Schema Itself

### ISSUE THREAD

**Issue by stellarpower** [Julian/jsonschema#554]
Hi,

I'm aware that validate will check my schema before validating the instance against this, but I can't see an easy way to check that my schema is valid before I try to validate any data in the documentation.

If this is possible already, it'd be great to add to the documentation. If not, adding jsonschema.checkSchema(...) or calling validate using my schema as the instance, and a refrence to the schema specification as the schema would be useful; I can't see an evident way to do this at the moment, so I'm going to try and validate against nothing and catch the right exception instead.

Thanks for this useful library!

**Comment by Julian** [comment]
Hi! Thanks.

The way to validate schemas is by calling [`SomeValidator.check_schema`](https://python-jsonschema.readthedocs.io/en/stable/validate/#jsonschema.IValidator.check_schema).

Could you possibly suggest an improvement (or better a PR!) that would have helped you find that in the documentation?
