### ISSUE TITLE
python 3 Validation json 

### ISSUE THREAD

**Issue by ItBankB** [Julian/jsonschema#556]
Tell me please, it is impossible to make a scheme for the following object:
{
"id_client" : "123456",
"uuid_client": "123456",
"request" : "true",
"object_r" : {
	"t"  : "20180518T220500",
	"s"  : "975.88",
	"fn" : "8710000101125654",
	"i"  : "99456",
	"fp" : "1250448795",
	"n"  : "1"
	}	
}
I use

from jsonschema import validate

`
schema = {
        "type": "object",
        "properties": {
            "id_client": {
                "type": "string",
                "required":False
                },
            "uuid_client": {
                "type": "string",
                "required":False
                },
            "request": {
                "type": "string",
                "required":False
                },
            "object_r": {
                "type":"array",
                "required":False,
                "items":
                    {
                        "type":"object",
                        "required":False,
                        "properties":{
                            "t": {
                                "type": "string",
                                "required":False
                                },
                            "s": {
                                "type": "number",
                                "required":False
                                },
                            "fn": {
                                "type": "number",
                                "required":False
                                },
                            "i": {
                                "type": "number",
                                "required":False
                                },
                            "fp": {
                                "type": "number",
                                "required":False
                                },
                            "n": {
                                "type": "number",
                                "required":False
                                }
                        }
                    }
                }
            }
        }
`

**Comment by Julian** [comment]
Hi! Sorry you're having trouble.

If possible, please try to use IRC, StackOverflow, or the JSON Schema Slack for these, so that we can keep the bug tracker for issues. Thanks!
