### ISSUE TITLE
Integer type fails for numbers which are numerically integer, but of type float

### ISSUE THREAD

**Issue by mitar** [Julian/jsonschema#557]
I just got a surprised result when I got a JSON where all numbers are always encoded in floating point format. Because in JavaScript and JSON there is no differentiation between floats and integers, this is valid JSON encoding. The problem is that Python then reads this as a `float` type which then fails JSON schema validation. So same JSON schema cannot be used across systems for various otherwise valid JSON serializations.

I could not find any issue about this already, so I would like to open this and see if something can be done here to improve interoperability.

It is interesting to note that this is in fact even [documented here](https://json-schema.org/understanding-json-schema/reference/numeric.html):

> The precise treatment of the “integer” type may depend on the implementation of your JSON Schema validator. JavaScript (and thus also JSON) does not have distinct types for integers and floating-point values. Therefore, JSON Schema can not use type alone to distinguish between integers and non-integers. The JSON Schema specification recommends, but does not require, that validators use the mathematical value to determine whether a number is an integer, and not the type alone. Therefore, there is some disagreement between validators on this point. For example, a JavaScript-based validator may accept 1.0 as an integer, whereas the Python-based jsonschema does not.

I would suggest that the check for integer is done something like `isinstance(value, int) or (isinstance(value, float) and int(value) == value)`.

**Comment by Julian** [comment]
Hi, thanks!

What version of JSON Schema are you using (and of the library) -- as of draft 6 (and `jsonschema 3.0`) the float `1.0` is now considered to be an integer. Are you on something later than that?

**Comment by mitar** [comment]
I am using draft 4.

**Comment by Julian** [comment]
Yeah so in draft 6 or newer I think you'll see the behavior you want.

The earlier drafts yeah were more tied to the specific type.

**Comment by mitar** [comment]
You are right, with `jsonschema.Draft6Validator` it works.

So could this also be updated for earlier drafts?

In any case, it seems that then the language on the site I linked to is not true anymore.

**Comment by mitar** [comment]
I opened: https://github.com/json-schema-org/understanding-json-schema/pull/99

**Comment by Julian** [comment]
I actually prefer the old behavior myself :)

It's easier to say "use whatever configuration in your JSON parser that you'd like to map to Python types, and from that point the library doesn't care".

Now it's more complicated to reason about -- so don't think the behavior will go back into old drafts as a default, but yeah it's now mandated by the spec for new drafts so it'll be in there for new ones.

You *can* if you'd like apply the behavior to draft 4, the hook you need is the [`type checker`](https://python-jsonschema.readthedocs.io/en/stable/validate/#validating-types) object -- so e.g. if you extend the Draft 4 validator and give it the Draft6 validator's implementation of type, you'll get that behavior.

**Comment by mitar** [comment]
> It's easier to say "use whatever configuration in your JSON parser that you'd like to map to Python types, and from that point the library doesn't care".

Sure, but one would hope default JSON schema (draft 4) would work with default Python JSON parser.

Anyway, I understand the problem now and I have also managed to fix this locally for me. But it did took me a lot of debugging and one large batch of JSON documents now being not stored into the database because they were seen as invalid. Not sure how to document maybe this for somebody else. But it should improve if people move to draft 6 or latter.

**Comment by mitar** [comment]
(Feel free to close this issue.)

**Comment by Julian** [comment]
Like I said, it *does* work just fine for draft 4 as well :)

There are two reasonable behaviors. You expected the newer one, older drafts expected the other one. They said:

> As a consequence, for interoperability reasons, JSON values used in
   the context of JSON Schema, whether that JSON be a JSON Schema or an
   instance, SHOULD ensure that mathematical integers be represented as
   integers as defined by this specification.

Glad you got it working though.
