### ISSUE TITLE
How to properly validate subschemas?

### ISSUE THREAD

**Issue by kolszewska** [Julian/jsonschema#561]
Hi,

I'm having problems properly validating subschemas when using the OneOf specification.

I have 2 schemas, let's call them A and B. I'm writing a negative test case for the schema A. The problem is that I am getting the validation error that comes from the B and of course I would like to get what went wrong in the A subschema. 

When I am debugging I can see that my error from schema A is on the list of errors. But sadly the `best_match` won't return the error that I am looking for. Is there is some function/trick that I can use to extract the error that I am looking for (something along the lines that validator knows "ok, this is probably the subschema A, so the best error would come from this spec).

Thanks for help :)

**Comment by Julian** [comment]
Hi!

Could you possibly show an executable example, might help to see if what you're asking for is a possible improvement to `best_match`?

**Comment by Julian** [comment]
Closing this out, but happy to discuss if you've got an example!
