### ISSUE TITLE
Set error messages

### ISSUE THREAD

**Issue by hound672** [Julian/jsonschema#564]
Hello, It's question just for discussion.
For example, I have a multilanguage application. And I want to make all translation on clientside (JS, React etc). In that case I wouldn't like to get human-readable error messages from Jsonschema validation, instead of it I'd rather get some code errors, like: 

> %FIELD_NAME% ERR_DOES_NOT_EXIST

I would try to make some stuff in this lib. 
Does it make sense?

**Comment by Julian** [comment]
Hi. Have a look at https://python-jsonschema.readthedocs.io/en/stable/errors/ which has documentation on all the available properties for validation errors. Happy to answer specific questions, though ideally not on the bug tracker.
