### ISSUE TITLE
Inconsistency when value fails type and enum check

### ISSUE THREAD

**Issue by blakehilliard** [Julian/jsonschema#571]
Consider this program:

```
$ cat ~/json-schema-test.py 
import jsonschema

schema = {
    'enum': ['3', '5'],
    'type': 'string',
}

failed_validators = {}
for _ in range(100):
    checker = jsonschema.FormatChecker()
    try:
        jsonschema.validate(None, schema, format_checker=checker)
    except jsonschema.exceptions.ValidationError as exc:
        if exc.validator not in failed_validators:
            failed_validators[exc.validator] = 0
        failed_validators[exc.validator] += 1

print(failed_validators)
```

I would expect it to always fail validating the _type_ of the value rather than iterate over the enum before doing the type check. But if you run it, it sometimes rejects None for having an invalid type and sometimes for not being in the enum list. What's even stranger, it varies across times you execute this script, not within a single execution:

```
$ for i in {1..10} ; do python3 ~/json-schema-test.py ; done
{'type': 100}
{'type': 100}
{'enum': 100}
{'enum': 100}
{'enum': 100}
{'enum': 100}
{'type': 100}
{'enum': 100}
{'enum': 100}
{'enum': 100}
```

Version details:

```
[mfw]$ python3
Python 3.5.3 (default, Apr 28 2018, 10:34:28) 
[GCC 4.8.5] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import jsonschema
>>> jsonschema.__version__
'3.0.1'
```

**Comment by Julian** [comment]
What makes you expect it to always fail with one or the other?

**Comment by blakehilliard** [comment]
1. Getting the type wrong is a more basic type of problem than not being in the enum, therefore it's more helpful for the client to know that's where they messed up.
2. Performance. It's quicker to check the type than iterate through an enum list.

**Comment by Julian** [comment]
It sounds like you want to have a look at the documentation on validation
errors.

https://python-jsonschema.readthedocs.io/en/stable/errors/#best-match-and-relevance

**Comment by Julian** [comment]
Closing, but happy to see a PR improving the docs if you find anything missing.
