### ISSUE TITLE
Pattern rule does not work correctly.

### ISSUE THREAD

**Issue by alvassin** [Julian/jsonschema#576]
For some reason, jsonschema does not handle pattern rule correctly.

```
from jsonschema import validate

schema = {
    "type" : "object",
    "properties" : {
        "price" : {"type" : "string", 'pattern': '^[a-z]+$'},
    },
}

# Works
validate(instance={ "price" : 'badstring\n\n'}, schema=schema)

# Does not work
validate(instance={ "price" : 'badstring\n'}, schema=schema)
```

**Comment by Julian** [comment]
Please don't file bugs saying entire large swaths of functionality don't work -- jsonschema is fairly well tested.

In your case, yes, that's what `$` does in Python regexes. See the [documentation on regexes for the $ character](https://docs.python.org/3/library/re.html), as well as simply trying `re.search('^[a-z]+$', 'badstring\n\n')`.
