### ISSUE TITLE
Validating with additional types and the implicit validator

### ISSUE THREAD

**Issue by maggyero** [Julian/jsonschema#577]
I used to validate with additional types with this code:

```python
jsonschema.validate(instance, schema, types={"array": (list, tuple)})
```

Now I get a `DeprecationWarning` (with JSON Schema 3.0.1):

> DeprecationWarning: The types argument is deprecated. Provide a type_checker to jsonschema.validators.extend instead.
>   validator = cls(schema, *args, **kwargs)

So I have looked at the documentation to update my code, and I have found this  [example](https://python-jsonschema.readthedocs.io/en/stable/validate/#validating-with-additional-types) for validating with additional types the new way:

```python
class MyInteger(object):
    pass

def is_my_int(checker, instance):
    return (
        Draft3Validator.TYPE_CHECKER.is_type(instance, "number") or
        isinstance(instance, MyInteger)
    )

type_checker = Draft3Validator.TYPE_CHECKER.redefine("number", is_my_int)

CustomValidator = extend(Draft3Validator, type_checker=type_checker)
validator = CustomValidator(schema={"type" : "number"})
```

It seems that now I have to _specify the validator version explicitly_ (`Draft3Validator`). But I don't want to specify the version, I would like to use the implicit validator like in my code above. Is this currently possible with the new way?

**Comment by Julian** [comment]
It's possible that there's a case to have a `TypeChecker.for_type` method that just shortens the new API a bit -- but on the

> It seems that now I have to specify the validator version explicitly

You should be specifying the version that your schema uses (via the `$schema` property).

If you are, you can use `extend(validator_for(schema), ...)` and it will use the right version as declared.

**Comment by maggyero** [comment]
@Julian
Thank you, that is exactly what I was looking for:

```
>>> jsonschema.validators.validator_for({}).META_SCHEMA["$schema"]
'http://json-schema.org/draft-07/schema#'
```

When specifying the schema version it works too:
```
>>> jsonschema.validators.validator_for({"$schema": "http://json-schema.org/draft-03/schema#"}).META_SCHEMA["$schema"]
'http://json-schema.org/draft-03/schema#'
>>> jsonschema.validators.validator_for({"$schema": "http://json-schema.org/draft-04/schema#"}).META_SCHEMA["$schema"]
'http://json-schema.org/draft-04/schema#'
>>> jsonschema.validators.validator_for({"$schema": "http://json-schema.org/draft-06/schema#"}).META_SCHEMA["$schema"]
'http://json-schema.org/draft-06/schema#'
>>> jsonschema.validators.validator_for({"$schema": "http://json-schema.org/draft-07/schema#"}).META_SCHEMA["$schema"]
'http://json-schema.org/draft-07/schema#'
```

So I have rewritten this code:
```
jsonschema.validate(instance, schema, types={"array": (list, tuple)})
```
 as:
```
import jsonschema

schema = {"type": "array"}


def is_list_or_tuple(checker, instance):
    return (
        jsonschema.validators.validator_for(schema).TYPE_CHECKER.is_type(instance, "array")
        or isinstance(instance, tuple))


validator = jsonschema.validators.validator_for(schema)
type_checker = validator.TYPE_CHECKER.redefine("array", is_list_or_tuple)
validator_cls = jsonschema.validators.extend(validator,
                                             type_checker=type_checker)
validator = validator_cls(schema)
instance = (1, 2, 3)
validator.validate(instance)
```

Is this correct? Or can I make it shorter?

**Comment by Julian** [comment]
Great! That's correct, but yeah you can make it shorter if you'd like by just directly implementing the logic you want. I.e.

```python
TupleAllowingValidator = jsonschema.validators.extend(
    validator,
    type_checker=validator.TYPE_CHECKER.redefine(
        "array", lambda instance: isinstance(instance, (list, tuple)),
)
```

**Comment by maggyero** [comment]
Thank you, it works (you only forgot the `checker` parameter for the `lambda`):

```python
import jsonschema

schema = {"type": "array"}
instance = (1, 2, 3)

Validator = jsonschema.validators.validator_for(schema)
type_checker = Validator.TYPE_CHECKER.redefine(
    "array", lambda checker, instance: isinstance(instance, (list, tuple)))
TupleAllowingValidator = jsonschema.validators.extend(Validator,
                                                      type_checker=type_checker)

TupleAllowingValidator(schema).validate(instance)
```

**Comment by Julian** [comment]
Correct yeah that's all it does.
