### ISSUE TITLE
jsonschema.validate(42, {"a": "b"}) raises no exceptions?

### ISSUE THREAD

**Issue by karlosss** [Julian/jsonschema#579]
This is probably a newbie one, but why this code raises no exceptions? Is there any way to force it to raise a `SchemaError`?

`jsonschema.validate(42, {"a": "b"})`

**Comment by Julian** [comment]
This is likely the most common newbie question to *JSON Schema*, not this library specifically :), so definitely it seems to deserve a FAQ upstream I guess, but that's just how JSON Schema works in all current drafts.

Additional properties are intentionally ignored by default.
