### ISSUE TITLE
Specify instance type in docstring?

### ISSUE THREAD

**Issue by laurenmarietta** [Julian/jsonschema#581]
I'm trying to just use the basic `validate(instance, schema)` function. The docstring for this function describes the `instance` argument as "The instance to validate."

This is not particularly specific - is this `instance` a filename to a JSON file? An open file object of a JSON file? A string of JSON text? A JSON object opened with `json.load()`? Or an instance of one of the classes defined within `jsonschema`?

It would be helpful, appreciated, and hopefully easy to update that docstring to be more specific.

**Comment by Julian** [comment]
Hi.

"Instance" there is actually a [technical term from the specification](http://json-schema.org/latest/json-schema-core.html#rfc.section.4.2). I could have sworn there was a link to that section of the spec at the first usage of the word in the documentation but I don't see it on [the validate function's docs](https://python-jsonschema.readthedocs.io/en/stable/validate/#the-basics) at least which is I assume what you're referring to. Happy to see a PR adding that link if that'd help you.

As for specificity -- the type of that parameter is "any object". Instances can be of any Python type, so happy to hear what you'd think a helpful way to say that would be too.

**Comment by Julian** [comment]
Closing this since I'm not sure I see a way to improve this, but happy to see any changes you propose.
