### ISSUE TITLE
What is the reason to not have tests suites as git submodule from json-schema-org?

### ISSUE THREAD

**Issue by ystreibel** [Julian/jsonschema#583]
Hello,

I compare the tests suites of jsonschema vs json-schema-org repositories. Could you explain why in jsonschema repository the tests suites directory is not a submodule from json-schema-org?

What's the differences between those two tests suites ?
Did you make the effort to maintain both in parallele ?

Thank you !

**Comment by Julian** [comment]
The tests are a git subtree, which is essentially a slightly improved version of git submodules.

**Comment by Julian** [comment]
Closing but hopefully that answered your question!
