### ISSUE TITLE
Support for MongoDB $bsonType extensions

### ISSUE THREAD

**Issue by ee987** [Julian/jsonschema#586]
When working with mongodb the database can enforce document structure with jsonSchema according to [1].

However mongodb has some own datatypes [2], like ObjectId, Date, Bool, Int  that are not supported natively by json schema. These can be encoded by using the extension "bsonType"  property instead of "type".

It would be very useful if jsonschema could validate such objects also. When a document fails validation inside mongodb you don't get any explanation why [3], so you always have to validate it with another validator client-side on failed insertions. Right now there is no such validator for python so the best workaround is to remove all bsonTypes before using jsonschema or convert the document into nodejs and use ajv. Neither option is really smooth.

[1] https://docs.mongodb.com/manual/reference/operator/query/jsonSchema/#jsonschema-extension
[2] https://docs.mongodb.com/manual/reference/operator/query/type/#document-type-available-types
[3] https://jira.mongodb.org/browse/SERVER-20547

**Comment by Julian** [comment]
This is as far as I know perfectly well supported, and there are users doing so.

What issue are you having and have you read the documentation on type extension

**Comment by Julian** [comment]
Closing, but happy to help if there's something specific here you're running into.

**Comment by ee987** [comment]
I think i managed to solve it now. Here is the core of it in case anyone else is interested.
It would have to be extended to support all required bsonTypes. 
Small caveat is that bsontype and type shares underlying type-checker implementation so it will also accept bsontypes in the types property, but such schema would be rejected by mongo before even loaded so i think that's acceptable.

`import jsonschema
from jsonschema import Draft7Validator
from bson import ObjectId

def is_objectId(checker, instance):
    return isinstance(instance, ObjectId)

type_checker = Draft7Validator.TYPE_CHECKER.redefine("objectId", is_objectId)
CustomValidator = jsonschema.validators.extend(Draft7Validator, type_checker=type_checker)
CustomValidator.VALIDATORS["bsonType"] = Draft7Validator.VALIDATORS["type"]`

**Comment by juan-dura** [comment]
I am trying to implement this solution. But I obtain this error 

> AttributeError: 'dict' object has no attribute 'iter_errors'

@ee987 can you help me?

        import jsonschema
        from jsonschema import Draft7Validator
        from bson import ObjectId
        
        def is_objectId(checker, instance):
            return isinstance(instance, ObjectId)
        
        type_checker = Draft7Validator.TYPE_CHECKER.redefine("objectId", is_objectId)
        CustomValidator = jsonschema.validators.extend(Draft7Validator, type_checker=type_checker)
        CustomValidator.VALIDATORS["bsonType"] = Draft7Validator.VALIDATORS["type"]
        
        schema =  {
          	"bsonType": "object",
            "properties":{
              "scan":{
                "bsonType": "object",
                "required": ["code"],
                "properties":{
                  "code": {
                    "bsontype" : "string"
                    },
                  "device": {
                    "bsonType": "int"
                    }
                  
                  }
                }
            }
          }
          
        dic = { 
          "scan" : {
            "code": "hello",
            "device": 34
            } 
          } 
        
        
        CustomValidator.validate(dic,schema)

**Comment by qhaas** [comment]
@juan-dura 

In jsonschema 4.20.0, the [`jsonschema.validators.extend`](https://python-jsonschema.readthedocs.io/en/stable/creating/) function returns a class: `RETURNS: a new jsonschema.protocols.Validator class extending the one provided`

You need to instantiate your new `CustomValidator` class with your schema, e.g.
```
my_validator = CustomValidator(schema)
my_validator.validate(dic)
```
MongoDB 4-7 uses [json-schema draft4](https://www.mongodb.com/docs/manual/reference/operator/query/jsonSchema/#json-schema), not Draft 7, so you might want to use `Draft4Validator` instead of `Draft7Validator`

There is also another issue in that [json-schema draft 4](https://json-schema.org/draft-04/json-schema-core#rfc.section.3.5) uses `integer` instead of `int`.  So, you will need to switch your `TYPE_CHECKER.redefine` to a `TYPE_CHECKER.redefine_many` and add it, [along with any other bson specific types you might need](https://www.mongodb.com/docs/v7.0/reference/bson-types/), e.g.
```
bson_redefines = {
        "objectId": lambda checker, instance:  isinstance(instance, ObjectId),
        "int": lambda checker, instance:  isinstance(instance, int),
}
bson_checkers = Draft4Validator.TYPE_CHECKER.redefine_many(bson_redefines)
CustomValidator = jsonschema.validators.extend(Draft4Validator, type_checker=bson_checkers)
```
