### ISSUE TITLE
Install with Conda

### ISSUE THREAD

**Issue by yehoshuadimarsky** [Julian/jsonschema#588]
Hi, I use conda a lot instead of pip and I'd love to be able to install this with Conda. I volunteer to get it added to the conda-forge channel - that's the open community channel where people can contribute to. It's pretty straightforward to do once you get the hang of it, especially for libraries that are already on PyPI. I'll use this issue to keep everyone posted about this, once you let me know it's ok to publish on Conda.

(As an aside, I've done this already with several other PyPI libraries that I wanted in conda - see `ib-insync`, `azure-cosmos-python`, `pyfinance`, and others).

Also, the conda "recipe" requires at least one maintainer, I'm happy to do so, but if you wish to also be a maintainer, let me know and I can get you added. 

Thanks for this great package!

**Comment by Julian** [comment]
Hi! Thanks for volunteering, that sounds great.

Please do add me though yeah in case in a year from now you decide to change your mind :)

**Comment by yehoshuadimarsky** [comment]
Wow was I dumb... this package is already *_ON_* conda-forge: https://github.com/conda-forge/jsonschema-feedstock. My bad. Thanks @minrk, @nehaljwani, and @ocefpaf for being the maintainers. Issue closed.

@Julian You can ask them to be added as a maintainer if you wish.
