### ISSUE TITLE
Accept `collections.abc.MutableMapping` instances as valid `object` instances

### ISSUE THREAD

**Issue by hblunck** [Julian/jsonschema#592]
Hey,

first: Thanks for the great work! I really appreciate your library!

I recently played around with my custom collections, i.e. classes that pretend to be python collections, in particular `dict` objects.

I derived these custom mappings from [`collections.abc.MutableMapping`](https://docs.python.org/3/library/collections.abc.html#collections.abc.MutableMapping). However, passing those instances as schemas to `jsonschema.validate` yields an error as it cannot be validated that the schema is of type `object`.

Here is some example code. Basically, the first call to `jsonschema.validate` works as expected, the second call complains that the schema is not of type object.

```python
import jsonschema
from collections.abc import MutableMapping

# Create my own class that looks a lot like a dictionary.
class MyMapping(MutableMapping):
    def __init__(self, **kwargs):
        self._content = kwargs
    
    def __getitem__(self, key):
        return self._content[key]
    
    def __setitem__(self, key, value):
        self._content[key] = value
    
    def __delitem__(self, key):
        del self._content[key]
    
    def __iter__(self):
        return iter(self._content)
    
    def __len__(self):
        return len(self._content)
    
    @classmethod
    def from_dict(cls, d):
        return cls(**d)
    

schema = {
    'type': 'object',
    'properties': {
        'name': {
            'type': 'string'
        },
        'age': {
            'type': 'number'
        },
        'descendants': {
            'type': 'array',
            'items': {
                '$ref': '#/human'
            }
        }
    },
    'required': ['name']
}

data = {
    'name': 'John Doe'
}


# First we try the original schema -> This works
jsonschema.validate(data, schema)
# Now, to show that MyMapping works but that jsonschema
# requires a class derived from dict, we create a second
# custom class that also inherits from dict but uses the
# methods defined in MyMapping for item access.
class MyDictBasedMapping(dict, MyMapping):
    pass

jsonschema.validate(data, MyDictBasedMapping.from_dict(schema))

# Finally, just using MyMapping does not work.
jsonschema.validate(data, MyMapping.from_dict(schema))
```

I tried to break down the problem and assume it relates to [this code segment](https://github.com/Julian/jsonschema/blob/8c725a1e4ded065dfd23c0d49d790df8e5396e6c/jsonschema/validators.py#L88) where the type check for `object` JSON types is set to a Python `dict`. Would it be possible to relax this to `collections.abc.MutableMapping`?

Regards,

Henning

**Comment by Julian** [comment]
Thanks!

Have you read the docs on [`type customization`](https://python-jsonschema.readthedocs.io/en/stable/validate/#validating-types)?

**Comment by hblunck** [comment]
Sorry, that makes sense. I will close the issue.
