### ISSUE TITLE
ISSUE/QUESTION - jsonschema.exceptions.RefResolutionError: Unresolvable JSON pointer: 'components/schemas/head'

### ISSUE THREAD

**Issue by sl2016** [Julian/jsonschema#596]
I am trying to validate the JSON with the expected Open API JSON schema(generated by FastAPI/Pydantic). However, for the $ref nodes in the schema, I receive an error message - "Unresolvable JSON pointer: %r" % fragment and jsonschema.exceptions.RefResolutionError: Unresolvable JSON pointer: 'components/schemas/head'

**Comment by Julian** [comment]
Hi. There isn't nearly enough information to help here, but also please try to use the Slack channel for questions, and the issue tracker for actual bugs (after first checking to see if any of the existing ones sounds like your issue).
