### ISSUE TITLE
RFE: Formalize workflow for loading and caching schema from localhost

### ISSUE THREAD

**Issue by jnsnow** [Julian/jsonschema#599]
The URI in my schema are not yet valid as they are in development. What I'd like to do is use jsonschema to load a number of .json files locally, and have any `$ref` references load from a local cache.

(Also, this helps unit tests in my code base before I push schema to production where they could be fetched by jsonschema. It's important to use the files from the local development branch and not those in production.)

There's kind-of support for this, because RefValidator has a cache. However, jsonschema.validate() creates a new Validator for every call. You can create your own validator, but seemingly you need to create a new one every time and manually propagate the cache, because the RefResolver appears to care about the base_url from the schema it was created from.

There doesn't *appear* to be support for creating something abstract like a ResolverContext that isn't specific to a particular Schema where cache items can be shared "globally" in a program.

I can kind of fudge it like this:

```python
with open("referenced-schema.json", "r") as infile:
    target_schema = json.load(infile)

with open("referencing-schema.json", "r") as infile:
    source_schema = json.load(infile)

# Grab a resolver so we have access to it after validate()
resolver = jsonschema.RefResolver.from_schema(target_schema)
jsonschema.validate(instance=foo, schema=target_schema, resolver=resolver)
# reach in and grab the resolver cache
store = resolver.store

# Create a new resolver for the next schema
resolver = jsonschema.RefResolver.from_schema(source_schema)
resolver.store.update(store)
jsonschema.validate(instance=bar, schema=sourcei_schema, resolver=resolver)
```

Do you have a recommendation for how to achieve this kind of a workflow? Ideally, I'd be able to do something as simple as this:

```python
context = jsonvalidator.RefContext()
jsonschema.validate(instance=foo, schema=target_schema, context=context)
jsonschema.validate(instance=bar, schema=source_schema, context=context)
```

**Comment by Julian** [comment]
It's just an argument to `RefResolver`. If you want to pass it around everywhere, `store = {...}; resolver = RefResolver(..., store=store)`, and then create as many validator instances as you'd like using that resolver.

**Comment by Julian** [comment]
Did that help?

**Comment by jnsnow** [comment]
I haven't gotten a chance to look again yet, sorry! I ran out of weekend time. Thank you for your time and in following up.

I might be confused, because it seemed to me like the RefResolver was an object that had schema-level scope and not project-level scope; by which I mean that because RefResolver necessarily takes a schema as an argument, I thought that it wasn't suitable for checking *other* schema. Looking into the source (briefly) led me to think it had some state that contextualized it to a particular schema.

Still, I don't think I realized you could just pass a store directly to the RefResolver constructor, so I'm thinking I could get away with something like the following:

```python
global_store = {}

def cached_validate(*, schema, instance, **kwargs):
    resolver = jsonschema.RefResolver.from_schema(schema, store=global_store)
    jsonschema.validate(instance=instance, schema=schema, resolver=resolver)

# Validate leaf schema
cached_validate(schema=leaf_schema, instance=foo)

# Validate root schema
cached_validate(schema=root_schema, instance=bar)
```

Does that seem right to you?

Either way, it would be nice to have access to some shared state at the `validate()` level, but if the above works I can't complain too much.

I'll look into it more this weekend, thanks!
