### ISSUE TITLE
TypeError: string indices must be integers

### ISSUE THREAD

**Issue by RichardCullen** [Julian/jsonschema#602]
Sorry I can't provide more info but I've auto-generated a schema using https://jsonschema.net/ from a lengthy JSON file and am getting this exception thrown. Schemas in both draft-06 and -07 throw the same error.
Any tips for bug-hunting?
Python 3.7.3, Win x64

Thanks

```
Traceback (most recent call last):
  File "verifyjson.py", line 13, in <module>
    validate(instance=data, schema=schema)
  File "C:\work\test\env\lib\site-packages\jsonschema\validators.py", line 893, in validate
    cls = validator_for(schema)
  File "C:\work\test\env\lib\site-packages\jsonschema\validators.py", line 925, in validator_for
    if schema[u"$schema"] not in meta_schemas:
TypeError: string indices must be integers
```

**Comment by Julian** [comment]
Your schema is a string.

**Comment by RichardCullen** [comment]
Thank you - json.loads(schema_string) - now it works!

**Comment by reitzig** [comment]
Type annotations and/or parameter doc would help avoiding this mistake.
