### ISSUE TITLE
jsonschema 3 incompatibility with OpenStack

### ISSUE THREAD

**Issue by jayvdb** [Julian/jsonschema#604]
I am surprised there isnt an issue about this.

A lot of the openstack projects have had pins like `jsonschema<3.0.0,>=2.6.0` for quite a long time.

This is blocking some distros (at least openSUSE) from moving to jsonschema 3.x , as they dont want to break openstack.  Which means they can also have all the new software which is now using features only in jsonschema 3.x .

I see there is movement on this front on the openstack side, e.g.
e.g. https://opendev.org/openstack/zaqar/commit/1af2c91e41b147f95082b68e3ec9df95ab458fb2

I have also run the `glance_store` unit tests with jsonschema 3.latest and those tests pass.

But the supported version of openstack (codenamed Stein) still has the pin, and will likely continue to be supported for a while.

Is there anything that can be done on the jsonschema side to reduce the incompatibilities with jsonschema 2.6.  Perhaps a shim can be created, or an upgrading guide (if one doesnt exist).

**Comment by Julian** [comment]
Hi.

I'm not sure what there is to do here really in this library -- especially if as you say, you tried it on some OpenStack thing and the tests all pass. Sounds like OpenStack just needs some PRs bumping the dep in all the repos.

The only real breaking change that tends to cause a major version bump and not the normal deprecation cycle is changing what draft is used by default -- as new drafts are released, there's a new `jsonschema` release with breaking change to use the newest draft by default.

Specifically, 3.x uses draft 7, the latest draft released at the time (and at the minute, until draft 8 is released, at which point `jsonschema` 4 will likely also be released).

So as long as schemas are specified properly (i.e. they contain `"$schema"` properties declaring them as whatever draft they use, there's typically no work in upgrading.

**Comment by jayvdb** [comment]
Would it be possible to have an envvar to override which draft is used by default?

**Comment by Julian** [comment]
What problem would we be trying to solve, is it something related to this? It's trivial to specify either what draft you want to run, either in the schema, which everyone should be doing anyhow, or in any of the places you do validation, so yeah, what would be the goal of an envvar?

**Comment by jayvdb** [comment]
While it might be easy to update the code, or the data, OpenStack has lots of separate sub-projects using jsonschema, with different development teams, different roadmaps, etc.  One project has done the changes needed, but most have not.  It likely is not a high priority for them.  If it involves altering the data interchange between their services, I can see why they would be reluctant to tackle the change - it is easier to pin `jsonschema`.   Those changes will take a long time to work their way through the development processes, and would only reach users in a future release, when all components have been fixed.  OpenStack is a slow moving beast with long support windows, so even the latest version Stein is supported until October 2020.  https://releases.openstack.org/  Quite possibly the next release due around October 2019 wont be jsonschema v3 ready.

If there is an envvar which can be set by the top level apps in OpenStack, even if they have no direct dependency on jsonschema, they might be able to get QA passing with jsonschema v3 sooner.

**Comment by Julian** [comment]
So, I should have asked this to start but are you part of OpenStack and this is a reason why it hasn't moved over to 3 (the lack of a way to change the default externally) or are you speculating about reasons there on their behalf?

(And in case I didn't say it initially, thanks certainly for flagging this, but yeah I want to understand what issues they're running into)

**Comment by jayvdb** [comment]
I am not part of OpenStack.  I have a few very minor contribs to their devops repos from years ago.  However OpenStack is used by several orgs I've been involved with, so I have a bit of familiarity as a user.  I am only guessing about future work they might do, or ways to help them, but their support of already released versions, which have a `<3` pin, is an ongoing problem which isnt speculation.

I am also not part of openSUSE; again just a user, and I am trying to get poetry into their core package collection, but that breaks because the openSUSE maintainers have so far chosen to keep jsonschema pinned to `<3` soas to not break OpenStack.  I've submitted an update request again yesterday; see https://build.opensuse.org/request/show/731508 for developments on that front.

I have most of the OpenStack jsonschema related projects in a build project at https://build.opensuse.org/project/show/home:jayvdb:jsonschema , and a bunch of other 'prominent' packages using jsonschema , so I could play around with those builds in order to try to get them all green.  Let me know if there are any other important packages which I should add to that build project to test compatibility with jsonschema v3.

I could patch the jsonschema in that build project to change the defaults, or add an envvar, to see if that is enough to get them green.

**Comment by Julian** [comment]
Will respond in more detail (apologies, I've been at a conference), but thanks that's helpful -- I'm not keen to add an envvar (the short version being simply that it's global mutable state that things can fight over), but I do respect thinking about the problem so not saying there's nothing to do.

Thanks a ton for filing the OpenSUSE issue at very least, will track that -- and if you do see anything fail a build definitely keen to see why, like I said, very little's changed.

Will keep this open and yeah probably come back to add a bit more detail after I review the two links you posted, so thanks again!

**Comment by Julian** [comment]
@handrews @relequestual I still haven't even done so myself but might be interesting to you to flip through the failing builds too, since like I mentioned, they likely represent the fraction of downstream schema users that do not declare $schema in their usages.

**Comment by Julian** [comment]
@jayvdb I haven't gotten a ton more time to flip through these, but it seems likely we need a baseline run that uses 2.6.0 to compare to, because out of the first 5 project failures, most of them look pretty suspicious (unlikely to be jsonschema related)...

Not sure if that's something you've looked at already.

**Comment by jayvdb** [comment]
Ya, good idea.  I'll set it up

**Comment by Julian** [comment]
Hi -- not sure if there is any movement here -- going to close this since I still don't know that there's anything to do here within `jsonschema`, but happy to continue the discussion if need be.

**Comment by jayvdb** [comment]
No worries.  Sorry I havent had time to get back to this.
