### ISSUE TITLE
Required properties

### ISSUE THREAD

**Issue by mlabarre** [Julian/jsonschema#605]
Hello
First, very very great job. Bravo.
A simple question : is possible with the actual code to require a property if another property is not set?
Thank you very much

**Comment by Julian** [comment]
Hi. Thanks.

There's a few ways to do this in JSON Schema (the specification this
library implements).

oneOf, dependencies, not, if/then/else, and/or some combination of those
are what you want essentially.

**Comment by Julian** [comment]
Hopefully that helped, but if not feel free to follow up, ideally on e.g. the JSON Schema slack channel, so that we can reserve the bug tracker for issues.
