### ISSUE TITLE
Return True if Validator.check_schema does not raise exception.

### ISSUE THREAD

**Issue by suguru-yazawa** [Julian/jsonschema#606]
Hi.

Currently, [Validator.check_schema](https://github.com/Julian/jsonschema/blob/master/jsonschema/validators.py#L292) doesn't explicitly return True.
It would be easy to test the schema if returns True.

`before`
```
@classmethod
def check_schema(cls, schema):
    for error in cls(cls.META_SCHEMA).iter_errors(schema):
        raise exceptions.SchemaError.create_from(error)
```

↓

`after`
```
@classmethod
def check_schema(cls, schema):
    for error in cls(cls.META_SCHEMA).iter_errors(schema):
        raise exceptions.SchemaError.create_from(error)
    return True
```

Thanks.

**Comment by Julian** [comment]
Hi. Thanks.

This is intentional, and works the same way `Validator.iter_errors` does. The
intended usage isn't `if validator.check_schema(whatever): do_stuff`, it's just
`validator.check_schema(whatever); do_stuff`. There isn't much benefit in
returning the boolean.
