### ISSUE TITLE
Support for ECMA 262 regex patterns

### ISSUE THREAD

**Issue by Zac-HD** [Julian/jsonschema#607]
The value of [the `pattern`] keyword [SHOULD be a valid regular expression](https://json-schema.org/latest/json-schema-validation.html#pattern), according to the ECMA 262 regular expression dialect.  However [sticking to a common subset of the syntax is recommended](https://json-schema.org/understanding-json-schema/reference/regular_expressions.html).

I spent the weekend doing some research on the differences between Python and JS regex, and seeing how difficult it might be to patch over them.  In short: https://pypi.org/project/js-regex/ now exists. (🎉)

It currently supports Python 3.6+ only, but solely because that's a much nicer way to develop a new project - if you were willing to use it in `jsonschema` I'd be happy to make a back-compatible release to support Pythons 2.7 and 3.5.

**Comment by Julian** [comment]
Awesome, well done as usual.

Yeah definitely would love to use this if you can support all the versions we do here.

**Comment by Greg7000** [comment]
Note that the following is coming:

[Format-Specific Notes
regex
The JSON Schema specification [recommends (but does not require)](https://json-schema.org/draft/2020-12/json-schema-core.html#name-regular-expressions) that implementations use ECMA 262 regular expressions.

Given that there is no current library in Python capable of supporting the ECMA 262 dialect, the regex format will instead validate Python regular expressions, which are the ones used by this implementation for other keywords like [pattern](https://json-schema.org/draft/2020-12/json-schema-validation.html#section-6.3.3) or [patternProperties](https://json-schema.org/draft/2020-12/json-schema-core.html#section-10.3.2.2).
](https://python-jsonschema.readthedocs.io/en/latest/validate/#format-specific-notes)
