### ISSUE TITLE
3.1.0 Release fails to validate strings via regex

### ISSUE THREAD

**Issue by amisevsk** [Julian/jsonschema#612]
A CI build of ours pulled the new release (3.1.0) and all validation is failing with messages like
```
u'go' does not match u'^[^\\s]+$'
```
Building with `<3.1.0` does not have this issue.

Reproducer:

test.json:
```json
{
  "test": "testString"
}
```

schema.json;
```json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Reproducer",
  "type": "object",
  "properties": {
    "test": {
      "type": "string",
      "pattern": "^[^\\s]+$"
    }
  }
}
```

dockerfile (or just install 3.1.0 locally)
```dockerfile
FROM alpine:3.10
RUN apk add --no-cache py-pip jq && pip install jsonschema

COPY . /build
RUN jsonschema --version
RUN jsonschema /build/schema.json -i /build/test.json
```

**Comment by Julian** [comment]
Having a look...

**Comment by amisevsk** [comment]
Thanks @Julian, from a somewhat hasty check, looks to be related to character classes (`"^[^ \t]+$"` does not have the issue)

**Comment by dslagle** [comment]
This appears to be related to the switch to js_schema. Specifically in relation to character classes where something like `[\w0-9]` gets translated to `[[a-zA-Z]0-9]` inside js_schema. At least that's what happened in my case.

**Comment by Julian** [comment]
OK, given that there's 2 separate issues here (#612 and #611) and that this is fairly fundamental functionality, I've temporarily pushed out v3.1.1 reverting the switchover.

We'll add some tests for the two cases here (and anything else we missed), and then there likely will be a v3.1.2 that goes back again to js-regex again.

**Comment by Zac-HD** [comment]
> This appears to be related to the switch to `js_regex`. Specifically in relation to character classes where something like `[\w0-9]` gets translated to `[[a-zA-Z]0-9]` inside `js_regex`.

Yep, that's a bug in `js-regex`.  Sorry for the trouble this has caused everyone 😕

**Comment by amisevsk** [comment]
Thanks all, FWIW I re-read the jsonschema draft docs and it *does* suggest not using anything outside of pretty limited range of the regex spec, so my issues are partly my own doing ;)

**Comment by tschmidtb51** [comment]
@Julian: What is the current status on that issue? Does jsonschema still use `js_regex`?

**Comment by Julian** [comment]
No, newer releases are not using js-regex. We still may explore JS regexes in the future, but yeah this issue shouldn't be present.

**Comment by tschmidtb51** [comment]
The problem that `js_regex` tried to solve is still there?

> Did you know that regular expressions may vary between programming languages? For example, let's consider the pattern "^abc$", which matches the string "abc". But what about the string "abc\n"? It's also matched in Python, but not in Javascript!

**Comment by Julian** [comment]
Yes, today we support only Python regular expressions.

**Comment by tschmidtb51** [comment]
Thanks for clarifying.
