### ISSUE TITLE
Generate JSON Skeleton from JSON Schema

### ISSUE THREAD

**Issue by micromad** [Julian/jsonschema#615]
I like your package but I would like to know if it's possible to add the function to generate a JSON skeleton based on the JSON schema.

I must generate many JSON files according to a schema and currently I must write a driver to write these files including the skeleton I've defined in the schema.

By this way I create correlation between schema and the main code, so if I modify One, I should modify the other....

This functionnality could be usefull !!!

Regards

**Comment by Julian** [comment]
Hi. Is JSON Skeleton a specific thing you're referring to? Or are you asking about generating valid JSON instances from a schema.

The latter is certainly useful functionality, though out of scope for this library, which is just about implementing the specification.

Something like [hypothesis-jsonschema](https://pypi.org/project/hypothesis-jsonschema/) though can be used to generate valid instances.

**Comment by Julian** [comment]
Closing this for cleanliness, but happy to hear your thoughts.
