### ISSUE TITLE
transient dependency on more-itertools breaks python 2

### ISSUE THREAD

**Issue by yogeshgstarsky** [Julian/jsonschema#617]
more itertools does not support python2 (not even python3.4)
https://github.com/erikrose/more-itertools/blob/master/tox.ini

**Comment by Julian** [comment]
All the tests are passing, including on 2.7 -- can you elaborate on what you see is broken?

**Comment by Julian** [comment]
Going to close this since I don't actually think anything is broken here? But if you do have something concrete, happy to have a look.
