### ISSUE TITLE
"Command" has not attribute "Load"

### ISSUE THREAD

**Issue by AwesomeAg1234** [Julian/jsonschema#618]
I am making a Discord bot(which, I know is unrelated to this repository) and I'm using JSON. Whenever I try to run the commands using JSON, however, I keep getting the following error:
`AttributeError: 'Command' object has no attribute 'load'`
This was working just 2 days ago, and the next morning, it suddenly stopped. Here is a snippet of my code(I am using python 3.7.3):
```def checkforprofile(userid):
    with open("gp.json", mode="r") as g:
        gp = json.load(g)
        user = "userid_" + str(userid)
        if user not in gp:
            addprofile(userid);```

**Comment by Julian** [comment]
Hi. Sorry you're having trouble.

Nothing there looks related to this library though. Is there something else you meant to include?
