### ISSUE TITLE
CLI: Show JSON schema parsing errors

### ISSUE THREAD

**Issue by cweiske** [Julian/jsonschema#622]
I am developing a schema from my JSON data files. 
During schema writing, I make mistakes and the schema file itself is not valid JSON and thus cannot be parsed.

jsonschema does not tell me where the problem is but only outputs the following:

```
$ jsonschema -i games/de.eiswuxe.blookid2.json invalid-json-schema.json 
usage: jsonschema [-h] [-i INSTANCES] [-F ERROR_FORMAT] [-V VALIDATOR]
                  [--version]
                  schema
jsonschema: error: argument schema: invalid _json_file value: 'invalid-json-schema.json'
```

It would be nice if `jsonschema` would tell me where my JSON file has a parsing error, instead of just saying "invalid".

Parsing errors should be shown for schema and data file parsing.

**Comment by Julian** [comment]
This is a limitation of `argparse` essentially, but happy to see a PR for this too if you find a way around it.

Otherwise there's plans to eventually rewrite the CLI with click, which makes this a bit easier. Definitely open to help there too.

**Comment by Julian** [comment]
Closing this, but if you're interested in fixing this happy to see a PR. Otherwise yeah, when this moves to click, this will change.
