### ISSUE TITLE
CLI: No error location for error "None: None is not of type 'string'"

### ISSUE THREAD

**Issue by cweiske** [Julian/jsonschema#623]
When jsonschema validates that a given object property is of type "string", and it is `null` in the data, it outputs:

    None: None is not of type 'string'

No more information is shown, especially not the property that failed to validate.

This makes finding the error with large schemas nearly impossible.

# Example
Schema:
```
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "object",
    "properties": {
        "foo": {
            "type": "string"
        }
    }
}
```

Data:
```
{"foo": null}
```

Output:
```
$ jsonschema -i test-data.json test-schema.json 
None: None is not of type 'string'
```

**Comment by Julian** [comment]
Showing something similar to what's shown when `jsonschema` is used normally sounds reasonable, yup.
