### ISSUE TITLE
note on readme and changelog that py2.7 support is dropped

### ISSUE THREAD

**Issue by kapilt** [Julian/jsonschema#626]
looks like starting with 3.1

**Comment by kapilt** [comment]
just noticed this https://github.com/Julian/jsonschema/issues/626

the case we saw this was actually the change to use importlib_metadata which uses more_itertools which dropped 2.7 support earlier this year.

**Comment by kapilt** [comment]
its also unclear if this project is supporting py2.7 why its not in the ci versions being tested.

**Comment by Julian** [comment]
2.7 is supported, and is still tested under CI, and is passing in CI (albeit we only test under PyPy these days, given it's the only Py2.7 that will continue to be supported past December 31).
