### ISSUE TITLE
Validation need to happen properly !!!!

### ISSUE THREAD

**Issue by vvksahoo** [Julian/jsonschema#629]
Validation() is not giving error if i will pass extra parameter in json. it suppose to check whether that extra key is there in schema or not based on that it should through error but unfortunately its not . 

from jsonschema import validate
from jsonschema.exceptions import ValidationError 

schema ={
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "id": {
      "type": "integer"
    },
    "name": {
      "type": "string"
    }
  },
  "required": [
    "id",
    "name"
  ]
}
try:
    var = validate(instance={"name" : "Eggs", "id" : 1,"city":"NY"}, schema=schema)
    print(var)
except ValidationError as e:
       return str(e)

**Comment by Julian** [comment]
Hi.

Please have a read through a [JSON Schema tutorial](https://json-schema.org/understanding-json-schema/reference/object.html#properties), specifically on the validators used for specifying what to do about additional properties.
