### ISSUE TITLE
Warning running pytest when importing jsonschema

### ISSUE THREAD

**Issue by michaelschmit** [Julian/jsonschema#630]
/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/jsonschema/compat.py:6: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
    from collections import MutableMapping, Sequence  # noqa

I'm wondering if jsonschema just needs to update it's reference.

**Comment by Julian** [comment]
What version of jsonschema

**Comment by michaelschmit** [comment]
My bad ... I had some constraints that was keeping me at 2.6.  Upgraded to 3.2 and that fixed it.
