### ISSUE TITLE
Depends on setuptools even after switch to importlib_metadata

### ISSUE THREAD

**Issue by eide** [Julian/jsonschema#631]
In #511 setuptools was added to `install_requires` in `setup.cfg` because it was needed for `pkg_resources` (#510).

In https://github.com/Julian/jsonschema/commit/6a7155a854d57e3f13f9dec15f2ade0820dbca2a `pkg_resources` was replaced with `import_metadata` and `import_metadata` was added as a dependency.

Does this not mean that `setuptools` is no longer a requirement for install?

**Comment by Julian** [comment]
Probably yes!
