### ISSUE TITLE
CLI: error on --validator parameter

### ISSUE THREAD

**Issue by christian-weiss** [Julian/jsonschema#635]
When i call:
`jsonschema -i /data/my.json -V /data/draft03.schema`

then i get:
```
usage: jsonschema [-h] [-i INSTANCES] [-F ERROR_FORMAT] [-V VALIDATOR]
                  [--version]
                  schema
jsonschema: error: argument -V/--validator: invalid _namedAnyWithDefault value: '/data/draft03.schema'
```
But what is wrong with that draft-03 schema file?
(Schema file was copied from: http://json-schema.org/draft-03/schema#; BTW: the file path is correct)

Environment:
Docker Container based on python:3.6.9-alpine
Python: Python 3.6.9
pip: pip 19.3.1 from /usr/local/lib/python3.6/site-packages/pip (python 3.6) 
jsonschema: 3.2.0

**Comment by Julian** [comment]
You're passing a schema as if it were a validator.

**Comment by christian-weiss** [comment]
I did not noticed that i injected the -V on and on. On all my tests. What a fail. Thanks for pointing it out.
