### ISSUE TITLE
make twisted test dep optional

### ISSUE THREAD

**Issue by chutz** [Julian/jsonschema#639]
Would it be possible to make the test dep on twisted optional? I am a packager for a Linux distro, and twisted is quite a large, complicated dependency.

Running the unit tests via `python -m unittest discover` works perfectly without twisted. It appears that it is really just used for the `FilePath` object and `SynchronousTestCase`. These seem pretty minor, and should be relatively easy to change.

**Comment by Julian** [comment]
Hi. You mean for the test suite it sounds like? Twisted isn't a runtime dependency.

I'd hope any Linux distro should have Twisted packaged, it's a fairly important and also old in age library at this point, but I can certainly understand if that isn't the case for a newer distro or something -- but if you want to send a PR changing `FilePath` to use `pathlib(2)` and `SynchronousTestCase` to use some other implementation of `assertWarns` I'm happy to accept that PR, though I can't guarantee that there won't be other dependencies added, including use of other trial features if they turn out to be useful. I *can* say though that the plan is to stay unittest compliant yeah, so you would in theory be mostly safe with just the stdlib unittest runner.

Let me know if so and would be happy to review.

**Comment by Julian** [comment]
Closing this for cleanliness, but happy to review a PR if you're interested in the above.
