### ISSUE TITLE
jsonschema: now available as a dockerized tool for CI / CD

### ISSUE THREAD

**Issue by christian-weiss** [Julian/jsonschema#640]
Hi Julian,

once again i want to thank you for this great validator.

To enable the crowd to easily use jsonschema in CI / CD pipelines i implemented an automated build and release of a docker image, which is available at: https://hub.docker.com/r/freifunkhamm/jsonschema. This docker image is automatically scanned for security vulnerabilities with trivy.

You are warm welcomed to join the release process. If your are interested in it i can grant you direct permissions at https://github.com/Freifunk-Hamm/docker_jsonschema. Just ping me.

Release cycle is very simple:
a) change Dockerfile (new version number)
b) commit and tag commit with version number
c) push
(we use sticky version numbers to have the same result on subsequent build re-runs of the same commit) 

Feel free to link it in your github repo / project website.

Alternative:
If you want to create your own namespace/organisation at DockerHub feel free to grap my code and enable automation in your git repo.

**Comment by Julian** [comment]
Thanks! Will have a look.

**Comment by Julian** [comment]
Still having a look, thanks again for this, but I had a question about the warning you put there:

> Warning: jsonschema is not using the official meta-schema, but patched schema files. If you want to use the official (unpatched) JSON schema meta schemas then you need to cache them. But be warned, the patched jsonschema-version is more closer to the official specs of json schema. We recommend to use the build-in patched meta schemas.

I assume this is related to #641, but what's there to warn about there? The metaschema(s) are non-normative -- what stumbling block exists for someone that the warning is trying to point out? Or put another way, what user would want to do what you mention there (use the "official" meta schema rather than the vendored one)?

**Comment by christian-weiss** [comment]
True, official JSON schema files are not normative. But they are a kind of quasi-standard.

Most tools use the official JSON schema files. It is a surprice if one tool is using not the official schema files (e.g. a patched one). Documentation should warn about such things, that break the Principle of Least Surprise. If  jsonschema would use the official JSON schema by default, and the patched JSON schema only when requested (e.g. with a `--use-improved-schema` or something similar), then it would not violate the Principle of Least Surprise. 

I am open for text contributions.

BTW: I would love to see a PR for patch No1 and patch No2 to the official JSON schema repo, to let other tools also participate in your findings (improved schema; closer to the specs).

**Comment by Julian** [comment]
If the tools you're mentioning are using the official meta schemas and not
applying the behavior dictated by the spec, they have bugs, that's
literally what "non-normative" means.

The principle of least surprise doesn't apply here.

But thanks for clarifying.

**Comment by Julian** [comment]
Had a quick look here -- thanks again for putting this together.

Great to have an image pushed.

I think for now I'll wait to see if there's sufficient demand for this (via people pulling the image) -- if enough people want it I'll ping you about it, but for now seems great to have someone maintaining it already. Thanks!
