### ISSUE TITLE
Validation Error when assigning a floating point number to multipleOf

### ISSUE THREAD

**Issue by balgon** [Julian/jsonschema#648]
If I assign a floating point number to multipleOf, I usually get a Validation Error.

For example, if I validate the following:
````
_schema={
  "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "object",
    "properties": {
      "X": {
        "type": "number",
        "multipleOf": 0.001
      }
    },
    "required": ["X"]
}

jsonschema.validate({"X":5.1}, _schema, format_checker=jsonschema.draft7_format_checker)
````
I get the following Validation Error:

````ValidationError: 5.1 is not a multiple of 0.001

Failed validating 'multipleOf' in schema['properties']['X']:
    {'multipleOf': 0.001, 'type': 'number'}

On instance['X']:
    5.1
````

I think, that this issue is related to the old problem with floating point numbers in python that not all numbers can be represented exactly. 

A posible workaround could be to substitute the following code in _validation.py (line 170):

````
quotient = instance / dB
failed = int(quotient) != quotient
````

with:
````
quotient = instance / dB
failed = abs( quotient - round(quotient) ) > 10**-14 / dB
````

Thanks in advance!

**Comment by Julian** [comment]
Hi -- indeed, floats cannot represent all numbers exactly (in Python or any language with floating points).

If you don't want floating point arithmetic, the actual solution at the minute would be to use whatever type of number you actually want to use, e.g. `decimal.Decimal` (which `jsonschema` already supports validating).

**Comment by Julian** [comment]
I think that should solve your issue, but happy to discuss further if you're having trouble.
