### ISSUE TITLE
Add project LICENSE file

### ISSUE THREAD

**Issue by johnthagen** [Julian/jsonschema#651]
The project currently doesn't have a LICENSE file for contributors or users. Could one be added?

setup.cfg mentions MIT:

https://github.com/Julian/jsonschema/blob/9131e5cdc919899894255a8b5c94d88e4289f51c/setup.cfg#L13

So probably this would be the template to use:

https://opensource.org/licenses/MIT

**Comment by gazpachoking** [comment]
It's there, it's just called COPYING, rather than LICENSE

**Comment by Julian** [comment]
Yep, that. (Thanks both).

**Comment by johnthagen** [comment]
> It's there, it's just called COPYING, rather than LICENSE

Ah, I see. Thanks!
