### ISSUE TITLE
additionalProperties inside else not handled correctly

### ISSUE THREAD

**Issue by Dr-Irv** [Julian/jsonschema#656]
Below, you will see a JSON schema, a python test program, and 4 test files.  The second and 4th files should fail validation.  With jsonschema v3.2, the second one fails, but the 4th one succeeds.

What I'm trying to do is allow JSON that has two properties `selector` and `c` if `selector` is `"a"` and does not allow property `c` if `selector` is not `"a"`

In Visual Studio Code, the 4th one properly fails validation (which is what I expected).  So I think this is a bug here, although maybe the JSON Schema Draft 7 is ambiguous on this point.

File `schema.json`

```json
{
   "$schema": "http://json-schema.org/draft-07/schema",
   "definitions": {
      "baseEntries": {
         "type": "object",
         "properties": {
            "selector": {
               "enum": [
                  "a",
                  "b"
               ]
            }
         },
         "required": [
            "selector"
         ]
      }
   },
   "allOf": [
      {
         "$ref": "#/definitions/baseEntries"
      },
      {
         "if": {
            "properties": {
               "selector": {
                  "const": "a"
               }
            }
         },
         "then": {
            "properties": {
               "c": {
                  "type": "number"
               }
            },
            "required": [
               "c"
            ]
         },
         "else": {
            "$ref": "#/definitions/baseEntries",
            "additionalProperties": false
         }
      }
   ]
}
```

File `testit.py`
```python
from jsonschema import validate
from jsonschema.exceptions import ValidationError
import json

with open("schema.json", "r") as f:
    schema = json.load(f)
for i in range(1, 5):
    fname = "s{}_test.json".format(i)
    with open(fname, "r") as f:
        d = json.load(f)
    try:
        validate(d, schema)
        print("Validation for ", fname, "succeeds")
    except ValidationError as e:
        print("Validation for ", fname, "FAILS")
        print("**Message ", e.message)
```

File `s1_test.json`
```json
{
   "selector": "a",
   "c":  3
}
```

File `s2_test.json`
```json
{
   "selector": "a"
}
```

File `s3_test.json`
```json
{
   "selector": "b"
}
```

File `s4_test.json`
```json
{
   "selector": "b",
   "c": 3
}
```

**Comment by Julian** [comment]
Sounds like a bug in Visual Studio Code -- your `"additionalProperties": false` is ignored in draft 7 since until the 2019-09 draft `$ref` is not allowed to have elements near it.

I didn't debug anything though that's just skimming, so if the above isn't your issue would be great if you tried to minimize your example to the smallest unexpected schema + instance.

**Comment by Dr-Irv** [comment]
> Sounds like a bug in Visual Studio Code -- your `"additionalProperties": false` is ignored in draft 7 since until the 2019-09 draft `$ref` is not allowed to have elements near it.

I don't understand the above sentence, in terms of what is ignored, and what is allowed in draft 7 versus the 2019-09 draft.
> 
> I didn't debug anything though that's just skimming, so if the above isn't your issue would be great if you tried to minimize your example to the smallest unexpected schema + instance.

My real schema is a lot larger, so that was the smallest I could figure out.

Having said all of this, I found another way of solving my issue, so if you want to close the issue, I'd have no qualms about it.

**Comment by Julian** [comment]
> I don't understand the above sentence, in terms of what is ignored, and what is allowed in draft 7 versus the 2019-09 draft.

In Draft 7, `{"$ref": "#/definitions/baseEntries", "additionalProperties": false}` is the same as `{"$ref": "#/definitions/baseEntries"}`, where anything else in there must be ignored, i.e. it's like `additionalProperties: true`.

> Having said all of this, I found another way of solving my issue, so if you want to close the issue, I'd have no qualms about it.

Cool, glad to hear it.
