### ISSUE TITLE
[BUG] False/True instead of false/true in ValidationError

### ISSUE THREAD

**Issue by jaklan** [Julian/jsonschema#660]
When using such a schema:
```
...
"type": "boolean",
"default": false,
"examples": [
    true
]
...
```
and passing some wrong value, e.g. `"some_string"`, an error looks like:
```
jsonschema.exceptions.ValidationError: 'some_string' is not of type 'boolean'

Failed validating 'type' in schema['properties']['something']:
    {'default': False, 'examples': [True], 'type': 'boolean'}
```
It's really misleading, because `True` and `False` are not proper JSON values - they should be lowercased (as they are in the schema, by the way).

**Comment by Julian** [comment]
What you see in tracebacks are Python objects, not JSON.

This is also what you must be validating, since `jsonschema` doesn't actually deal with any JSON whatsoever.

**Comment by jaklan** [comment]
@Julian yep, I know they're Python objects and that's why it can be confusing for people not dealing with JSONs too much - they would expect potential JSON values, not Python ones.

Moreover, I would say backend language of JSON Schema Engine should be transparent, here we're mixing implementation with abstraction. But I see it would need completely different way of dealing with JSONs (be able to parse their raw form), so yeah, it's rather not worth it...

**Comment by Julian** [comment]
I'd hope seeing the same objects that you pass in is the opposite of confusing, but yes either way this would be a huge change.

Thanks though.
