### ISSUE TITLE
ImportError:MetadataPathFinder

### ISSUE THREAD

**Issue by cxapython** [Julian/jsonschema#663]
when i use python3.8,
 "\__version__ = metadata.version("jsonschema")"  raise error,

*** ImportError: cannot import name 'MetadataPathFinder' from 'importlib.metadata' (/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/importlib/metadata/__init__.py)

**Comment by Julian** [comment]
Hi. I'd need to see more details on your setup, how you installed `jsonschema`, and where you got your Python from.

It seems likely it's not a `jsonschema` issue though unfortunately, it's something about your setup.
