### ISSUE TITLE
Adding Conditional schema basis to enum value

### ISSUE THREAD

**Issue by knowBalpreet** [Julian/jsonschema#664]
Hi @Julian , thank you for this amazing library.
I have a use case where I need to add a property in schema based on the value of enum of another property. Please see the below example

`{
  "type": "object",
  "properties": {
    "type": {
      "type": "string",
"enum": ["image", "text"]
    }
  }
}`

Now if incoming value is image I want to add a property `transforms` and i want to validate against
`{
  "type": "object",
  "properties": {
    "width": {
      "type": "integer"
    },
    "height": {
      "type": "integer"
    }
  },
  "required": [
    "width",
    "height"
  ]
}
`

And if the incoming value is text I want to a add a property `transforms` and I want to validate against:
`{
  "type": "object",
  "properties": {
    "font-size": {
      "type": "integer"
    },
    "font-color": {
      "type": "string"
    }
  },
  "required": [
    "font-size",
    "font-color"
  ]
}
`

Please let me know if there is a way to do this?

**Comment by Julian** [comment]
Hi. Thanks, appreciate your compliments!

Could we take this kind of conversation to the JSON Schema slack channel, or StackOverflow, so that the issue tracker can be reserved for issues?

What you're looking for is either `if`, or `oneOf`, but someone in either of those two venues should be able to help out further if needed.

Thanks.

**Comment by knowBalpreet** [comment]
Hi @Julian thank you for such quick revert. I will go ahead and put this question on StackOverflow. Can you direct me to the slack channel? Also does this version support if then in json-schema?

**Comment by Julian** [comment]
https://json-schema.slack.com is the slack and yes it does.

**Comment by knowBalpreet** [comment]
Hey @Julian thank you so much, my query was resolved on slack. However i am stuck on one thing. After validation, I mutate the data to add defaults [if present in json schema]. 
This is my code below 
`def json_schema_validator():
    validator_class = Draft7Validator
    validate_properties = validator_class.VALIDATORS["properties"]
    def set_defaults(validator, properties, instance, schema):
        for property, subschema in properties.items():
            if "default" in subschema:
                instance.setdefault(property, subschema["default"])
        for error in validate_properties(validator, properties, instance, schema):
            yield error
    return validators.extend(validator_class, {"properties": set_defaults})`

Can you please guide me on how to get it to work with if in oneOf property. ?
Thanks in advance

**Comment by knowBalpreet** [comment]
Hey @Julian thank you so much, my query was resolved on slack. However i am stuck on one thing. After validation, I mutate the data to add defaults [if present in json schema].
This is my code below
```
def json_schema_validator():
    validator_class = Draft7Validator
    validate_properties = validator_class.VALIDATORS["properties"]
    def set_defaults(validator, properties, instance, schema):
        for property, subschema in properties.items():
            if "default" in subschema:
                instance.setdefault(property, subschema["default"])
        for error in validate_properties(validator, properties, instance, schema):
            yield error
    return validators.extend(validator_class, {"properties": set_defaults})
```

Can you please guide me on how to get it to work with if in oneOf property. ?
Thanks in advance

**Comment by knowBalpreet** [comment]
@julesjulian Any help on this would be appreciated. Thanks again!
