### ISSUE TITLE
Any string valid uri

### ISSUE THREAD

**Issue by AsierGonzalez** [Julian/jsonschema#665]
It seems that any string is considered a valid uri, is that expected?

```
>>> from jsonschema import validate
>>> schema = {
        "type" : "object",
        "properties" : {
                "price" : {"type" : "number"},
                "name" : {"type" : "string", "format":"uri"}
        }
}
>>> validate(instance={"name" : "Eggs", "price" : 34.99}, schema=schema)
>>> validate(instance={"name" : "////  ", "price" : 34.99}, schema=schema)
>>> validate(instance={"name" : "//// has spaces  ", "price" : 34.99}, schema=schema)
>>> validate(instance={"name" : 1, "price" : 34.99}, schema=schema)
Traceback (most recent call last):
        ...
jsonschema.exceptions.ValidationError: 1 is not of type 'string'
```
From the [tests](https://github.com/Julian/jsonschema/blob/master/json/tests/draft7/optional/format/uri.json#L81-L100) (which I have not tried) it seems that at least some of those should not be invalid.
The most problematic case I have seen is that an empty string also seems to be valid:
```
>>> validate(instance={"name" : "", "price" : 34.99}, schema=schema)

```

**Comment by Julian** [comment]
Hi. Sorry you're having trouble. Please see the [docs on validating formats](https://python-jsonschema.readthedocs.io/en/stable/validate/#validating-formats).

**Comment by AsierGonzalez** [comment]
Thank you @Julian
