### ISSUE TITLE
Unexpected behaviour applying minimum clause to missing property

### ISSUE THREAD

**Issue by alsyia** [Julian/jsonschema#670]
Hi!

I'm seeing a somewhat weird behaviour when I try to apply a conditional minimum clause to a message where the minimum clause subject is missing.

For example: 
```
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
      "amount": {
          "type": "number"
      },
      "sometimesOptional": {
        "type": "string"
      }
  },
  "if": {
      "properties": {
          "amount": {
              "minimum": 1
          }
      }
  },
  "then": {
      "required": ["sometimesOptional"]
  }
}
```

Applying this schema to an empty JSON doc (`{}`) raises the following error:
```
jsonschema.exceptions.ValidationError: 'sometimesOptional' is a required property

Failed validating 'required' in schema['if']['then']:
    {'required': ['sometimesOptional']}

On instance:
    {}
```

Is this expected? It looks like in the absence of `amount` the `if/minimum` clause is considered valid. I checked the spec but could not find anything related to this particular edge case. I'm not sure what the correct behaviour is as I'm not very familiar with JSON schemas. In classic python or javascript testing if `None` or `undefined` was greater than 1 would raise an error... Anyway, I thought I might open an issue to know if it's a bug or just a quirk of schemas :)

As a side note, I think it worked in jsonschema 2.6.0 because I've had issues only since I upgraded to 3.2.0. 

For now, as a fix, I added `"required": ["amount"]` in my if clause so that it's only enforced if the attribute is present.

Looking into the code of 3.2.0 it looks logical at least: the `minimum` validator returns `None` because the attribute is not found and I think the `if` validator checks if there was an error validating the schema so... 

Thank you for your time and this amazing lib! :)

**Comment by Julian** [comment]
Hi!

> Thank you for your time and this amazing lib! :)

Thanks! Glad you like it.

> Is this expected? It looks like in the absence of amount the if/minimum clause is considered valid. I checked the spec but could not find anything related to this particular edge case. 

Yes, both in the current spec and all previous ones. `properties` applies a schema only when a property is present. If it's not present, that doesn't make the schema invalid. Making the property *need* to be present is exactly what `required` is for, as you're using it -- maybe you meant to make `amount` required always?

**Comment by alsyia** [comment]
Thanks for your answer!
I see! I want `sometimesOptional` to be `required` only if `amount` is greather than 1 (which in my mind implied `amount` was there in the first place so I guess adding `required` in my `if` close was the way to go. Except if there is a better way to say "if this field is defined" in a `if` clause?

As a side note, do you know why it worked differently before? The example above was valid in 2.6.0. (I understand it's more like a bug fix though).

**Comment by Julian** [comment]
> As a side note, do you know why it worked differently before? The example above was valid in 2.6.0. (I understand it's more like a bug fix though).

As I mentioned, this *didn't* work differently before -- would have to see specifically what you're referring to to know what you were running -- but also, 2.6.0 was before draft 7 was out, 3.x was the first version to support draft 7 of the spec -- so if you're saying you were running a draft 7 spec on pre-draft 7 validators that may be a reason why it appeared to validate successfully.

Glad you've got it working now though.

**Comment by alsyia** [comment]
Maybe it is, I'm not sure, that's old code. Anyway, the issue was definitely on my side :/

Sorry for that, and thanks for your help!
