### ISSUE TITLE
Add support for uuid4 format

### ISSUE THREAD

**Issue by charlax** [Julian/jsonschema#671]
Hi there,

Would it make sense to add support for the uuid4 format (and the other uuid formats?)

I had to do the following to add it manually:

```python
import re

from jsonschema import (
    validate as jsonschema_validate,
    draft7_format_checker,
)

RE_UUID4 = re.compile(
    "^[a-f0-9]{8}-?[a-f0-9]{4}-?4[a-f0-9]{3}-?[89ab][a-f0-9]{3}-?[a-f0-9]{12}", re.I
)


@draft7_format_checker.checks(format="uuid4", raises=(ValueError,))
def validate_uuid4(value: str) -> bool:
    if not RE_UUID4.match(value):
        raise ValueError(f"'{value}' is not a valid uuid4")
    return True


jsonschema_validate(
    content, schema, format_checker=draft7_format_checker,
)
```

**Comment by Julian** [comment]
Hey!

In general `jsonschema` supports the formats specified by the spec (and not others) -- UUID(4) was added in draft2019-09, which #613 is tracking support for (though it's not sufficiently far along yet).

In the meanwhile what you have looks reasonable if you want to use it for an earlier draft.
