### ISSUE TITLE
Custom FormatChecker

### ISSUE THREAD

**Issue by Sharealikelicence** [Julian/jsonschema#674]
Hi,
Just wondering if there is a way to extend the FormatChecker that is passed to the validator? I can't seem to find anything in the documentation. 
Basically, I am trying to check if a string value is a valid timezone. I'm using pytz for the timezone side. But, I need to check the provided json string property is contained within that list.
The only other way I can think of is to extract the list as an enum field in the schema. But, it's a huge list and seems a pretty clunky way of doing it.
Thanks in advance.

**Comment by Julian** [comment]
Hi. Are you looking for [`FormatChecker.checks`](https://python-jsonschema.readthedocs.io/en/stable/validate/#jsonschema.FormatChecker.checks)?

**Comment by Sharealikelicence** [comment]
I ended up finding it. But, I used cls_checks instead:
```
timezone_checker = FormatChecker.cls_checks(format='timezone', raises=ValueError)
timezone_checker(check_timezone)
```
