### ISSUE TITLE
Making extra messages for error messaging optional

### ISSUE THREAD

**Issue by ethankpow** [Julian/jsonschema#677]
Is there a way to make the extra error messages the _validator yields optional? If not, could it be an enhancement where you pass an "extraErrorMessages" property on the schema that is a boolean? I need to be able to disable that feature because of security issues.

**Comment by Julian** [comment]
Hi. Not sure I know what you mean here unfortunately.

Which extra messages are you referring to (and what do you mean by security issues)?

Perhaps sharing what code you're running would be helpful too.

**Comment by Julian** [comment]
Happy to discuss further if you can clarify!
