### ISSUE TITLE
`[[False], [0]]` should be considered unique

### ISSUE THREAD

**Issue by Zac-HD** [Julian/jsonschema#686]
```python
jsonschema.validate([[False], [0]], {'type': 'array', 'uniqueItems': True})
```

fails, though the inner lists should be considered distinct due to the different types of their values.  (though all numbers are considered the same type, so `[[0], [0.0]]` should and does fail to validate)

This should probably go in the upstream test suite as well.  Checked on version 3.2.0.

(sorry for the short report, found this just as I was heading to bed)

**Comment by Julian** [comment]
Closed (by @nezhar, thanks!) in 7b9b5c3.
