### ISSUE TITLE
Update or remove outdated benchmark instructions from README.rst.

### ISSUE THREAD

**Issue by jdmoorman** [Julian/jsonschema#689]
The **Benchmarks** section of `README.rst` suggests using this command to run the benchmarks manually (i.e. without tox):
```bash
$ python -m pyperf jsonschema/benchmarks/test_suite.py --hist --output results.json
```

However, this command fails with version 2.0.0 of pyperf:
```text
$ python -m pyperf jsonschema/benchmarks/test_suite.py --hist --output results.json
usage: -m pyperf [-h] {show,hist,compare_to,stats,metadata,check,collect_metadata,timeit,system,convert,dump,slowest,command} ...
-m pyperf: error: argument action: invalid choice: 'jsonschema/benchmarks/test_suite.py' (choose from 'show', 'hist', 'compare_to', 'stats', 'metadata', 'check', 'collect_metadata', 'timeit', 'system', 'convert', 'dump', 'slowest', 'command')
```
Additionally, there is no such file `jsonschema/benchmarks/test_suite.py`.

Having a look at `tox.ini`, I see that the commands used to run pyperf are actually
```text
    perf: mkdir {envtmpdir}/benchmarks/
    perf: {envpython} {toxinidir}/jsonschema/benchmarks/issue232.py --inherit-environ JSON_SCHEMA_TEST_SUITE --output {envtmpdir}/benchmarks/issue232.json
    perf: {envpython} {toxinidir}/jsonschema/benchmarks/json_schema_test_suite.py --inherit-environ JSON_SCHEMA_TEST_SUITE --output {envtmpdir}/benchmarks/json_schema_test_suite.json
```
which suggests the correct commands for running the benchmarks manually would be
```bash
$ python jsonschema/benchmarks/issue232.py --inherit-environ JSON_SCHEMA_TEST_SUITE --output issue232_results.json
$ python jsonschema/benchmarks/json_schema_test_suite.py --inherit-environ JSON_SCHEMA_TEST_SUITE --output json_schema_test_suite_results.json
```

**Comment by Julian** [comment]
Fun -- yeah possibly just easiest to only give the option to run them via tox and not try and leak too many implementation details. Happy to see a PR for that if you're up for it.

**Comment by jdmoorman** [comment]
I've opened #690 which removes the instructions for running tests manually. I'm not sure what to do about the remaining instructions for comparing results between different runs of the benchmarks, since `tox -e perf` stores those results in `{envtmpdir}/benchmarks/issue232.json` and `{envtmpdir}/benchmarks/json_schema_test_suite.json`.

**Comment by Julian** [comment]
Probably for that piece we just leave it out for now, I meant to go back and implement that possibility but we can just treat that as a feature request same as any other and hit it whenever someone feels it's important enough to make easy. Will have a look at your PR, thanks!
