### ISSUE TITLE
[question] when type is object and no properties field, the result has  no error message.

### ISSUE THREAD

**Issue by willson-chen** [Julian/jsonschema#700]
There is no error message when schema type is `object` without `properties` filed, which is a required filed.

Here is the example code:
```
from unittest import TestCase
from jsonschema.validators import Draft7Validator, exceptions

class TestBestMatch(TestCase):
   def test_xxx(self, false=None):
       schema={
           "$schema": "http://json-schema.org/schema#",
           "type": "object",
           "name": {"type": "string"},
           "foo": {"type": "string"}
       }

       doc={
           "name": 3,
           "foo": 2
       }

       validator = Draft7Validator(schema)
       print(exceptions.best_match(validator.iter_errors(doc)))
```

Is it more reasonable to throw an error message?

**Comment by Julian** [comment]
Hi. Thanks. This is the behavior mandated by the spec, for better or worse.

The spec says unknown validation keywords are to be ignored. `name` and `foo` are, as far as `jsonschema` can know, just such unknown validation keywords that may be being used for some other purpose.
