### ISSUE TITLE
multipleOf validation throws DivisionImpossible error for Decimal class, if one of the operands is much bigger than the other.

### ISSUE THREAD

**Issue by Fraznist** [Julian/jsonschema#701]
Modulo operation between two instances of `decimal.Decimal` classes can throw an `decimal.InvalidOperation: [<class 'decimal.DivisionImpossible'>]` error if the bigger operand is 28 orders of magnitudes bigger than the other (for `a % b` we get an error if a > b * 10^28). [Relevant stackoverflow thread](https://stackoverflow.com/questions/42868278/decimal-invalidoperation-divisionimpossible-for-very-large-numbers).

I believe this exception should be caught and tried again with a better precision value. I understand that `decimal.Decimal` isn't used by `json.load`. Still, `decimal.Decimal` is being heavily used by [Singer](https://github.com/singer-io/getting-started) taps and targets for some reason.

**Comment by Julian** [comment]
That's something that should be done outside `jsonschema` -- as you say, `jsonschema` doesn't deserialize things. It supports `Decimal`s if they've been loaded properly, but it's up to you to set their precision to what you need them to be *before* handing them to validation, `jsonschema` can't really know what precision is appropriate.
