### ISSUE TITLE
Validation option - spit out warnings if fields in JSON schema not present in JSON

### ISSUE THREAD

**Issue by jvillacis90** [Julian/jsonschema#702]
I don't think the following functionality exists when validating jsons against their json schemas, but the functionality I would like

- I have a json schema with fields X,Y,Z
- my json file contains fields X and Y only
- I run `Draft4Validator(myJson, myResolver)`
- the Validator succeeds, but prints out/returns warning logs saying "myJson does not contain field Y"

I know I could throw in required tag in schema, or I think I could define a custom keyword and create some custom resolver logic, but I'm hoping there is a less verbose method of achieving the above?

```
if jsonField not in jsonSchema.properties:
    log("missing")
```
for example

**Comment by Julian** [comment]
Are you looking for the `required` validator? Or if not, how is what you're looking for different from it?

**Comment by jvillacis90** [comment]
Not the required validator no, for 2 reasons. 
1) it requires specific property fields to be set, example - `'required':'name'`
2) when validating, the required validator throws error

For the case I'm looking for, I want to run validation on json file, and check if there are any fields missing that are in the schema file, and have a soft warning be spit out.

I realize it is a niche case. I managed to achieve what I wanted by extracting keys from both files and doing some comparisons.

Thank you for responding!
