### ISSUE TITLE
`0.0` is not considered an `integer` in draft-04 schemas

### ISSUE THREAD

**Issue by Zac-HD** [Julian/jsonschema#705]
I discovered this oddity working on a `hypothesis-jsonschema` upgrade:

```python
from jsonschema import validate
validate(0.0, {"type": "integer"})  # passes
validate(0.0, {"type": "integer", "$schema": "http://json-schema.org/draft-04/schema#"})  # fails
```

The first behaviour is correct, because the `"integer"` 'type' is defined by having a zero fractional part, rather than by the Python `type` of the value.  (a surprise which my planned feature will introduce to users...)

**Comment by Julian** [comment]
Hi hi!

The zero fractional part was new in draft 6 (or 7, I forget). In draft 4, using the language-level type was the expected behavior.

**Comment by willson-chen** [comment]
> ```
> from jsonschema import validate
> validate(0.0, {"type": "integer"})  # passes
> validate(0.0, {"type": "integer", "$schema": "http://json-schema.org/draft-04/schema#"})  # fails
> ```

About `validate` function, when no schema is passed in, the latest validator ` Draft7Validator`  is used for verification by default, and if a schema is passed in, the incoming validator `Draft3Validator` `Draft4Validator` `Draft6Validator` or `Draft7Validator` is used for verification.
In `jsonschema\_types.py`: 
```
draft4_type_checker = draft3_type_checker.remove(u"any")
draft6_type_checker = draft4_type_checker.redefine(
    u"integer",
    lambda checker, instance: (
        is_integer(checker, instance) or
        isinstance(instance, float) and instance.is_integer()
    ),
)
draft7_type_checker = draft6_type_checker
```






The float in the type_checker of `draft6` and `draft7` have been redefined integer, while `draft3` and `draft4` haven't been redefined. So your code above, the first  behaviour was correct, the second failed.

**Comment by Zac-HD** [comment]
Huh, https://json-schema.org/draft-06/json-schema-release-notes.html#q-what-are-the-changes-between-draft-04-and-draft-06 does indeed note this change.

I'd only looked at https://tools.ietf.org/html/draft-zyp-json-schema-04#section-5.5 vs https://tools.ietf.org/html/draft-handrews-json-schema-02#section-6.3, which as the changelog notes both say that integer-valued numbers SHOULD be encoded without fractional part, i.e. libraries had better support both :roll_eyes: 

So I guess I either have to abandon this "helpful feature", or track the schema version down into subschemas...

Anyway, thanks heaps for your quick response, and thanks again for the wonderful library :heart:

**Comment by Julian** [comment]
> So I guess I either have to abandon this "helpful feature", or track the schema version down into subschemas...

Yeah you can imagine implementing it was similarly fun :D, might as well share the pain with downstream folks too hooray!

> Anyway, thanks heaps for your quick response, and thanks again for the wonderful library ❤️

Of course, and thanks for being great!
