### ISSUE TITLE
unresolvable pointer: #/definitions not resolved

### ISSUE THREAD

**Issue by Janluak** [Julian/jsonschema#711]
Hey,

I was trying to skip the checking of the schema itself and for some reason the in-file pointing doesn't seem to work.

Attached are a schema, test_data to verify and a small, rudimentarily script.

The most relevant code looks like this:
```
class Validator:
    ...
    
    def _file_resolver(self):
        absolute_directory = dirname(realpath(self.file))
        relative_directory = f"file://{absolute_directory}/"
        self.__resolver = RefResolver(relative_directory, None)

    def _create_validator(self):
        self._file_resolver()

        self._validator = Draft7Validator(self.raw_schema, resolver=self.__resolver)

    def validate(self, d):
        self._validator.validate(d)

Validator(file=schema_file).validate(data)
```

Error message shows `jsonschema.exceptions.RefResolutionError: Unresolvable JSON pointer: 'definitions/schemas/properties/origin'`.

Do you have any idea why the pointer isn't getting resolved?
The schema itself is correct and if running `jsonschema.validate(schema=schema, instance=data)` there seems to be no issue with it.

Thanks for your support!
J

### data.json
```
{
  "KEY1": "value1",
  "KEY2": {
    "ORIGIN": "file"
  }
}
```
### schema.json
```
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "some test schema",
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "KEY1": {
      "description": "",
      "type": "string"
    },
    "KEY2": {
      "description": "",
      "type": "object",
      "properties": {
        "ORIGIN": {
          "$ref": "#/definitions/schemas/properties/origin"
        }
      }
    }
  },
  "definitions": {
   "schemas": {
     "type": "object",
      "properties": {
        "origin": {
          "type": "string",
          "enum": [
            "file",
            "url",
            "raw"
          ]
        }

      }
   }
  }
}
```

### simple_schema_checking.py
```
from jsonschema.validators import Draft7Validator, RefResolver
from os.path import dirname, realpath
from json import load


class Validator:
    def __init__(self, file):
        self.file = file
        self.schema = dict()

        self._load_schema()
        self._create_validator()

    def _load_schema(self):
        with open(self.file, "r") as fs:
            self.raw_schema = load(fs)

    def _file_resolver(self):
        absolute_directory = dirname(realpath(self.file))
        relative_directory = f"file://{absolute_directory}/"
        self.__resolver = RefResolver(relative_directory, None)

    def _create_validator(self):
        self._file_resolver()

        self._validator = Draft7Validator(self.raw_schema, resolver=self.__resolver)

    def validate(self, d):
        self._validator.validate(d)


if __name__ == "__main__":
    schema_file = "schema.json"
    data_file = "data.json"

    with open(schema_file, "r") as f:
        schema = load(f)

    with open(data_file, "r") as fd:
        data = load(fd)

    import jsonschema

    jsonschema.validate(schema=schema, instance=data)

    Validator(file=schema_file).validate(data)

```
### zip of all files
[errorful_json_checking.zip](https://github.com/Julian/jsonschema/files/4975330/errorful_json_checking.zip)

**Comment by Julian** [comment]
Hi there, sorry you're having trouble.

If you can reduce this to a [minimal example](http://sscce.org/) I'm happy to take a look, especially if you first look at the existing issues (there are a few existing known issues around `$ref`).

Otherwise much as I'd love to help, and don't want to be rude, but it's unlikely I'll be able to spend the time to reduce the example myself, there are as I say a few existing ones already that could use diagnosis and may represent the same underlying minimal example.

**Comment by willson-chen** [comment]
@Julian @Janluak 
This is a simplified example where ref is the correct definition. If ref is changed to "#/definitions/schemas", the problem occurs.

schema.json:
```
{
  "type": "object",
  "properties": {
      "KEY1": {
          "type": "object",
          "properties": {
              "ORIGIN": {
                  "$ref": "schema.json#/definitions/schemas"
              }
          }
      }
  },
  "definitions": {
      "schemas": {
          "type": "string"
      }
  }
}
```
simple_schema_checking.py:
```
with open("./schema.json") as file:
    schema = json.load(file)

path = "file://{}/".format(os.path.abspath("."))
res =  jsonschema.RefResolver(path, None)

vali_data = {
    "KEY1": {
        "ORIGIN": "file"
    }
}

jsonschema.validate(vali_data, schema=schema,  resolver=res)

```

**Comment by Janluak** [comment]
@willson-chen I am not 100% getting why you referenced the file to itself again, this gives me a different bug: `jsonschema.exceptions.RefResolutionError: unknown url type: 'schema.json'`

@Julian totally get your point. Was already downsizing the hole class to a minimal limit but it's not even relevant, please check this code. It's giving the same error and is only 3 lines:

```
resolver = RefResolver(f"file://{dirname(realpath(schema_file))}/", None)
validator = Draft7Validator(schema, resolver=resolver)
validator.validate(data)
```

(only for reference the hole python file with loading the data:)
```
from jsonschema.validators import Draft7Validator, RefResolver
from os.path import dirname, realpath
from json import load
import jsonschema

schema_file = "schema.json"
data_file = "data.json"

with open(schema_file, "r") as fs:
    schema = load(fs)

with open(data_file, "r") as fd:
    data = load(fd)

# working with schema check forehand
jsonschema.validate(schema=schema, instance=data)

# not working with skipping schema check
resolver = RefResolver(f"file://{dirname(realpath(schema_file))}/", None)
validator = Draft7Validator(schema, resolver=resolver)
validator.validate(data)
```

**Comment by willson-chen** [comment]
@Janluak 
The problem can be solved by modifying the following two parts:
```
schema.json:
Change "$ref": "#/definitions/schemas" to "$ref": "schema.json#/definitions/schemas"
```
```
Change  "resolver = RefResolver(f"file://{dirname(realpath(schema_file))}/", None)" to 
"resolver = RefResolver(f"file://{dirname(realpath(.))}/", None)"

```

**Comment by Janluak** [comment]
@willson-chen this doesn't seem to work for me:
This line `resolver = RefResolver(f"file://{dirname(realpath(.))}/", None)` returns an syntax error.

Adaptions to 
`resolver = RefResolver(f"file://{dirname(realpath('.'))}/", None)`
or
`resolver = RefResolver(f"file://{dirname(realpath('./'))}/", None)` 
are only bringing this exception: `jsonschema.exceptions.RefResolutionError: unknown url type: 'schema.json'`

Do you have any idea?

**Comment by Julian** [comment]
@Janluak thanks, that's obviously an improvement, but can you also minimize your schema and data, including inlining them? The goal should be the shortest self contained example of your issue.

**Comment by Janluak** [comment]
@Julian I reduced the schema and data a little more and inlined it.
The issue arises if using the RefResolver and having a reference to within the schema (no pointing to files or urls etc.):

```
from jsonschema.validators import Draft7Validator, RefResolver
from os.path import dirname, realpath
import jsonschema

schema_file = "schema.json"

schema = {
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "object",
    "properties": {
        "KEY1": {
            "description": "",
            "type": "object",
            "properties": {"KEY2": {"$ref": "#/definitions/schemas/referring"}},
        }
    },
    "definitions": {"schemas": {"referring": {"type": "string"}}},
}


data = {"KEY1": {"KEY2": "some_string"}}


# working: schema check forehand
jsonschema.validate(schema=schema, instance=data)

# working: skipping schema check without RefResolver
validator = Draft7Validator(schema)
validator.validate(data)

# not working: skipping schema check with RefResolver
resolver = RefResolver(f"file://{dirname(realpath(schema_file))}/", None)
validator = Draft7Validator(schema, resolver=resolver)
validator.validate(data)
```

**Comment by willson-chen** [comment]
@Janluak This is a very simple test case, you can run it directly, and hope to solve your problem。

[example_711.zip](https://github.com/Julian/jsonschema/files/4985391/example_711.zip)

**Comment by Janluak** [comment]
@willson-chen thanks for your code. This definitely helped me to get it working.

Unfortunately, the pointing from one schema to another is now based on the python execution path and not based on the direction of the schema. Loading the schema from different python execution paths get's very tricky...
Using os.chdir to switch paths for resolving is a workaround but not a very nice though...
Do you have a quick fix for that, too?
[follow_up_error.zip](https://github.com/Julian/jsonschema/files/4996528/follow_up_error.zip)

**Comment by willson-chen** [comment]
@Janluak Just modify the code below：
```
path = prefiefile.format(os.path.abspath("."))
```
Change to:
path = prefiefile.format(os.path.abspath("./schema_directory")
```
```

**Comment by Janluak** [comment]
@willson-chen ah thanks, this resolves the issue.

```RefResolver(f"file://{os.path.dirname(os.path.realpath(schema_file))", None)``` 
to
```RefResolver(f"file://{os.path.dirname(os.path.abspath(schema_file))", None)```

`realpath → abspath`

**Comment by reitzig** [comment]
Whoa, this took some googling. I was quite surprised to find that a plain local file `$ref` doesn't Just Work(TM)!

Anyway, FWIW: if you use `pathlib`, this works:

```python
# schema: Path
ref_resolver = jsonschema.RefResolver(f"file://{schema.absolute()}", None)
```

**Comment by reitzig** [comment]
What I posted above works for references to _other_ files, but not for the _same_ file. Not only does the resolver break "relative references" to begin with, explicitly adding the (current) file name doesn't help!

For some arcane reason, this works for references to both the same (with filename!) and other files:

```python
jsonschema.RefResolver(f"file://{schema_file.absolute()}/../", None)
```

No variant using `Path.parent` that I tried worked, but adding `/../` does.

:shrug: 

@Julian , is there a bug there or am I misunderstanding something?

**Comment by Julian** [comment]
Can you put a minimal self-contained example in a new ticket if you think there's a bug somewhere? I can't follow the back and forth.

**Comment by reitzig** [comment]
Done: #915 #916

FWIW and the benefit of googlers, I've now arrived at

```python
ref_resolver = jsonschema.RefResolver(f"{schema_file.parent.absolute().as_uri()}/", None)
```

The major difference to the solution above is that `as_uri()` is platform-independent (think `file://C:/dir/` vs `file:///dir/`).
