### ISSUE TITLE
Validator fails on some cyrillic symbols from UTF-8 file

### ISSUE THREAD

**Issue by Ujifman** [Julian/jsonschema#715]
Command line tool fails to parse json file in UTF-8 with **И** cyrillic symbol
schema:
```
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "type": "object",
    "properties": {
        "some": {
            "type": "object",
            "properties": {
                "target": {
                    "type": "string"
                }
            }
        }
    },
    "required": [
        "some"
    ]
}
```

json_file successfull:
```
{
    "some": {
        "target": "ЙЦЫРВАСРПМДНЛГАОНВРВОЕ"
    }
}
```

json_file failing:
```
{
    "some": {
        "target": "ЙЦЫРВАСРПМДНЛГАОНВРВОЕИ"
    }
}
```
All the problem in **И** symbol. Encoding table fails to recognize because I can't pass `UTF-8` encoding in command line tool using arguments, and it defaults to `cp1251` (I'm not completely sure)
Command line tool answers:
```
 $ jsonschema.exe -i test2.json schema.json
usage: jsonschema.exe [-h] [-i INSTANCES] [-F ERROR_FORMAT] [-V VALIDATOR]
                      [--version]
                      schema
jsonschema.exe: error: argument -i/--instance: invalid _json_file value: 'test2.json'
```
I have two proposals:
* add encoding exception catch to provide meaningfull answer
* add encoding argument to pass file encoding

**Comment by Julian** [comment]
I'm not a Python-on-Windows expert, but I think this is a Python-on-Windows "common" issue, and the solution is normally [set PYTHONUTF8=1 if you're using UTF-8 files on Windows](https://docs.python.org/3/using/windows.html#utf-8-mode), otherwise yes, you will get CP1251.

(I agree on the exception message, but that's fixed already in the next release).

**Comment by Julian** [comment]
Think the above should sort this out, but obviously feel free to follow up.

**Comment by Ujifman** [comment]
> I'm not a Python-on-Windows expert, but I think this is a Python-on-Windows "common" issue, and the solution is normally [set PYTHONUTF8=1 if you're using UTF-8 files on Windows](https://docs.python.org/3/using/windows.html#utf-8-mode), otherwise yes, you will get CP1251.
> 
> (I agree on the exception message, but that's fixed already in the next release).

Yes, I found meaningfull exception in `master` branch
Thank you for advice with PYTHONUTF8
