### ISSUE TITLE
check_schema validation against the schema in which no types are defined.

### ISSUE THREAD

**Issue by d-ojha** [Julian/jsonschema#724]
`{
            "$schema": "https://json-schema.org/draft/2019-09/schema",
            "$id": "https://json-schema.org/draft/2019-09/meta/core",
            "$vocabulary": {
                "https://json-schema.org/draft/2019-09/vocab/core": True
            },
            "$recursiveAnchor": True,

            "title": "Core vocabulary meta-schema",
            "type": ["object", "boolean"],
            "properties": {
                "$id": {
                    "type": "string",
                    "format": "uri-reference",
                    "$comment": "Non-empty fragments not allowed.",
                    "pattern": "^[^#]*#?$"
                },
                "$schema": {
                    "type": "string",
                    "format": "uri"
                },
                "$anchor": {
                    "type": "string",
                    "pattern": "^[A-Za-z][-A-Za-z0-9.:_]*$"
                },
                "$ref": {
                    "type": "string",
                    "format": "uri-reference"
                },
                "$recursiveRef": {
                    "type": "string",
                    "format": "uri-reference"
                },
                "$recursiveAnchor": {
                    "type": "boolean",
                    "default": False
                },
                "$vocabulary": {
                    "type": "object",
                    "propertyNames": {
                        "type": "string",
                        "format": "uri"
                    },
                    "additionalProperties": {
                        "type": "boolean"
                    }
                },
                "$comment": {
                    "type": "string"
                },
                "$defs": {
                    "type": "object",
                    "additionalProperties": { "$recursiveRef": "#" },
                    "default": {}
                }
            }
        }`

Above one is the core schema of jsonschema. And if i need to validate a new json schema against this core schema, but the problem is that it validates even if the schema is different. Not getting the point why and how it is doing it.. The example schema which i checked is given below.

`{ "tech_schema":
{
        "type": "object",
        "properties": {
            "stringProp": {
            "type": "string",
            "title": "Color",
            "description": "This description is used as a help message."
            },
            "stringTextareaProp": {
            "type": "string",
            "title": "Type",
            "x-display": "textarea"
            },
            "integerSliderProp": {
            "type": "integer",
            "title": "Test",
            "x-display": "slider",
            "minimum": 0,
            "maximum": 5
            },
            "booleanProp": {
            "type": "boolean",
            "title": "I'm a boolean"
            },
            "stringEnum": {
            "type": "string",
            "title": "I'm a string with values from an enum",
            "enum": [
                "value 1",
                "value 2"
            ],
            "description": "This description is used as a help message."
            }
        }
       }
     }`

**Comment by Julian** [comment]
Hi. Not sure I follow yet exactly what you're reporting here, but I see the above is a 2019-09 schema, which isn't yet supported by this library.

**Comment by d-ojha** [comment]
Hi.. Thanks a lot for replying. I will try to explain my situation here.. 

I need to validate the json schema given in request for which  previously i used check_schema() validator. But, from my learning i assumed that it should not be validated as "tech_schema" doesnot contain any type or properties. And that why i tried to validate this schema against a meta schema using validate() function. And the validate function also validates the below schema.

Below is the short schema which gets validated, but the outer declarative format contains only key (without Type or properties). 
So is it right to validate that schema by check_schema(). Just need to understand the reason behind it. And how to improve the validation for check_schema() functionality.

` {
        "tech_schema":
        {
        "type": "object",
        "properties": {
            "stringProp": {
            "type": "string",
            "title": "Color",
            "description": "This description is used as a help message."
            },
            "stringTextareaProp": {
            "type": "string",
            "title": "Type",
            "x-display": "textarea"
            },
            "numberProp": {
            "type": "number",
            "title": "Length"
            },
            "integerProp": {
            "type": "integer",
            "title": "Length2"
            }, 
         }  
      }
    }`

**Comment by d-ojha** [comment]
Just need to validate the schema with proper id, type and properties  and without these definition it should reject the schema.

Please suggest me something.

**Comment by Julian** [comment]
Hi @d-ojha -- it sounds like this then is more of a question than a likely bug.

Sorry you're having trouble there -- for questions, there's a JSON Schema slack at https://json-schema.slack.com which as a number of folks who may be able to help you write the schema you're looking for.

StackOverflow is another option there.

I wish I were able to provide direct support but I simply don't have the time to do so unfortunately. You're welcome to try those two places. If it does turn out there's a bug that isn't already known and tracked, feel free to file it here with a simple reproducer.
