### ISSUE TITLE
3.2 of Jsonschema Won't run on Python 3.8.5

### ISSUE THREAD

**Issue by mkkeffeler** [Julian/jsonschema#731]
Had issues getting this version to work with flask on python 3.8.5. We deploy to PCF and as such have to specify versions of our dependencies in requirements.txt. 

Is it expected to not run on Python 3.8.5? Is there a patch fix coming soon? I see active contributions but no release since 2019 on pypi.

**Comment by Julian** [comment]
Hi. Please include code + traceback when filing issues -- yes, `jsonschema` works on 3.8.5 and is tested under it in CI.

**Comment by Julian** [comment]
Sorry, hit the button before finishing the message. But if you're experiencing some issue, I'll need to see more details of what you're running and what you're seeing.
