### ISSUE TITLE
Dependency pyrsistent dropped py2 support in 0.17.0

### ISSUE THREAD

**Issue by wizardfishball** [Julian/jsonschema#732]
Hi there! I'm not sure if jsonschema plans to keep python2 support, but just realized the dependency pyrsistent dropped python 2 support in its 0.17.0 release today.

**Comment by Julian** [comment]
Hi!

The next version of `jsonschema` will be py3-only (though will declare so appropriately via `python_requires`, so nothing in Py2 will break).

The same should be true of `pyrsistent` I hope (that it properly declares `python_version`, so Py2 will still work even if you haven't pinned your dependencies). If that's not the case though definitely worth bringing up there.

**Comment by stas-sbi** [comment]
jsonschema-3.2.0 doesn't work anymore, can we have jsonschema-3.2.x with pyrsistent version restricted to <0.17.0 ?

**Comment by Julian** [comment]
Sounds like the `pyrsistent` release indeed doesn't/didn't include `python_requires`. It's being addressed here though: https://github.com/tobgu/pyrsistent/issues/208.

That's where the fix would go so likely worth following that issue.
