### ISSUE TITLE
pyrsistent requires Python '>=3.5' but the running Python is 2.7.13

### ISSUE THREAD

**Issue by mozgbrasil** [Julian/jsonschema#736]
Hello good afternoon all right

I ran the command

    pip install jsonschema

And is Returned or Error

    Collecting pyrsistent>=0.14.0 (from jsonschema)
    Downloading https://files.pythonhosted.org/packages/7d/ae/90ddcf28fb8eee5d4990920586d2856342e42faa95f39223f0b9762ef264/pyrsistent-0.17.2.tar.gz (106kB)
    pyrsistent requires Python '>=3.5' but the running Python is 2.7.13

can you help me solve the situation

![Captura de tela de 2020-09-10 10-07-18](https://user-images.githubusercontent.com/17202780/92732906-6f168680-f34d-11ea-8d38-0401280fae5a.png)

**Comment by jpatel3** [comment]
How did you resolved it? I see the same issue.
