### ISSUE TITLE
Validation failing wrongly

### ISSUE THREAD

**Issue by vvasuki** [Julian/jsonschema#740]
Tested against jsonschema-3.2.1.dev280+gddcc2e2 .

Reproduce with:
```
jsonschema.validate({'jsonClass': 'JsonObjectNode', 'content': {'jsonClass': 'BookPortion', 'source': {'jsonClass': 'DataSource', 'source_type': 'system_inferred'}, 'title': 'c1', 'authors': [], 'targets': []}, 'children': [{'jsonClass': 'JsonObjectNode', 'content': {'jsonClass': 'BookPortion', 'source': {'jsonClass': 'DataSource', 'source_type': 'system_inferred'}, 'title': 'c1v1', 'authors': [], 'targets': []}, 'children': []}]}, {'properties': {'content': {'type': 'object', 'properties': {'jsonClass': {'type': 'string', 'description': 'A hint used by json libraries to deserialize json data to an object of the appropriate type. This is necessary for sub-objects to have as well (to ensure that the deserialization functions as expected).'}}, 'required': ['jsonClass']}, 'jsonClass': {'enum': ['JsonObjectNode'], 'description': 'A hint used by json libraries to deserialize json data to an object of the appropriate type. This is necessary for sub-objects to have as well (to ensure that the deserialization functions as expected).', 'type': 'string'}, 'children': {'type': 'array', 'items': {'type': 'object', '$ref': 'JsonObjectNode'}}}, 'type': 'object', 'id': 'JsonObjectNode', 'required': ['jsonClass']})
```

The validation ought to work as per https://www.jsonschemavalidator.net/ .

**Comment by Julian** [comment]
Hi there, happy to look at this, but would need you to minimize it to its smallest reproducer, and then to check that that minimal reproducer isn't covered by a previous issue (which I'm happy to point you towards once you manage).

I'd say though something already looks suspicious there -- your schema doesn't declare `$schema` (which is discouraged, but will default to draft 7), but uses `id`, which is not a draft 7 validator (there it's spelled `$id`). I don't know what version that schema is intended to be, but certainly your issue may be related.

Going to close, but after you minimize if you still have doubts on whether this is a new not previously known issue, happy to discuss.

**Comment by vvasuki** [comment]
Thanks for the tip. Adding $id and $schema fixed the problem.

`jsonschema.validate({'properties': {'content': {'type': 'object', 'properties': {'jsonClass': {'type': 'string', 'description': 'A hint used by json libraries to deserialize json data to an object of the appropriate type. This is necessary for sub-objects to have as well (to ensure that the deserialization functions as expected).'}}, 'required': ['jsonClass']}, 'jsonClass': {'enum': ['JsonObjectNode'], 'description': 'A hint used by json libraries to deserialize json data to an object of the appropriate type. This is necessary for sub-objects to have as well (to ensure that the deserialization functions as expected).', 'type': 'string'}, 'children': {'type': 'array', 'items': {'type': 'object', '$ref': 'JsonObjectNode'}}}, 'type': 'object', '$id': 'JsonObjectNode', 'required': ['jsonClass'],  "$schema": "https://json-schema.org/draft/2019-09/schema"}, {'jsonClass': 'JsonObjectNode', 'content': {'jsonClass': 'BookPortion', 'source': {'jsonClass': 'DataSource', 'source_type': 'system_inferred'}, 'title': 'c1', 'authors': [], 'targets': []}, 'children': [{'jsonClass': 'JsonObjectNode', 'content': {'jsonClass': 'BookPortion', 'source': {'jsonClass': 'DataSource', 'source_type': 'system_inferred'}, 'title': 'c1v1', 'authors': [], 'targets': []}, 'children': []}]})`
