### ISSUE TITLE
jsonschema no longer supports Python2.7 (due to dependencies)

### ISSUE THREAD

**Issue by haneefkassam** [Julian/jsonschema#741]
As of September 8, 2020, the jsonschema package no longer supports Python2.7, but not because of code it contributed, but because of a restriction placed on a dependent package (Pyrsistent).  As of the aformentioned date, Pyrsistent no longer supports a Python version < 3.5 ( https://github.com/tobgu/pyrsistent/blob/ccc4a341ea74f80df8487654bfc7c638865867d4/setup.py#L81 ).

This would be fine and dandy, except for the way jsonschema defines dependencies, meaning I could pull an older version of jsonschema, but when it resolves its dependencies, it'll pull the most recent version of Pyrsistent (as seen in the setup.cfg of version as far back as Jan, 2019 - https://github.com/Julian/jsonschema/blob/21838cd7727bd7c1d9a309df51cd32ebb0c78cdb/setup.cfg#L28 ).

I get that Python2.7 is no longer supported, but I would expect older versions that previously worked on Python2.7 to continue to work on Python2.7.

**Comment by Julian** [comment]
Hi! Python 2.7 is very much still supported in 3.2, but this is a pyrsistent bug. See some of the closed issues for a link to the upstream ticket. I think #735 or #734.

**Comment by haneefkassam** [comment]
Any suggestion of a workaround?  Can I force a pyrsistent version for jsonschema dependency?

**Comment by Julian** [comment]
`pip install jsonschema pyrsistent==0.16.0` or thereabouts.

You should always be pinning your dependencies in wherever you're using jsonschema, for exactly this scenario (where a transitive dependency has a bug and forgets to do something or other and it breaks your app)

**Comment by haneefkassam** [comment]
OK, I'll give that a shot.  Thank you!
