### ISSUE TITLE
pyrsistent is dropping support for python 2.x

### ISSUE THREAD

**Issue by GenesisSelf** [Julian/jsonschema#744]
This leads projects using python 2.7 or such to have a dependency break.
See below issue written for pyrsistent:
https://github.com/tobgu/pyrsistent/issues/214

How would jsonschema like to handle this?

Currently you require the below version:
`pyrsistent>=0.14.0`

Can we expect a version of jsonschema that helps support projects using python2.x?

**Comment by Julian** [comment]
Nothing should be required of jsonschema. Any modern pip will only install the newest py2 supporting version.

Have a look at some of the closed duplicates of this if need be.
