### ISSUE TITLE
setup.py is not dead / Add [tool.poetry] to pyproject.toml

### ISSUE THREAD

**Issue by jpmckinney** [Julian/jsonschema#745]
PEP 621 (pyproject.toml)  is still Draft: https://www.python.org/dev/peps/pep-0621/ Anyway...

```
poetry install
```

yields:

```
  PyProjectException

  [tool.poetry] section not found in /Users/james/Sites/remote/miscellaneous/jsonschema/pyproject.toml
```

**Comment by Julian** [comment]
Hi. PEP 518 is the relevant PEP for pyproject.toml. (PEP 621 is a follow up PEP on something not directly relevant)

This project uses setuptools, not poetry, as declared in its pyproject.toml :).

**Comment by jpmckinney** [comment]
In case anyone else is trying to `pip install - e path/to/clone/of/jsonschema`, you can add this `setup.py` file as a shim:

```python
#!/usr/bin/env python

import setuptools

if __name__ == "__main__":
    setuptools.setup()
```

**Comment by Julian** [comment]
Yep, or see https://discuss.python.org/t/pip-19-1-and-installing-in-editable-mode-with-pyproject-toml/1553 for ongoing discussion of how `pip install -e` will eventually support PEP517 (well, really vice versa).
