### ISSUE TITLE
Dependency Problem: pyrsistent dropped python 2 support

### ISSUE THREAD

**Issue by ipichris** [Julian/jsonschema#747]
in setup.cfg the dependency is defined as:
`pyrsistent >= 0.14.0`

Using Python 2.7 i can no longer install jsonschema:
`ERROR: pyrsistent requires Python '>=3.5' but the running Python is 2.7.2`

Suggested Fix:
`pyrisistent >=0.14.0,<0.17`

Workaround:
Install pyrsistent in version 0.16.x before installing jsonschema or any project that uses jsonschema (like i.e. flask-restx)

**Comment by Julian** [comment]
Hello. Please see any of the recent duplicate issues.

(Possibly your pip is very old).

**Comment by ipichris** [comment]
I'm using pip 19.1 so from April 2019

**Comment by Julian** [comment]
yanked releases are supported only in 19.2, so you're getting a version (of `pyrsistent`) that has since been yanked, and which was broken.

**Comment by ipichris** [comment]
Thank you very much!
I didn't realize there are yanked releases and i'm not sure why i got 0.17.2 when 0.17.3 was already released, might be an issue with our Nexus repository (we have the new version in the repo, but it was downloaded two hours after my pip install jsonschema)

Side note: We are currently evaluating poetry instead of pip which has no support of yanked releases yet (https://github.com/python-poetry/poetry/issues/2453), so it might happen more often to users of poetry.

**Comment by ipichris** [comment]
Update:
Nexus currently doesn't support the "yanked" attribute.
So even when using the current pip version you might get a yanked version when using a Nexus repository.
https://issues.sonatype.org/browse/NEXUS-25231

**Comment by ipichris** [comment]
I realize the root cause is not in jsonschema (but invalid pyrsistent releases)
However the invalid versions could probably be excluded by using the version string
pyrsistent >= 0.14.0,!=0.17.0,!=0.17.1,!=0.17.2

The syntax is defined in PEP-440: https://www.python.org/dev/peps/pep-0440/#version-specifiers
(i never used it myself)

**Comment by ipichris** [comment]
I figured out while i got pyrsistent 0.17.2:
The latest pyrsistent version 0.17.3 is not compatible with python 2:
https://pypi.org/project/pyrsistent/0.17.3/
=> Metadata shows "Requires: Python >=3.5"
The earlier version 0.17.0, 0.17.1 and 0.17.2 do require python >=3.5 as well but don't declare it in the Metatdata: https://pypi.org/project/pyrsistent/0.17.2/
=> No mention of any requirements

So to conclude:
1. pyrsistent is incompatible with python 2 from version 0.17.0 onwards
2. pyrsistent 0.17.0, 0.17.1 and 0.17.2 were released without mentioning the python >=3.5 requirement in the metadata of the wheel
3. pyrsistent 0.17.3 has fixed that
4. pyrsistent 0.17.0, 0.17.1 and 0.17.2 have been "yanked" which is a relativly new feature that is not yet widely supported, so you may get these invalid versions despite beeing "yanked"
5. workaround: install pyrsistent==0.16.0 first or if you develop a module declare this dependency in setup.py/requirements.txt/Pipfile depending on your build/deploy/install routine

Sidenote: pip 19.1 is the version delivered with the most recent version of jython (java interpreter for python), upgrading it seems to break it unfortunatly. The latest release of jython is 2.7.2 and there is not yet a jython version based on python 3.x, its still under development.

**Comment by Julian** [comment]
> I realize the root cause is not in jsonschema (but invalid pyrsistent releases)
However the invalid versions could probably be excluded by using the version string
pyrsistent >= 0.14.0,!=0.17.0,!=0.17.1,!=0.17.2

Yes, fine with a PR adding that certainly.

**Comment by linuxholic** [comment]
> Yes, fine with a PR adding that certainly.

this change seems not done yet? do we still need to fix this issue

**Comment by Julian** [comment]
Yes, a PR is still welcome.

**Comment by linuxholic** [comment]
here's my trivial PR https://github.com/Julian/jsonschema/pull/830 🚀
