### ISSUE TITLE
ValidationError __str__ is far too verbose on large objects

### ISSUE THREAD

**Issue by naught101** [Julian/jsonschema#748]
I have some objects that are not particularly complex, but have a large number of elements (a few nested arrays with up to 150 elements at some levels).

If I hit a ValidationError (e.g. during testing), then the error is massive - more lines than my terminal retains. I've never seen such a large error in python, and it makes testing difficult, because I can't see the backtrace.

A few possibilities for solutions:
- Just remove all of the extra information in the [__str__ return](https://github.com/Julian/jsonschema/blob/e48d56cbd2b6c25d4a9483f53f79ec537b9a4a34/jsonschema/exceptions.py#L71). Personally I'd think this was fine - the user can always get the values from `error.schema` and `error.instance`, or
- Truncate the objects - ideally by sub-selecting the elements that are causing the error.
    - Also hard-truncate the string representations of the objects (maybe 100 chars?), and add an ellipsis at the end. This is often still useful information, because if a JSON object has any kind of ID, it will usually be at the top.

Happy to submit a PR for either of these, after your feedback on the ideas.

**Comment by Julian** [comment]
Hi there. This is essentially a dupe of #243, at least https://github.com/Julian/jsonschema/issues/243#issuecomment-125668925

Certainly happy to review a PR that uses `reprlib.repr`.

**Comment by Julian** [comment]
(Error messages already should subselect the relevant portion of an object)

**Comment by naught101** [comment]
Yep, fair enough. Let's close this, and I'll have a proper read over there and see if I can figure out a solution.

**Comment by naught101** [comment]
Yeah, they do sub-select, I was just looking at a top-level error.

**Comment by ablakey** [comment]
For posterity, if anyone wants a short workaround, just catch the error, remove instance, and re-raise:

```python
    try:
        validate(instance=jsonfile, schema=schema, resolver=resolver)
    except jsonschema.exceptions.ValidationError as e:
        e.instance = "<Omitted>"
        raise
```

Thanks Julian for writing and maintaining this library!
