### ISSUE TITLE
Local copy of remote JSON schemas

### ISSUE THREAD

**Issue by schwehr** [Julian/jsonschema#756]
I would like to be able to use validation in environments that do not have access to remote networks.  I've got testing and production environments that can't get to the schemas, but my development environment can.  I'd like to be able to snapshot all the remote files and use that as a cache locally that I embed in my application.  e.g.

https://stackoverflow.com/questions/15585493/store-the-cache-to-a-file-functools-lru-cache-in-python-3-2

This will have the benefit of allowing folks in the future to run against older schemas in the future even if those files have vanished from their original homes.

**Comment by Julian** [comment]
Hi there. Can you elaborate on what this ticket is asking for? Is it a feature request?

Nothing in `jsonschema` requires network access really. Are you asking about say the `store` argument to `RefResolver`s?

**Comment by schwehr** [comment]
In https://github.com/stac-utils/pystac, one can make a instance of a collection and then ask for validation.  My mistake... the fetching of json configs happens in `stac_io.py`.  I had thought it was a part of jsonschema.
