### ISSUE TITLE
"dependentRequired" did not work

### ISSUE THREAD

**Issue by butflame** [Julian/jsonschema#760]
Hi there.
It seems the validation keyword for objects "dependentRequired" did not work, 
I tried to find this keyword from source code but got nothing.

I just wanna make sure if this keyword has been implemented? (glad to contribute btw.)

**Comment by Julian** [comment]
Hi there! Yeah, `dependentRequired` is a draft2019-09+ validator, which isn't yet implemented. Certainly could use help if you'd like! There's extremely bare initial work on the `draft2019-09` branch, if you had incremental small improvements we could probably look at what's there together?

Thanks!
