### ISSUE TITLE
JSON Filtering

### ISSUE THREAD

**Issue by quentinmayo** [Julian/jsonschema#761]
Hi, 

I was curious. Is it possible to use the library to filter based on json schema?

**Comment by Julian** [comment]
Hi there. I'm not quite sure what you mean -- perhaps something like filtering some JSON input based on lines that validate or do not?

You certainly could do so by piping things through the `jsonschema` CLI, if that's what you mean.

Going to close this for cleanliness but if you have further issues you may ask perhaps in the JSON Schema Slack or via StackOverflow and someone may be able to give you some tips.

**Comment by quentinmayo** [comment]
Hi @Julian.  I would like to add more clarity.  I want to be able to remove additional properties based on the defined schema. Take for example: 

`
from jsonschema import validate, ValidationError, SchemaError
import json
schema = json.loads("""{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "glossary": {
      "type": "object",
      "properties": {
        "title": {
          "type": "string"
        },
        "GlossDiv": {
          "type": "object",
          "properties": {
            "title": {
              "type": "string"
            },
            "GlossList": {
              "type": "object",
              "properties": {
                "GlossEntry": {
                  "type": "object",
                  "properties": {
                    "ID": {
                      "type": "string"
                    },
                    "SortAs": {
                      "type": "string"
                    },
                    "GlossTerm": {
                      "type": "string"
                    },
                    "Acronym": {
                      "type": "string"
                    },
                    "Abbrev": {
                      "type": "string"
                    },
                    "GlossDef": {
                      "type": "object",
                      "properties": {
                        "para": {
                          "type": "string"
                        },
                        "GlossSeeAlso": {
                          "type": "array",
                          "items": [
                            {
                              "type": "string"
                            },
                            {
                              "type": "string"
                            }
                          ]
                        }
                      },
                      "required": [
                        "para",
                        "GlossSeeAlso"
                      ]
                    },
                    "GlossSee": {
                      "type": "string"
                    }
                  },
                   "additionalProperties": false,
                  "required": [
                    "ID",
                    "SortAs",
                    "GlossTerm",
                    "Acronym",
                    "Abbrev",
                    "GlossDef",
                    "GlossSee"
                  ]
                }
              },
              "required": [
                "GlossEntry"
              ]
            }
          },
          "required": [
            "title",
            "GlossList"
          ]
        }
      },
      "required": [
        "title",
        "GlossDiv"
      ]
    }
  },
  "required": [
    "glossary"
  ]
}""")
 
validJson = json.loads("""{
    "glossary": {
        "title": "example glossary",
		"GlossDiv": {
            "title": "S",
			"GlossList": {
                "GlossEntry": {
                    "ID": "SGML",
					"SortAs": "SGML",
					"GlossTerm": "Standard Generalized Markup Language",
					"Acronym": "SGML",
					"Abbrev": "ISO 8879:1986",
					"GlossDef": {
                        "para": "A meta-markup language, used to create markup languages such as DocBook.",
						"GlossSeeAlso": ["GML", "XML"]
                    },
					"GlossSee": "markup",
                    "ThisShouldNotBeHere":"25652512"
                }
            }
        }
    }
}""")

try:
    result = validate(validJson, schema)
 
except SchemaError as e:
    print("There is an error with the schema")
     
except ValidationError as e:
    temp = e
    #print(e)
     
    print("---------")
    print(e.absolute_path)
 
    print("---------")
    print(e.absolute_schema_path)
`

--------End of Code Block---

this will generate an error on the property "ThisShouldNotBeHere". I would like to feed the validator a JSON and output a filtered version. i.e. this 

`
{
    "glossary": {
        "title": "example glossary",
		"GlossDiv": {
            "title": "S",
			"GlossList": {
                "GlossEntry": {
                    "ID": "SGML",
					"SortAs": "SGML",
					"GlossTerm": "Standard Generalized Markup Language",
					"Acronym": "SGML",
					"Abbrev": "ISO 8879:1986",
					"GlossDef": {
                        "para": "A meta-markup language, used to create markup languages such as DocBook.",
						"GlossSeeAlso": ["GML", "XML"]
                    },
					"GlossSee": "markup",
                    "ThisShouldNotBeHere":"25652512"
                }
            }
        }
    }
}
`
Becomes this 
`
{
    "glossary": {
        "title": "example glossary",
		"GlossDiv": {
            "title": "S",
			"GlossList": {
                "GlossEntry": {
                    "ID": "SGML",
					"SortAs": "SGML",
					"GlossTerm": "Standard Generalized Markup Language",
					"Acronym": "SGML",
					"Abbrev": "ISO 8879:1986",
					"GlossDef": {
                        "para": "A meta-markup language, used to create markup languages such as DocBook.",
						"GlossSeeAlso": ["GML", "XML"]
                    },
					"GlossSee": "markup"
                }
            }
        }
    }
}
`
