### ISSUE TITLE
How to show a textarea in jsonschema

### ISSUE THREAD

**Issue by colordove** [Julian/jsonschema#764]
I wrote a json like this.
```
{
            "type": "object",
            "properties": {
                "host": {"type": "string"},
                "port": {"type": "number"},
                "conf": {"type": "textarea", "title": "config"}
            },
            "order": [
                "host",
                "port",
                "conf"
            ],
            "required": ["host", "port"],
}
```
I want to show a textarea, display it works, but can not pass the validator
![image](https://user-images.githubusercontent.com/11832969/102615868-957c6700-4171-11eb-8696-dbf958a181b8.png)

**Comment by Julian** [comment]
Hi there -- the error is telling you that there is no type called `textarea`. Not sure if you're trying to create one and should look at the type extension documentation or if you mean to do something else.

Going to close this but if you have issues you may try the JSON Schema slack who may be able to help with questions.
