### ISSUE TITLE
enforcing correct minimum/maximum constraint formats for specific types

### ISSUE THREAD

**Issue by PatMyron** [Julian/jsonschema#766]
As described more in https://github.com/aws-cloudformation/cloudformation-cli/issues/414:
[`string` uses `minLength`/`maxLength`](https://json-schema.org/understanding-json-schema/reference/string.html#length)
[`number`/`integer` uses `minimum`/`maximum`/etc.](https://json-schema.org/understanding-json-schema/reference/numeric.html#range)
frequently mixed up and doesn't seem to be caught during `jsonschema` validation yet

**Comment by Julian** [comment]
Hi there. Was this meant to be filed here?

The behavior described from a quick glance at that is the behavior specified by the JSON Schema specification.

Validators which only apply to certain types pass silently on other types.

If you want to protect against that you make sure you're validating type as well essentially.

Let me know if I've misunderstood the intention here.

**Comment by PatMyron** [comment]
>Validators which only apply to certain types pass silently on other types.

Meant to ask about this. Could keywords which only apply to other types be caught during schema validation?

**Comment by katzj-amzn** [comment]
+1 this would be a huge improvement to the validation.

**Comment by Julian** [comment]
I think a decent way to think about this is to write down a metaschema that does what you want.

Not sure it'd even be a very long schema, it's something like `{"required": ["type"], "allOf": [{"properties": {"type": {"const" : "string"}}, {"not" : {"properties" : {"minimum": {}, "maximum" : {}}}], ...` etc with the other two cases for array and object.

Don't know that I see something particularly special needed at the library level to do so once such a schema is written down.

**Comment by PatMyron** [comment]
This could definitely be handled just on our side, but thought this would be generally useful since many JSON schemas are mixing up these similar but slightly different JSON schema keywords

**Comment by Julian** [comment]
Right that metaschema would be usable by anyone presumably -- it'd be a way to validate that a schema doesn't use validators except within particular types.

Once we had it though anyone who wanted this behavior could validate against it.

**Comment by PatMyron** [comment]
there are actually 10 different min/max JSON schema keywords across 5 different types, which felt like a lot to schematize, so checking in Python for now:

https://github.com/aws-cloudformation/cloudformation-cli/pull/675

**Comment by Julian** [comment]
Fair enough, glad you got a solution that works.

I'm still a bit reluctant to add anything here given that this indeed *can* be specified within JSON Schema without any special support -- if someone writes down that metaschema that likely would help folks who want to do this (perhaps worth discussing upstream), but for now will close this given that I think a solution like that should address this generically without any additional work for end-users.

**Comment by PatMyron** [comment]
Similar problem with `additionalProperties` vs `additionalItems` if anyone else is looking into this
