### ISSUE TITLE
Get the property name of the current node that is being evaluated

### ISSUE THREAD

**Issue by gk12277** [Julian/jsonschema#767]
```
schema = {
   "type": "object",
   "properties":{ 
     "name": {
     "type": "string",
     "newKey: "value",
      } 
    },
}

def function_1(validator, properties, instance, schema):
      pass
  
Draft4Validator.VALIDATORS["newKey"] = function_1
Draft4Validator(schema).validate({"name":"123"})
```

function_1 will be called for each occurrence of `newKey` is it possible to get the name of the current node that is being evaluated ie. is it possible to get the key `name` inside function_1.
When I checked was only able to get value of key name `123`, value of newKey `value` and the schema.
I need the specific key that is being evaluated that is `name` in this case.

**Comment by Julian** [comment]
Hi -- you can do this by overriding the properties validator instead, which has view over the whole subobject.
