### ISSUE TITLE
jsonschema is unable to process input from stdin (shell pipe)

### ISSUE THREAD

**Issue by ssbarnea** [Julian/jsonschema#770]
One particular bug is very annoying is the inability to process input from stdin. Not only that but when given data on stdin, that is disregarded and the final exit code is zero (success). Please read https://clig.dev/#arguments-and-flags section in particular.

```shell
cat garbage | jsonschema some-schema.json
```
Apparently there were others that pinpointed the same issue but the bugs were closed.

There is one trick that can be used one *nix: `-i /dev/stdin` but that is not documented and not fully portable.

I do think that running with `--help` should mention how to perform schema validation from stdin, especially as the tool is not able to load other file formats like YAML, so we have to convert them on the fly and pipe them.

I would personally recommend a full read of https://clig.dev document which can is one of the best resources I found so far regarding how write good command line interfaces, what to do and what not to do. I am not affiliated with the author, just wanted to share it.

**Comment by Julian** [comment]
Happy to have a look. For what it's worth the CLI was "badgered" into the library :) in the sense that folks asked for a simple CLI, I resisted knowing there's no such thing as "simple" and that eventually folks show up wanting more and more functionality out of it, and well here we are :)

Happy to read that document, though FWIW I find what you showed a shell antipattern. Specifically, use shell IO redirection, not piping cat to things, i.e.:

```sh
jsonschema -i instance.json <(yaml2json foo.yaml)
```

Not:

```sh
cat foo.yaml | yaml2json | jsonschema -i instance.json -
```

**Comment by Julian** [comment]
Closing this for cleanliness since I think there's nothing more that needs doing here but happy to follow up if needed.
