### ISSUE TITLE
type: string format: regex does not fail on invalid regular expressions

### ISSUE THREAD

**Issue by thomasborgen** [Julian/jsonschema#775]
Hi, I'd like to validate regular expression strings, but it does not seem to give me an error on for example missing closing brackets etc.

tested with python 3.8.2, josnschema 3.2

```python
from jsonschema import Draft7Validator

schema = {
    '$schema': 'http://json-schema.org/draft-07/schema#',
    '$id': 'testid',
    'title': 'regex test schema',
    '$ref': '#/definitions/regexp',
    'definitions': {
        'regexp': {
            'description': 'Regex search string',
            'type': 'object',
            'properties': {
                'search': {
                    'type': 'string',
                    'format': 'regex',
                },
            },
            'required': ['search'],
        },
    },
}


validator = Draft7Validator(schema)

print(validator.check_schema(schema))

print(validator.is_valid({'search': 'test'}))
# True
print(validator.is_valid({'search': '[0-9'}))
# True, but i expect False because of missing bracket.
```

**Comment by Julian** [comment]
Hi. Please review the docs on validating format: 

https://python-jsonschema.readthedocs.io/en/stable/validate/#validating-formats

**Comment by thomasborgen** [comment]
Sry i missed that and its clear from the docs.

Because `type` is enforced it didn't even cross my mind that `format` wouldn't be.
If its about performance would argue that having it enabled/enforced by default would make more sense as one would expect that the rules you set in your schema is executed and checked.

Is there any specific reason why it's not enabled by default?

**Comment by Julian** [comment]
That is what the specification requires.

`format` is indeed not like `type`. By default, it's informational only. Validation is opt-in behavior in implementations.

Have a look at the format spec for some more notes on why.

**Comment by thomasborgen** [comment]
I see, I'll read up about it.
Thanks for the replies, and thanks for the awesome library.
