### ISSUE TITLE
Validator fails to catch invalid enums in an array

### ISSUE THREAD

**Issue by PeteW** [Julian/jsonschema#776]
Consider the following code:
```
import json
import jsonschema

v = """
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "Reqs": {
      "type": "array",
      "items": [
        {
          "type": "object",
          "properties": {
            "Id": { "type": "string" },
            "Items": {
              "type": "array",
              "items": [
                {
                  "type": "object",
                  "properties": {
                      "Val": { "type": "string", "maxLength": 50 },
                      "Type": { "enum": ["A", "B", "C"]}
                  },
                  "required": [
                    "Val",
                    "Type"
                  ]
                }
              ]
            }
          }
        }
      ]
    }
  },
  "required": [
    "Reqs"
  ]
}
"""
o = {
    'Reqs': [
        {
            'Id': 'foo',
            'Items': [
                { 'Val': 'abc', 'Type': 3 },
                { 'Val': 'abc', 'Type': 'A' },
            ],
        },
    ]
}
jsonschema.validate(o, json.loads(v))
```
This correctly raises a ValidationError `Failed validating 'enum' in schema['properties']['Reqs']['items'][0]['properties']['Items']['items'][0]['properties']['Type']`
Good!

But when I change the order of `Items` such that the bad item is second, not first,
```
o = {
    'Reqs': [
        {
            'Id': 'foo',
            'Items': [
                { 'Val': 'abc', 'Type': 'A' },
                { 'Val': 'abc', 'Type': 3 },
            ],
        },
    ]
}
jsonschema.validate(o, json.loads(v))
```
The exception is no longer raised. Am I doing something incorrectly?

**Comment by PeteW** [comment]
I attempted to work around this by replacing the `enum` with `pattern` but the same result happens. It seems to be a general issue where only the first object in the collection is validated?

**Comment by Julian** [comment]
That's what putting a single schema in an array for `items` does. It's the first item in an array, so it'll validate the first element in the instance array.

It sounds like you instead mean to write `items: yoursubschema` rather than `items: [yoursubschema]`, which applies the subschema to all items rather than just the first.

**Comment by PeteW** [comment]
Wow. Subtle but impactful nuance! @Julian thank you for the quick response! My apologies on the false issue. I'm glad to see it is my side that is wrong here.

**Comment by mrsarm** [comment]
I don't get it. I have the same issue, how the schema posted here get fixed? could you @PeteW or @Julian show the full schema fixed please?
