### ISSUE TITLE
integer type doesn't seem to work

### ISSUE THREAD

**Issue by mastupristi** [Julian/jsonschema#777]
Hi,
I read on the website https://json-schema.org/understanding-json-schema/reference/numeric.html#integer about the possibility to use the type `integer`.

I modified an example as follows:
```python
import json
import jsonschema
from jsonschema import validate

# Describe what kind of json you expect.
studentSchema = {
    "type": "object",
    "properties": {
        "name": {"type": "string"},
        "rollnumber": {"type": "integer"}, # rollnumber is an integer
        "marks": {"type": "number"},
    },
}

def validateJson(jsonData):
    try:
        validate(instance=jsonData, schema=studentSchema)
    except jsonschema.exceptions.ValidationError as err:
        return False
    return True

# Convert json to python object.
jsonData = json.loads('{"name": "jane doe", "rollnumber": 25.0, "marks": 72}')
# validate it
isValid = validateJson(jsonData)
if isValid:
    print(jsonData)
    print("Given JSON data is Valid")
else:
    print(jsonData)
    print("Given JSON data is InValid")
```

running it I get the following output:

```
{'name': 'jane doe', 'rollnumber': 25.0, 'marks': 72}
Given JSON data is Valid
```
I expected that 25.0 is not valid because it is a floating point type (even if its value is that of an integer number).
is this a bug?

my system is xubuntu 20.10, python 3.8.6, jsonschema 3.2.0.

best regards
Max

**Comment by Julian** [comment]
Hi. Not sure what you expect really. 25.2 isn't an integer. Am I missing the question?

**Comment by mastupristi** [comment]
> Hi. Not sure what you expect really. 25.2 isn't an integer. Am I missing the question?

Sorry, I wrote the wrong example. I have now modified it

**Comment by Julian** [comment]
So, for that, it's a decent idea when you're unsure of a particular behavior to check the specification before filing a ticket.

Here, yes, it's correct behavior, the JSON schema specification as of draft 7 (which is the draft you're using here) treats integers as any number with 0 fractional part. The understanding JSON schema tutorial you linked is unfortunately out of date and deals with much older drafts.

Have a look at the spec for draft 7 for further info if you'd like.
