### ISSUE TITLE
Exceptions always output to console when casting to string?

### ISSUE THREAD

**Issue by ravensorb** [Julian/jsonschema#783]
I am curious, is there any specific reason the full schema is always output to the console when casting an exception to a string?

https://github.com/Julian/jsonschema/blob/b0be7bf48e6554a00296307f7c84283a77738267/jsonschema/exceptions.py#L69

Would it make more sense to move this to the python logging framework?

**Comment by Julian** [comment]
Hi. Not sure what you mean -- are you asking / questioning that output is produced just via calling `str(ValidationError)`? It isn't, that's `pformat`, which produces a string, it doesn't write anything to stdout unless you print / write it yourself.

**Comment by ravensorb** [comment]
Interesting -- so I have a validation error that is occuring and as soon as I do a logger.debug(str(error)) inside of a except statement the entire schema and json is output to the console even when I have logging set to INFO only.  I couldn't find anything in my code that was dumping it to the console so I started looking at the code base as saw the pprint line and I think I jump to the conclusion that it was causing the issue (bad on my part) :-/

**Comment by Julian** [comment]
No worries.
