### ISSUE TITLE
Zenodo Archive?

### ISSUE THREAD

**Issue by vsoch** [Julian/jsonschema#784]
hey @Julian ! I'd like to add JsonSchema to the [Research Software Encyclopedia Software showcase](https://rseng.github.io/rseng/blog/), and one of the things that we do is show researchers how to cite it. I noticed that you don't have a paper or citation, and was wondering if you'd be open to adding a Zenodo DOI for it? It's fairly easy to connect the repo via GitHub at https://zenodo.org/ and then add the badge here. It's okay if you don't want to, but I wanted to ask. Thanks!

**Comment by Julian** [comment]
Hi there! Thanks, that sounds great -- probably am happy to. I believe I just linked it within Zenodo, but looks like to get a DOI requires another release, correct?

One's been in the works for the last few months already I just haven't set aside time to do it, so if one's required that shouldn't be a big deal, will maybe be some extra motivation...

**Comment by vsoch** [comment]
That's correct - it will trigger on release! I'll put a watch on your repository so that when it releases, I can add the Zenodo DOI to the RSEPedia post. So future folks can cite it, and (better) support you (I added your sponsors links to the post).

Academics / researchers are terrible at citing all the software they use, and pigs will probably fly before you see individual researchers GitHub sponsoring them (but I hope I am wrong). I'm trying to be very loud to get more attention for libraries like yours, but I'm just one voice. I do think if researchers can start to speak up to their institutions / companies about what is being used, the companies could turn around and contribute meaningfully (money, that is). But who knows if this model for GitHub sponsors will work in the long run. I hope so, and if not, maybe something else would.

**Comment by Julian** [comment]
@vsoch At long last a release is out, and I believe the badge is now in the README.

Super appreciate your support! (And the suggestion). It's really great to have more people focused on making things better!

**Comment by vsoch** [comment]
It looks great! :tada:  Thank you!

**Comment by vsoch** [comment]
Okay, the post from earlier this year was updated: https://rseng.github.io/rseng/software/jsonschema#cite and I updated the associate tweet as well.  https://twitter.com/vsoch/status/1443361553374318593 Thank you again!

**Comment by Julian** [comment]
Thank you!!
