### ISSUE TITLE
ValidationError are too verbose to be used for linting a file

### ISSUE THREAD

**Issue by ssbarnea** [Julian/jsonschema#787]
I tried to use jsonschema in order to lint some files but I discovered that ValidationError errors only contain a single error message that is a very long error message, something that would be ineligible for a normal user due to the amount of noise.

Example of error reported when a user introduced an invalid value for an array of enums (licenses):
```
# e.message
'\'{"name": "foo", "namespace": "bar", "version": "1.2.3", "authors": ["John"], "readme": "../README.md", "description": "...", "dependencies": {"other_namespace.collection1": ">=1.0.0", "other_namespace.collection2": ">=2.0.0,<3.0.0", "anderson55.my_collection": "*"}, "license": ["GPL", "Apache"]}\' is not of type \'object\''
```

```
# input file (instance) that used https://github.com/ansible-community/schemas/blob/main/f/ansible-galaxy.json schema
name: foo
namespace: bar
version: 1.2.3
authors:
  - John
readme: ../README.md
description: ...
dependencies:
  "other_namespace.collection1": ">=1.0.0"
  "other_namespace.collection2": ">=2.0.0,<3.0.0"
  "anderson55.my_collection": "*"    # note: "*" selects the highest version available
license:
  - GPL # <-- these are the invalid values
  - Apache
```

Is there a way to get jsonschema library to raise some errors that could be rendered as linting errors? displaying the entire input json file makes it impossible to use as a practical linter. I was not able to identify other more detailed fields inside the exception, ones that could be used to generate a shorter error message.

**Comment by Julian** [comment]
Have you seen the ValidationError documentation](https://python-jsonschema.readthedocs.io/en/stable/errors/)?

**Comment by Julian** [comment]
I suspect what you're looking for here is covered either on that page or on the general validation documentation. Closing for cleanliness, but happy to follow up if you find a specific gap.
