### ISSUE TITLE
Create jsonschema from Openconfig yang Model

### ISSUE THREAD

**Issue by mahen-g** [Julian/jsonschema#789]
Hi,

Is there a way to generate a jsonschema from openconfig yang models.
Intent is the below

1. Generate jsonschema using openconfig yang models.
2. Get the instance of the data  from switch for the particular model.
3. Use validate to verify the instance data  with the jsonschema 

Thanks,

**Comment by Julian** [comment]
Hi there. I can't say I know what Openconfig yang is myself. This may be a good topic for either a discussion (and someone else who knows may chime in) or for the JSON Schema slack (where other folks may know what that is)
