### ISSUE TITLE
Throwing ERROR against DMTF Schema.

### ISSUE THREAD

**Issue by abirami-sekar-3** [Julian/jsonschema#793]
Ran the JsonSchema tool ,
for Systems/{{SystemID}}/SD, we have "AliasBootOrder" property under "Boot",

as per the schema it is an array, and when the underlying values are not present , we are showing empty array in response as shown below,

![image](https://user-images.githubusercontent.com/81425094/112659207-2a31e780-8e7a-11eb-97c6-3915daff9eef.png)

when on running this tool, we are getting error as below,
![image](https://user-images.githubusercontent.com/81425094/112659129-17b7ae00-8e7a-11eb-813f-5c9c3177ade6.png)

With Regards,
Abirami S

**Comment by Julian** [comment]
Hi there. Not sure which project you meant to file this on, but pretty sure this isn't the right one -- this one isn't a web app. Hope you figure the issue out.

**Comment by abirami-sekar-3** [comment]
Hi Julian,
Yes, i will tell the steps i have followed in short,

1. created a python file with the below content in Linux machine  (validate.py),

          import jsonschema, re, json

        **schema_file** = "/root/Downloads/ComputerSystem.v1_8_0.json"
        **json_response** = "/root/Downloads/SD.json"
        def jsonschema_validation(schema_file, json_response):
            with open(schema_file, 'r', encoding='utf8') as f:
                schema = json.load(f)
            with open(json_response, 'r', encoding='utf8') as f:
                json_response = json.load(f)
            try:
                jsonschema.validate(instance = json_response, schema = schema)
                print("Schema Validation Pass", "Pass")
            except Exception as e:
                print("Schema Validation Fail", "Fail")
                print("Validation Error Info:", "Fail")
                print(" --> ".join([i for i in e.path]))
                print(re.sub("<|>|class|'| ", "", str(type(e))))
                print(e.message)
                print(e.context)
                print(e.validator)
                print(e.validator_value)
                print(e.cause)
        
        jsonschema_validation(schema_file, json_response)


2.  Update schema_file and json_response in the py file with required path,
      schema_file will refer the json file DMTP path,
      json_response will refer the response saved in *.json file

3. then execute with python3,

![python3](https://user-images.githubusercontent.com/81425094/112663266-a0384d80-8e7e-11eb-9c6a-bfc0977d44c6.png)

this is how i tried, 
please let me know if anything is wrong.

thank you,
Abirami S

**Comment by Julian** [comment]
So you're saying it's indeed this library you're referring to?

Can you elaborate then on what issue you're reporting?

You have a validation error it seems, is there something you're not expecting about that?
