### ISSUE TITLE
Indicate violated range values in error messages

### ISSUE THREAD

**Issue by abcdenis** [Julian/jsonschema#796]
Hi,
I have simple schema for verification 'name' field of API request:
```
from jsonschema import validate

schema = {
    "type": "object",
    "required": [
        "name"
    ],
    "properties": {
        "name": {
            "description": "name",
            "type": "string",
            "minLength": 2,
            "maxLength": 10
        }
    }
}

instance = {'name': ''}

validate(instance=instance, schema=schema)
```

Which leads to exception with output like this:
```
jsonschema.exceptions.ValidationError: '' is too short

Failed validating 'minLength' in schema['properties']['name']:
    {'description': 'name',
     'maxLength': 10,
     'minLength': 2,
     'type': 'string'}

On instance['name']:
    ''
```

I catch validation exceptions and pass first line of exception message to API response.
Unfortunately it doesn't suggest correct string length for client.

It will be helpful to have self-sufficient error messages:
```
jsonschema.exceptions.ValidationError: '' is too short, minimal size is 2 characters.
```

To avoid massive change for clients it could be hidden under `verbose=False` validate()'s option.

Thank you.

**Comment by Julian** [comment]
Hi there -- `jsonschema`'s precise error messages [are not part of its public API](https://python-jsonschema.readthedocs.io/en/stable/faq/#how-do-jsonschema-version-numbers-work) and aren't really intended to be shown directly to end-users -- if you want a precise / self contained error message, it should be possible to do this yourself via the attributes available on the error object. E.g. `if error.validator == "minLength": message = f"{error.instance} is too short, minimal size is {len(message.instance)} characters.` or thereabouts.

**Comment by abcdenis** [comment]
Thank you!
I will use jsonschema.exceptions.ValidationErrors from public API.
