### ISSUE TITLE
Benchmarks not running in JsonSchema

### ISSUE THREAD

**Issue by babu1998** [Julian/jsonschema#798]
I first did a git clone of the main branch.

Then i read the docs from here 

[jsonschema-docs](https://python-jsonschema.readthedocs.io/en/stable/)

I tried both the commands 
1. tox -e perf
2. python -m pyperf jsonschema/benchmarks/test_suite.py --hist --output results.json

I even tried installing tox and pyperf but still got error in running the Benchmarks.

**Comment by Julian** [comment]
Fixed in c4d94f3, thanks.
