### ISSUE TITLE
fastjsonschema.compile() equivalent?

### ISSUE THREAD

**Issue by gitpushdashf** [Julian/jsonschema#806]
Is there something equivalent to fashjsonschema's .compile()?

https://horejsek.github.io/python-fastjsonschema/#fastjsonschema.compile

The FHIR R4 jsonschema is pretty massive and slow to load.

https://www.hl7.org/fhir/downloads.html

**Comment by Julian** [comment]
The most direct equivalent would be instantiating a [Validator](https://python-jsonschema.readthedocs.io/en/stable/validate/#versioned-validators) with the schema. Other than that fastjsonschema is as far as I recall just an entirely different execution model.

Not 100% sure what you mean by slow to load -- jsonschema doesn't do any loading, perhaps you mean slow to validate with, but yeah if you're not already using them, instantiating a validator is the most basic thing there to try.

**Comment by Julian** [comment]
Closing since yeah, that's what's here, but happy to follow up to discuss if there are any further thoughts.
