### ISSUE TITLE
install from source without internet

### ISSUE THREAD

**Issue by themaddoctor** [Julian/jsonschema#809]
Hi. I need to install from source on a machine with no internet capabilities.
Can you please provide a setup.py that can accomplish this? Thanks.

**Comment by Julian** [comment]
Hi there. Doing so shouldn't be much different from any other Python package, e.g. via `pip download jsonschema` on a machine with internet, followed by `pip install --find-links` on the one without.

If you need more guidance you likely can find tutorials to do so in the packaging documentation.
