### ISSUE TITLE
format checker support for `format=uri`

### ISSUE THREAD

**Issue by satra** [Julian/jsonschema#827]
is there a reason why `format="uri"` is not supported by checkers?

format checkers don't seem to have uri in the list.

```
In [30]: v.format_checker
Out[30]: <FormatChecker checkers=['date', 'email', 'hostname', 'idn-email', 'idn-hostname', 'ipv4', 'ipv6', 'regex']>
```

this code passes validation.

```python
import jsonschema
import json

schema = json.loads("""{
      "title": "Anatomy",
    "type": "object",
    "properties": {
      "identifier": {
        "title": "Identifier",
            "type": "string",
            "format": "uri"
      }
    }
}""")
v = jsonschema.Draft6Validator(schema, format_checker=jsonschema.draft7_format_checker)
v.validate({"identifier": "word"})
```

**Comment by Julian** [comment]
Possibly you don't have the dependency installed?

**Comment by satra** [comment]
that is correct. looking at the documentation indeed it says it will silent ignore missing formats. perhaps it would be nice to put a strict keyword arg or something that forces a warning or exception when a format checker is missing.

**Comment by Julian** [comment]
The issue is would you have known to look for it?

The spec says formats must be ignored by default.

**Comment by satra** [comment]
> would you have known to look for it?

in this particular case i was looking at the docstring (in ipython) of the validator and the validate command and i suspect IDEs would have prompted those as well. so potentially. so at least through that route, i think people would find it. 

i only dug into it because i was expecting a validation to fail and it didn't.
