### ISSUE TITLE
[FEATURE] schema to python object with default values

### ISSUE THREAD

**Issue by Saifu0** [Julian/jsonschema#831]
I'm not able to find a way to convert my json schema to a python object with some default values. Like I wanted to convert my schema with a key-value python object where key will be actual field of the schem and value will be some default value.

If we don't have support of this feature as of now, I can take it and implement this feature.

Please let me know.

**Comment by Julian** [comment]
Hey. Are you referring to [this](https://python-jsonschema.readthedocs.io/en/stable/faq/#why-doesn-t-my-schema-s-default-property-set-the-default-on-my-instance)?

**Comment by Julian** [comment]
I think the link is what you're asking about, but feel free to follow up with more details if not.
