### ISSUE TITLE
false positive

### ISSUE THREAD

**Issue by cryply** [Julian/jsonschema#835]
Hi

I get no exception with following code. 
updatedAt is string but schema has number and validation pass.

```
import jsonschema
from jsonschema import validate


set_tl_schema = {
    "type" : "object",
    "properties" :  {

    "level": {
      "value": {"type" : "number"},
      "updatedAt": {"type" : "number"}
    }
}
}

x = {'level': {'updatedAt': '1970-01-01T00:00:00.000Z', 'value': 1}, }

try:
    validate(instance=x, schema=set_tl_schema)
except jsonschema.exceptions.ValidationError as ex:
    print(ex)
```

**Comment by Julian** [comment]
Your schema is missing a `properties` object inside of `level`.

**Comment by cryply** [comment]
Ignoring invalid schema is bad behavior for validator.

**Comment by Julian** [comment]
The schema isn't invalid, and this behavior is required by the specification, unknown validators are required to be ignored by default.
