### ISSUE TITLE
Unable to reference a json schema from an external file.

### ISSUE THREAD

**Issue by Agent-Hellboy** [Julian/jsonschema#836]
**├── __init__.py
├── common
│   └── common_schema.json
├── main1_schema.json
├── main2_schema.json**

I am not able to reference common_schema from main1_schema and main2_schema.

I tried with `file:common_schema.json#/common_data` but it is not working
I am getting  the following error 
`jsonschema.exceptions.RefResolutionError: <urlopen error [Errno 2] No such file or directory: '/snr_info_def_schema.json'>
`

when I tried with `file://common_schema.json#/common_data` 
I am getting the following error
`jsonschema.exceptions.RefResolutionError: <urlopen error [Errno 2] No such file or directory: ''>
`

 `is it because I am working inside a package?`--->`As I have to use pkg_resources to load the schema`

This is a small package for schema validation having an internal API to load JSON schema files and a public API which will take JSON data and validate it with the loaded JSON schema.  

Is it possible to use "$ref" inside a package having static files inside it(In this case JSON files)?
can I get some insights on `how ref is implemented`?

**Comment by Agent-Hellboy** [comment]
Is it possible to use "$ref" inside a package having static files inside it(IN this case JSON files)?
can I get some insights on `how ref is implemented`?

**Comment by RomainTT** [comment]
Maybe `--base-uri` option is what you need. Sorry I don’t have time to dig it.

**Comment by Agent-Hellboy** [comment]
Thanks for the reply. But I didn't get you. please elaborate.

**Comment by Agent-Hellboy** [comment]
I resolved it with the help of RefResolver().
