### ISSUE TITLE
Is there any interest in adding c extension support?

### ISSUE THREAD

**Issue by skamensky** [Julian/jsonschema#838]
I'm interested in the Python C-extension scene and thought this project may have some low hanging performance fruit to pick.

Is there any interest in that? Is performance something that needs attention here? 

(P.s. I saw the benchmarking section and don't run it yet. I'm on mobile and didn't want to forget to write this!)

**Comment by Julian** [comment]
Hi! Thanks for the offer.

I'm willing certainly to consider performance improvements, under ~3 conditions essentially:

* they indeed should start with a benchmark -- the one that's called `issue232` may be good enough to try out whether you can improve performance somehow by taking a hot path and moving it to C
* they should not use the CPython C API -- they either should use [CFFI](https://cffi.readthedocs.io/) or [hpy](https://hpyproject.org/) though I haven't followed hpy closely enough to know whether it's a good choice yet
* they should be as minimal as possible (i.e. target just hot paths), and CI needs to be modified under any combination of source that can happen

But yeah contributions are more than welcome here! There likely is indeed performance improvement to be had on CPython for some things.

**Comment by skamensky** [comment]
Understood, thanks for the quick response @Julian.

I'll likely check this out within a week or so. Out of curiosity, what are the reason you'd like to avoid the Cpython C API?

Is it because Hpy is considered a modern alternative? I've heard of it but haven't tried it out yet.
And/or to avoid all of the rituals in the c extension code?

**Comment by Julian** [comment]
Great thanks.

> Is it because Hpy is considered a modern alternative? 

Yep, but also even before hpy, cffi is easier to write and works better on other implementations like PyPy, so even without hpy there are better options.

**Comment by skamensky** [comment]
Re pypi, that makes sense.

I've been doing some reading of the documentation of both Hpy and cffi. Hpy had its first public release only 2 months ago and seems to be incomplete.

Given a choice between cffi and hpy, I'd prefer to do the initial attempt using cffi. It seems more mature and has the advantage of built in separation between the implementation and the python glue. Is that okay with you?

I also noticed you have some secrets in the ci. When I get a chance to look into this more deeply I'll attempt to fork this repo and get the ci working in the fork. Here's to hoping that'll be easy!

**Comment by Julian** [comment]
> Is that okay with you?

Yes definitely fine!

> I also noticed you have some secrets in the ci. When I get a chance to look into this more deeply I'll attempt to fork this repo and get the ci working in the fork. 

It's just the codecov.io token, which these days actually isn't even necessary I believe, but if you have trouble do let me know.

**Comment by Julian** [comment]
Going to close this but again definitely happy to see any benchmark you come up with!
