### ISSUE TITLE
Fix packaging tags to drop Python version support

### ISSUE THREAD

**Issue by Lothiraldan** [Julian/jsonschema#845]
The recent release of JsonSchema 4.0.0 seems to drop support for Python 2 (and Python 3.5 also but it might been dropped before) but pip is having issues getting the right version depending on the Python version.

The correct information is in the setup.cfg https://github.com/Julian/jsonschema/blob/main/setup.cfg#L23

I think there are two issues for pip to pick the correct version based on the python version:
* The python-requires seems to be correctly packaged in the file `jsonschema-4.0.0.tar.gz` but not in the file `jsonschema-4.0.0-py3-none-any.whl`. It looks like it's missing the correct metadata in the `METADATA` file. It should be a line similar to: `Requires-Python: >=3.7`
* For pip to be able to get the correct package version, it needs at least two package versions with the proper package metadata https://packaging.python.org/guides/dropping-older-python-versions/#dropping-a-python-release. I would recommend releasing a version 3.2.1 with the following metadata: `python_requires = ">=2.7, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*, !=3.4.*"`.

I believe once both these actions are done, pip should be happy and users should get the proper version of jsonschema installed. I would be happy to help if needed.

**Comment by Lothiraldan** [comment]
@tirkarthi Looks like you are correct, I also think the setup.cfg needs to be corrected.

**Comment by tirkarthi** [comment]
yes, I just verified it and the metadata is generated correctly.

**Comment by tirkarthi** [comment]
I just created https://github.com/Julian/jsonschema/pull/846 as a fix.

**Comment by Julian** [comment]
4.0.0 has been yanked, and 4.0.1 released, which I believe I confirm locally means both pre-3.7 and post 3.7 environments seem to get the correct versions now.

Thanks for the diagnosis and fix @tirkarthi , @Lothiraldan and others.

**Comment by tirkarthi** [comment]
Thanks @Julian
