### ISSUE TITLE
"format": "date-time" not working now in 4.0.1 release

### ISSUE THREAD

**Issue by thorwolpert** [Julian/jsonschema#848]
Adding in strict-rfc3339 allowed version 3.x to validate "format": "date-time"

The 4.0.1 has changed that and now allows values such as 
'this should fail'

Schema snippet:
```
            "effectiveDate": {
              "type": "string",
              "format": "date-time",
              "title": "The date and time a filing should become valid and applied.",
              "default": "",
              "examples": ["1970-01-01T00:00:00+00:00"]
            },
 ```
and this returns valid
```
Draft7Validator(schema,
                           format_checker=draft7_format_checker,
                           resolver=resolver
                           ) \
                .is_valid(json_data)
```

**Comment by Julian** [comment]
Feel free to follow up with more details. Otherwise ensure you're installing the `format` setuptools extra.

**Comment by thorwolpert** [comment]
thanks, that worked.
Sorry for the bad issue.
Thank you very much for such a quick response, wasn't expecting that.

**Comment by Julian** [comment]
Great glad to hear.
