### ISSUE TITLE
jsonschema.exceptions.SchemaError: ... is not of type 'object', 'boolean'

### ISSUE THREAD

**Issue by bneradt** [Julian/jsonschema#849]
Apache Traffic Server has some tests which use jsonschema to verify the JSON files that its Traffic Dump plugin produces verifies correctly against a jsonschema. The test passes through jsonschema release 3.x, but with the 4.x releases it fails when parsing the following part of the schema:

https://github.com/apache/trafficserver/blob/44d1be681245f73e82eee59699ad0660dea91290/tests/tools/lib/replay_schema.json#L169

Pasted here for convenience:

```    "header-fields": {
      "description": "HTTP header fields.",
      "type": "object",
      "required": ["fields"],
      "properties": {
        "encoding": {
          "description": "Encoding applied to field values.",
          "$ref": "#/definitions/encoding"
        },  
        "fields": {
          "description": "The field name and value pairs.",
          "type": "array",
          "items": {
            "description": "HTTP field.",
            "type": "array",
            "items": [
              {   
                "description": "Name of the field.",
                "type": "string"
              }, {
                "description": "Value of the field.",
                "type": "string"
              }   
            ]   
          }   
        }   
      }   
    },  
```

The error looks like the following:

```
Traceback (most recent call last):
  File "verify_replay.py", line 446, in <module>
    sys.exit(main())
  File "verify_replay.py", line 394, in main
    if not validate_json(schema_json, replay_json):
  File "verify_replay.py", line 53, in validate_json
    jsonschema.validate(instance=replay_json, schema=schema_json)
  File "/home/bneradt/.local/share/virtualenvs/tests-RWaVYdAG/lib/python3.8/site-packages/jsonschema/validators.py", line 963, in validate
    cls.check_schema(schema)
  File "/home/bneradt/.local/share/virtualenvs/tests-RWaVYdAG/lib/python3.8/site-packages/jsonschema/validators.py", line 183, in check_schema
    raise exceptions.SchemaError.create_from(error)
jsonschema.exceptions.SchemaError: [{'description': 'Name of the field.', 'type': 'string'}, {'description': 'Value of the field.', 'type': 'string'}] is not of type 'object', 'boolean'                                                                                                                        

Failed validating 'type' in metaschema['properties']['definitions']['additionalProperties']['$dynamicRef']['allOf'][1]['properties']['properties']['additionalProperties']['$dynamicRef']['allOf'][1]['properties']['items']['$dynamicRef']['allOf'][1]['properties']['items']['$dynamicRef']['allOf'][0]:       
    {'$defs': {'anchorString': {'pattern': '^[A-Za-z_][-A-Za-z0-9._]*$',
                                'type': 'string'},
               'uriReferenceString': {'format': 'uri-reference',
                                      'type': 'string'},
               'uriString': {'format': 'uri', 'type': 'string'}},
     '$dynamicAnchor': 'meta',
     '$id': 'https://json-schema.org/draft/2020-12/meta/core',
     '$schema': 'https://json-schema.org/draft/2020-12/schema',
     '$vocabulary': {'https://json-schema.org/draft/2020-12/vocab/core': True},
     'properties': {'$anchor': {'$ref': '#/$defs/anchorString'},
                    '$comment': {'type': 'string'},
                    '$defs': {'additionalProperties': {'$dynamicRef': '#meta'},
                              'type': 'object'},
                    '$dynamicAnchor': {'$ref': '#/$defs/anchorString'},
                    '$dynamicRef': {'$ref': '#/$defs/uriReferenceString'},
                    '$id': {'$comment': 'Non-empty fragments not allowed.',
                            '$ref': '#/$defs/uriReferenceString',
                            'pattern': '^[^#]*#?$'},
                    '$ref': {'$ref': '#/$defs/uriReferenceString'},
                    '$schema': {'$ref': '#/$defs/uriString'},
                    '$vocabulary': {'additionalProperties': {'type': 'boolean'},
                                    'propertyNames': {'$ref': '#/$defs/uriString'},
                                    'type': 'object'}},
     'title': 'Core vocabulary meta-schema',
     'type': ['object', 'boolean']}

On schema['definitions']['header-fields']['properties']['fields']['items']['items']:
    [{'description': 'Name of the field.', 'type': 'string'},
     {'description': 'Value of the field.', 'type': 'string'}]

```

Again, parsing this works if I pin jsonschema to 3.2.0. On the face of it, that exception seems to indicate that the first part of each header field should be an 'object' and the second part of each entry should be a boolean instead of a string, but I'm not sure why it would think that. Maybe I'm not understanding the message correctly?

For reference, here's an example json HTTP field entry corresponding to the above jsonschema specification:

```
                        "headers": {
                            "encoding": "esc_json",
                            "fields": [
                                [
                                    "Host",
                                    "www.notls.com"
                                ],
                                [
                                    "x-request-1",
                                    "0000000 0000001"
                                ],
                                [
                                    "Content-Length",
                                    "0"
                                ],
                                [
                                    "uuid",
                                    "1"
                                ]
                            ]
                        },
```

Where, for the first field, `Name of the field` corresponds to `"Host"` and `Value of the field` corresonds to `"www.notls.com"`.

Thank you for your work on jsonschema. Let me know whether there's anything I can provide to help with this issue.

**Comment by bneradt** [comment]
Maybe the extra specification for each field has to be specified with `prefixItems` instead of `Items` with the later versions of json schema?

```
            "prefixItems": [
              {   
                "description": "Name of the field.",
                "type": "string"
              }, {
                "description": "Value of the field.",
                "type": "string"
              }   
```

That change seems to get the schema parsing to pass for both jsonschema 3.x and 4.x.

Reference:
https://json-schema.org/understanding-json-schema/reference/array.html

> In Draft 4 - 2019-09, tuple validation was handled by an alternate form of the items keyword. When items was an array of schemas instead of a single schema, it behaved the way prefixItems behaves.

Can you please confirm whether this is indeed my problem (i.e., I should use `prefixItems` instead of `Items`). If so, please comment as such and close this issue.

Thanks!

**Comment by Julian** [comment]
> Thank you for your work on jsonschema. Let me know whether there's anything I can provide to help with this issue.

Thanks for the kind words.

That error message looks suspicious (i.e. there's undoubtedly a bug there, but dynamicRef support is a known unfortunate last piece missing from 2020-12 support, so it may not be a trivial one to avoid).

Are you trying to update your schema to 2020-12? Or just to maintain something previously working? In general in any schema you should be setting a key in your schema called `$schema` which identifies what version of the JSON Schema specification you're trying to target. That makes you not at the whim of changes from version-to-version, so if you're not otherwise specifically intending to update your schema (i.e. if you're not looking for a specific draft2020-12 feature) you may be best off just making sure you have `$schema` set and pointing to the Draft 7 URI if that's what version your schema is written for?

**Comment by bneradt** [comment]
> you may be best off just making sure you have $schema set and pointing to the Draft 7 URI

Thanks for the tip.

Feel free to close this issue or leave open as a reference for any work you may or may not do with the log message. With the update to my schema, I'm currently in good shape now. 👍

**Comment by Julian** [comment]
Great glad to hear!

Will do (though feel free to keep an eye out for dynamicRef support in the future :)
