### ISSUE TITLE
invalid validation error

### ISSUE THREAD

**Issue by foolioo** [Julian/jsonschema#887]
Given a [Renovate configuration file](https://docs.renovatebot.com/modules/manager/regex/#configuration-templates) `renovate.json`

```shell
$ cat renovate.json
{
  "regexManagers": [
    {
      "fileMatch": ["^Dockerfile$"],
      "matchStrings": ["ENV YARN_VERSION=(?<currentValue>.*?)\n"],
      "depNameTemplate": "yarn",
      "datasourceTemplate": "npm"
    }
  ]
}
```

When running check-jsonschema it reports an error

```shell
$ wget -q https://docs.renovatebot.com/renovate-schema.json
$ jsonschema --instance renovate.json renovate-schema.json
ENV YARN_VERSION=(?<currentValue>.*?)
: 'ENV YARN_VERSION=(?<currentValue>.*?)\n' is not of type 'array'
```

These are the details of my environment
```shell
$ python --version
Python 3.9.9

$ pip show jsonschema | grep -i version
Version: 4.2.1
```

I confirm that the same issue happens on previous released versions. (e.g. 3.2.0)

**Comment by Julian** [comment]
Hi, please include the schema you're using.

**Comment by foolioo** [comment]
hi @Julian, it is included, see the `wget` command, but in case it was missed, [this is the schema](https://docs.renovatebot.com/renovate-schema.json)

**Comment by Julian** [comment]
I see, sorry. Can you minimize your example to the minimum schema and instance which triggers the unexpected behavior? Doing so will likely reveal what part of your schema is causing the behavior. It's honestly unlikely there's a bug here, but if it turns out there is, I'm happy to look at the minimized example.

**Comment by foolioo** [comment]
> Can you minimize your example to the minimum schema and instance which triggers the unexpected behavior? 

Here we go :)

```json
{
  "regexManagers": [
    {
      "matchStrings": "ENV YARN_VERSION=(?<currentValue>.*?)\n"
    }
  ]
}
```

> It's honestly unlikely there's a bug here, but if it turns out there is, I'm happy to look at the minimized example.

Thanks!

**Comment by Julian** [comment]
And the schema? That's the main bit to minimize.

**Comment by foolioo** [comment]
> And the schema?

Oops, sorry for that. Here we go

```json
{
  "properties": {
    "regexManagers": {
      "type": "array",
      "items": {
        "allOf": [
          {
            "type": "object",
            "properties": {
              "matchStrings": {
                "type": "array",
                "items": {
                  "type": "string",
                  "format": "regex"
                }
              }
            }
          }
        ]
      },
      "default": []
    }
  }
}
```

**Comment by Julian** [comment]
You have `"matchStrings": {"type": "array"}`, and it's not an array, which the message is telling you.

**Comment by Julian** [comment]
Let me know if the above is somehow unclear, but hopefully that helps.

**Comment by foolioo** [comment]
@Julian: I appreciate the quick response - you are awesome.

Will close this as it seems there is no issue. If something will pop, I will reopen.

**Thank you**
