### ISSUE TITLE
Version jsonschema 3.2.0 installs importlib-metadata version 4.10.0 which is not compatible with python 3.6

### ISSUE THREAD

**Issue by fervand1** [Julian/jsonschema#898]
3.2.0 version of jsonschema is mentioned as compatible with python 3.6 but it pulls newer version of importlib-metadata 4.10.0 which is not compatible with python 3.6. This needs to be pinned at importlib-metadata==4.8.3 for python versions  3.7 and lower

**Comment by Julian** [comment]
importlib-metadata seems to properly declare it depends on 3.7: https://github.com/python/importlib_metadata/blob/main/setup.cfg#L18

I don't have a Py3.6 to test at the minute, but are you on a very old pip?

**Comment by fervand1** [comment]
Well I am not able to install jsonschema==3.2.0 on python 3.6
Because it fails to get importlib-metadata
I don’t remember the pip version though I can check that but it was trying to install importlib-metadata==4.10.0 and it failed saying can’t find the version on python 3.6. I can’t upgrade python at the moment though

**Comment by Julian** [comment]
I didn't say to upgrade python, just your pip if that's out of date (and not doing so means jsonschema may not be the only thing broken for you).

What is `python3.6 -m pip --version`?

**Comment by fervand1** [comment]
I understand. I see the pip version as 21.0.1

**Comment by Julian** [comment]
Getting my hands on a Py36, here it seems to properly install the right version of importlib-metadata (4.8.3 which seems to be the last version supporting 3.6):

```
Collecting jsonschema
  Downloading jsonschema-3.2.0-py2.py3-none-any.whl (56 kB)
     |████████████████████████████████| 56 kB 3.4 MB/s
Collecting attrs>=17.4.0
  Downloading attrs-21.4.0-py2.py3-none-any.whl (60 kB)
     |████████████████████████████████| 60 kB 5.9 MB/s
Collecting pyrsistent>=0.14.0
  Downloading pyrsistent-0.18.0.tar.gz (104 kB)
     |████████████████████████████████| 104 kB 12.0 MB/s
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Requirement already satisfied: setuptools in ./site-packages (from jsonschema) (44.0.0)
Collecting six>=1.11.0
  Downloading six-1.16.0-py2.py3-none-any.whl (11 kB)
Collecting importlib-metadata; python_version < "3.8"
  Downloading importlib_metadata-4.8.3-py3-none-any.whl (17 kB)
Collecting zipp>=0.5
  Downloading zipp-3.6.0-py3-none-any.whl (5.3 kB)
Collecting typing-extensions>=3.6.4; python_version < "3.8"
  Downloading typing_extensions-4.0.1-py3-none-any.whl (22 kB)
Building wheels for collected packages: pyrsistent
  Building wheel for pyrsistent (PEP 517) ... done
  Created wheel for pyrsistent: filename=pyrsistent-0.18.0-py3-none-any.whl size=56340 sha256=59e7878cc08fd7fd82e970aba59805fc96f0b2518e2483dcb73f5afd752a11b8
  Stored in directory: /home/julian/.cache/pip/wheels/44/eb/cd/6b9fba4c0896ca88b9ea628527b3853f26ce1fe29ba6fb73ec
Successfully built pyrsistent
Installing collected packages: attrs, pyrsistent, six, zipp, typing-extensions, importlib-metadata, jsonschema
Successfully installed attrs-21.4.0 importlib-metadata-4.8.3 jsonschema-3.2.0 pyrsistent-0.18.0 six-1.16.0 typing-extensions-4.0.1 zipp-3.6.0
```

You'll have to share your full install (the result of running say `python3.6 --version; python3.6 -m pip --version; python3.6 -m pip install jsonschema`) to be sure, though I'm somewhat confident this will be an issue with your environment.

Going to close, but feel free to share the above if you'd like some help.

**Comment by fervand1** [comment]
Thanks @Julian yea seems like its an environment issue.
