### ISSUE TITLE
4.0.0 yanked because of false py36 support

### ISSUE THREAD

**Issue by GlenNicholls** [Julian/jsonschema#900]
I've been using jsonschema with python3.6 on centos7. I didn't realize that the python3.6 support was incorrect on PyPi and now I'm getting a warning in CI and when installing my package. Things are still working fine and I don't plan to change anything. However, I'm curious to know what in the code isn't 3.6 compliant so I can avoid it? Also, is there a risk that the 4.0.0 release will be removed entirely in the future?

**Comment by Julian** [comment]
Hi there. It will never be deleted entirely off PyPI (doing so is really really bad behavior), just yanked.
I don't remember what doesn't work on 3.6, you can run tox/the test suite on 3.6 (and see what fails) or find the commit that bumped the version, one of the two should hopefully explain.

**Comment by GlenNicholls** [comment]
Looks like importlib_metadata doesn't support <py3.7. Thanks for the insight, I'll keep an eye on it and hopefully won't run into any issues.
