### ISSUE TITLE
jsonschema.validate does not fail on unexpected input

### ISSUE THREAD

**Issue by HoneyryderChuck** [Julian/jsonschema#901]
Hi, I've just noticed that the library is not validating input which is not referenced in the schema:

```python
import jsonschema
schema = {
  "type": "object",
  "properties": {
    "name": {
      "type": "string",
      "description": "the configuration field identifier."
    }
  },
  "$schema": "http://json-schema.org/schema#"
}
jsonschema.validate({"name": 1}, schema) #=> jsonschema.exceptions.ValidationError: 1 is not of type 'string' jsonschema.validate({"a": 1}, schema) #=> nothing happens
```

Is there a way that one could be more strict validating input using this library? Potentially a `flask` extension (which is where we use this library)?

**Comment by Julian** [comment]
Hi there -- yes, properties in the JSON Schema specification are not required by default.

You could certainly write a Python function that takes a schema and automatically adds the required validator, or you could write a custom validator (see the docs) which does the same at validation time.

**Comment by HoneyryderChuck** [comment]
Hi @Julian thank you for the answer. 

Which docs do you mean? I'm looking at https://python-jsonschema.readthedocs.io/ but I didn't find a "how to write a custom validator" section.

**Comment by Julian** [comment]
https://python-jsonschema.readthedocs.io/en/stable/creating/#jsonschema.validators.extend

**Comment by HoneyryderChuck** [comment]
thank you 🙏
