### ISSUE TITLE
Import error in 4.4.0

### ISSUE THREAD

**Issue by jrtcppv** [Julian/jsonschema#903]
I am getting an error in this package on the following line in `jsonschema/_format.py`:

`from __future__ import annotations`

The error I get is:

`SyntaxError: future feature annotations is not defined`

**Comment by Julian** [comment]
What version of Python are you on?

**Comment by jrtcppv** [comment]
This is in a Docker container using `ubuntu:18.04` base image; the apt version of python is 3.6.9. There was a similar issue I found here: https://github.com/altdesktop/python-dbus-next/issues/10
