### ISSUE TITLE
Drop setuptools dependency in v3

### ISSUE THREAD

**Issue by EpicWink** [Julian/jsonschema#908]
The setuptools requirement was dropped for version 4.0a1, but some packages out there (notably [docker-compose](https://github.com/docker/compose)) still requires `jsonschema` v3. I'm requesting d647d72 is applied to the tag [v3.2.0](https://github.com/Julian/jsonschema/releases/tag/v3.2.0), and then released as a new version (for example v3.2.1)

Related: #631

**Comment by Julian** [comment]
Hi. 3.x is no longer supported, so generally this would not be done. docker-compose will at some point presumably upgrade.

Can you elaborate on why this is important to you?

**Comment by EpicWink** [comment]
I use [pip-tools](https://pypi.org/project/pip-tools/) to pin my app dependency versions, and docker-compose is one of those dependencies. However, pip-tools refuses to pin setuptools (as it "may cause conflicts with pip itself"), so I have to install setuptools separately before installing the packages in my lock file (with `--no-deps`). This is currently working, so this request isn't blocking me.

I have submitted a request for docker-compose to upgrade: docker/compose#9128

**Comment by Julian** [comment]
Got it, yes feel free to take this upstream. You also can tell pip-tools to pin setuptools regardless, or add it afterwards.
