### ISSUE TITLE
Dependency on `uritemplate` and/or `uri_template`

### ISSUE THREAD

**Issue by TheChymera** [Julian/jsonschema#911]
Does jsonschema as of 4.* depend on both, or just the second of these packages?

In the Gentoo package manager, jsonschema is set to depend on uritemplate only, and while the package passes all tests, as of `>jsonschema-4` [downstream packages have thrown errors](https://github.com/dandi/dandi-cli/issues/825#issuecomment-1034935312).

Also, does the `[format]` extra require any additional build options, or does it only control further dependencies? It could be that our package just misses this extra.

**Comment by Julian** [comment]
Hi there -- indeed the canonical place for this is the [`format` setuptools extra](https://github.com/Julian/jsonschema/blob/ee5d31afb08ef0a1592ce54431f3f9c59ad95bbf/setup.cfg#L46) -- `uri_template` with the underscore is the dependency. It doesn't require any additional build options.

(`uri_template` support was blocked on https://github.com/python-hyper/uritemplate/pull/36, which means tests do not pass with it).

Hope that helps!
