### ISSUE TITLE
multipleOf does not work consistently for negative numbers

### ISSUE THREAD

**Issue by claria** [Julian/jsonschema#914]
Hi,

thanks for the great library!

I tried to use the multipleOf keyword to validate negative fractional numbers.

While this works for some numbers

`jsonschema.validate(-0.001, {'type': 'number', 'minimum': -1, 'maximum': 1, 'multipleOf': 0.001})`
it fails for others:
`jsonschema.validate(-0.059, {'type': 'number', 'minimum': -1, 'maximum': 1, 'multipleOf': 0.001})`

```
ValidationError: -0.059 is not a multiple of 0.001

Failed validating 'multipleOf' in schema:
    {'maximum': 1, 'minimum': -1, 'multipleOf': 0.001, 'type': 'number'}

On instance:
    -0.059
```

The reason could be that -0.059 / 0.001 = -58.9999 in python but i am not sure.

**Comment by Julian** [comment]
Hi. Thanks for the kind words!

Yes, this is a property of floating point numbers, nothing specific neither to this library nor even Python.

If you want precise division, you may want to use `decimal.Decimal` to load your JSON (or in your validation in general), which this library supports.
